### ISSUE TITLE
pop-up filters won't close with multiple row hearders / low width columns

### ISSUE THREAD

**Issue by Insorior** [koalyptus/TableFilter#100]
Hi there !

One of my table has many columns so I had to manage each column width. 

_I can open the pop-up filter, but I won't be able to click the filter button again as the filter popup hides it (starts from the middle of the cell rather than from the filter icon)
![capture](https://cloud.githubusercontent.com/assets/16704873/12327454/ede6f2a6-bad6-11e5-8148-bf9db98ffd2f.PNG)

_ for low width columns, the filters is very thin and really hard to use properly (many line breaks, the filter should be larger...)
![capture2](https://cloud.githubusercontent.com/assets/16704873/12327457/f82666fc-bad6-11e5-9eed-5a60597ecdb0.PNG)

Thanks for your support !

**Comment by koalyptus** [comment]
Thanks @Insorior for your valuable feedback on the pop-up filters feature.
There are currently many issues UI wise with the pop-up filters, as you point out here, without mentioning the fact that they are not touch friendly at all. The intention is to gradually improve this feature over time, but if you can't wait for future releases, there is room for some tweaking at the moment:
1. define a custom CSS class for the element containing the filter:
```
var yourConfig = {
...
  popup_filters: true,
  popup_div_css_class: 'custom-css-class',
...
};
```
with this CSS definition as an example, same as default one but with higher top margin value:
```
.custom-css-class {
    background: #fff;
    -webkit-box-shadow: 3px 3px 2px #888;
    -moz-box-shadow: 3px 3px 2px #888;
    box-shadow: 3px 3px 2px #888;
    margin: 50px auto 0 0;
    position: absolute;
    display: none;
    width: 100px;
    background-color: #eaeaea;
    border: 1px solid #eaeaea;
    padding: 0;
}
```
2. disable an obscure property called ``popUpFltAdjustToContainer`` which adjusts the pop-up filter container element width to the cell's width:
```
var yourConfig = {
...
  on_filters_loaded: function(tf) {
    var feature = tf.feature('popupFilter');
    feature.popUpFltAdjustToContainer = false;
  },
...
};
```

If you try those, tell me how it goes.

Cheers

**Comment by cjohnsonuk** [comment]
Alternatively look to put your filter drop downs in a separate part of the page like here : http://tablefilter.free.fr/external-grid.htm

**Comment by koalyptus** [comment]
Refer to this demo instead:
http://koalyptus.github.io/TableFilter/external-filters.html

**Comment by cjohnsonuk** [comment]
Thanks for the link. I've been looking for that one for the last couple of
weeks!:-)

**Comment by koalyptus** [comment]
Cool closing this issue then,
Cheers
