### ISSUE TITLE
Status bar not displayed correctly

### ISSUE THREAD

**Issue by Insorior** [koalyptus/TableFilter#112]
Hello,

I'm working on a large table with a lot of columns. As it's too large to be displayed entirely, I have put it inside of a <div style="overflow:scroll;">.

I'm also using the following configuration options : 
status_bar: true,
btn_reset: true,
rows_counter: true,

My problem is that instead of remaining at the right of the div, the reset and info buttons go to the right of the scrollable table and are not visible (users must scroll to the right to reset their filters).

I gave a look into the docs and wasn't able to find a trick.
Do you have any advice?

Thanks in advance

**Comment by koalyptus** [comment]
Hi @Insorior,
I am not sure I understood correctly your question: you wrapped a large table in a ``div`` but the `info` and 'reset' button are still displayed at right of the toolbar which is not visible to the user. The toolbar is part of the table by default so it will match the table's width even if contained in a 'responsive' div.
There might be different options to solve this assuming my understanding is correct:
- Generate the toolbar in a custom element (``toolbar_target_id`` option), have a look to this demo:
http://koalyptus.github.io/TableFilter/external-toolbar.html
- Generate the individual buttons (info and reset) in custom elements (``help_instructions_target_id`` and ``btn_reset_target_id``)
- Use the grid layout instead with the ``grid_width`` set to ``'100%'``

**Comment by koalyptus** [comment]
closing this as no news good news :)

**Comment by Insorior** [comment]
Hello ! 

After a few weeks working on other modules for my application, I actually found a way to manage my problem. Instead of putting my whole table into a <dif overflow> element, I just used this setup : 

<table>
<thead>
... 1st table row goes here in <th> tags
</thead>
<tbody style="overflow:auto;width:XXXpx">
... Content rows here
</tbody>
</table>


Using this, only the table body is being scrolled. PLUS : the pop-up filters remain stuck to the table headers.

**Comment by koalyptus** [comment]
Hi @Insorior,
Happy to hear that!
Just by curiosity, was it an option for you to use the `grid_layout` mode?

**Comment by Insorior** [comment]
Hi !

I actually did not use this option. Here is my config set : 

var filtersConfig = {
        base_path: \'../scripts/tablefilter/\',
		col_0: \'checklist\',
		col_4: \'checklist\',
		col_5: \'checklist\',
		col_6: \'checklist\',
		col_7: \'select\',
		col_8: \'checklist\',
		col_9: \'checklist\',
		col_10: \'checklist\',
        auto_filter: true,
        auto_filter_delay: 1100, //milliseconds
        remember_grid_values: true,
        alternate_rows: true,
        rows_counter: true,
        rows_counter_text: "Lignes affichées : ",
        btn_reset: true,
        status_bar: true,
        no_results_message: true,
        msg_filter: \'Tri en cours...\',popup_filters: true,
		popup_div_css_class: \'popup-filters-css-class\',
	   on_filters_loaded: function(tf) {
    var feature = tf.feature(\'popupFilter\');
    feature.popUpFltAdjustToContainer = false;
  },
    };
