### ISSUE TITLE
sort_num_desc doesn't appear to have any affect on drop down sort order

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#113]
We're trying to get our drop downs sorted into numerical order.

Numbers 0-13 in our drop down sort in the order 0,1,10,11,12,13,2,3,etc

Here's an extract from our tf config : 

 ```
 sort_select: 'true',
  sort_num_desc: [0,4],
  col_0: 'multiple',
  col_3: 'select',
  col_4: 'multiple',
  col_5: 'multiple',
```

I've checked and there are no alpha characters, only numeric, in the column

Any ideas

**Comment by koalyptus** [comment]
Thanks for pointing this out, I confirm the this functionality is currently broken, it is a bug due to large refactoring happened lately.
It will be hopefully fixed in the next release.

**Comment by koalyptus** [comment]
Should now be fixed in v.0.1.11. 
By the way, you don't need to set ``sort_select`` as ``true`` by default.

**Comment by koalyptus** [comment]
Closing this as no news good news :)
