### ISSUE TITLE
extension sort:  example for sort_col_at_start[]

### ISSUE THREAD

**Issue by m67hoff** [koalyptus/TableFilter#116]
Hy I'm try to find a example/documentation for sort_col_at_start to  sort a column descending at start 

my code at the moment, but I'm not sure that this was the idea since even google does not find any hint to sort_col_at_start   

```       
var tf = new TableFilter( 'log_table', {
            base_path: "/tablefilter/",   
            alternate_rows: true,
            rows_counter: true,
            btn_reset: true,
            highlight_keywords: true,            
            status_bar: true,
            filters_row_index: 1,
            enable_checklist_reset_filter: false, 
            msg_filter: 'Filtering...',
            col_2: 'checklist',
            col_3: 'checklist',
            col_widths: [ "5%", "10%", "7%", "7%"  ],
            extensions: [{
                name: 'sort', 
                types: [ 'number', 'none', 'none', 'none', 'none' ],
                sort_col_at_start: [ false, 'null', 'null', 'null', 'null'  ]
                }]
}) 
```

**Comment by koalyptus** [comment]
Hi @m67hoff,
You just need to specify the column index and a boolean set true for descending sort, sort_col_at_start: [2, true].
Sort documentation:
https://github.com/koalyptus/TableFilter/wiki/3.1-Sort

Cheers

**Comment by m67hoff** [comment]
Hy,

thanks that helped.  

BTW:  I already had looked into  the  3.1-sort wiki above before asking.  However because of the "table formatting"  in my firefox I was not aware that there are "more columns" also with a example: 

![capture](https://cloud.githubusercontent.com/assets/16188530/12810603/90051e90-cb27-11e5-8a8b-b85f3269c39e.JPG)

thanks again for help - and the really helpful tablefilter library   (can close now)

Grüße aus Heidelberg - Michael

**Comment by koalyptus** [comment]
Thanks Micheal, it is the same for all browsers, it is due to GitHub's wiki page layout and table styling.
