### ISSUE TITLE
OnAfterFilter Event Handler Not Firing

### ISSUE THREAD

**Issue by vnomus** [koalyptus/TableFilter#118]
We have TF configuration in which we are attempting to attach a JavaScript handler for the OnAfterEvent. However, the handler never fires. Inspecting the TF object just after initialization shows that OnAfterEvent property is null. Manually setting it in the debugger still doesn't seem to resolve the issue as the handler (now set) still fails to fire. The rest of the filter functionality works as expected. Thank you in advance for help in resolving this!...

Here's a screen shot of the TF config object.... 
![tf_config](https://cloud.githubusercontent.com/assets/1231006/12856800/a689595e-cc14-11e5-8f5a-8cfe06c51c13.PNG)

Here's a screen shot of the initialized TF object...
![tf_initialized](https://cloud.githubusercontent.com/assets/1231006/12856807/ad45f4a0-cc14-11e5-9336-f663a16c23be.PNG)

**Comment by koalyptus** [comment]
It seems to me you are assigning a string instead of a function to ``on_after_filter``, try this instead:
```
on_after_filter: function(o){ CalcCost(); }
```

**Comment by vnomus** [comment]
You are exactly correct, thank you for your help!...
