### ISSUE TITLE
Set cookie for the Columns visibility

### ISSUE THREAD

**Issue by WinChris** [koalyptus/TableFilter#120]
It would be better if there are cookie for the columns visibility

**Comment by koalyptus** [comment]
The way state is persisted will go through some refactoring to adopt localStorage and fallback to cookies.
At that stage, additional features state will be persisted, things like column sorting and columns visibility are good candidates.
By the way, you could easily implement that by taking advantage of the ``colsVisibility`` extension callbacks (``on_after_col_hidden`` and ``on_after_col_displayed``)

**Comment by WinChris** [comment]
Ok thank you can you explain me how to use this function : getHiddenCols()

**Comment by koalyptus** [comment]
Assuming ``tf``` references an instance of ``TableFilter``:
```var colsVisibility = tf.extension('colsVisibility');
var hiddenColumnIndexes = colsVisibility.getHiddenCols();```

**Comment by koalyptus** [comment]
Columns visibility is now persisted as per http://koalyptus.github.io/TableFilter/persistence.html demo.
Cheers
