### ISSUE TITLE
Linked Filters and checklists

### ISSUE THREAD

**Issue by pLeBlanc93** [koalyptus/TableFilter#122]
I was experimenting with the data and example on [Linked Filters](http://koalyptus.github.io/TableFilter/linked-filters.html) and I changed the filtering type of `col_1` from `multiple` to `checklist` and the items are being duplicated when either of the checklist items are selected.

![chk](https://cloud.githubusercontent.com/assets/12817527/13088933/4440996e-d4a3-11e5-9fd1-120d06145625.PNG)

Can linked filtering work when there are multiple checklist filters?

**Comment by koalyptus** [comment]
Thanks for pointing this out, looks like a bug to me, I'll have a look.

**Comment by koalyptus** [comment]
It should now be fixed in v0.1.15,
Cheers

**Comment by pLeBlanc93** [comment]
Verified, thanks!
