### ISSUE TITLE
custom_options and strings

### ISSUE THREAD

**Issue by snacke** [koalyptus/TableFilter#123]
Hi!

When using custom_options with strings as values, is it possible to define a "select" option that comprises more than one value?

Example: The table entries in one column are A, B, C, D or E. I want a filter option that shows alls rows with A or B, and hides other rows. I tried the following code, but it did not work.

```
custom_options: {
            cols:[1],
            texts: [
                [
                    'A or B',  'C',  'D',  'E'
                ]
            ],
            values: [
                [
                    'A' || 'B',  'C',  'D', 'E'
                ]
            ],
            sorts: [false]
        },

```
Is there a way to achieve the function that I'm looking for?

Many thanks!

**Comment by koalyptus** [comment]
Hi,
the whole expression is a string, try this instead:
```
custom_options: {
            cols:[1],
            texts: [
                [
                    'A or B',  'C',  'D',  'E'
                ]
            ],
            values: [
                [
                    'A || B',  'C',  'D', 'E'
                ]
            ],
            sorts: [false]
        },
```
Have a look this demo: http://koalyptus.github.io/TableFilter/custom-filter-options.html
Cheers

**Comment by snacke** [comment]
Excellent! Thank you very much!! =D
