### ISSUE TITLE
table init and clearFilters()

### ISSUE THREAD

**Issue by pLeBlanc93** [koalyptus/TableFilter#125]
I'm trying to call `tf.clearFilters()` after `tf.init()`. Is FilterTable being created as a deferred? If so, when would I have access to call `tf.clearFilters()`?

**Comment by koalyptus** [comment]
Just tried this and worked synchronously:
```
var tf = new TableFilter('demo', {
        base_path: '../dist/tablefilter/'
});
tf.init();
tf.setFilterValue(0, 'hello');
tf.clearFilters();
```
 there are some features that are async though.

**Comment by koalyptus** [comment]
You can hook-up into into particular events with callbacks:
```
var tf = new TableFilter('demo', {
    base_path: '../dist/tablefilter/',
    on_filters_loaded: function(o) {
        //o is the TableFIlter instance
        console.log('hello', o);
    }
});
```
or you can subscribe to an event with the event emitter:
```
var tf = new TableFilter('demo', {
    base_path: '../dist/tablefilter/'
});
tf.emitter.on(['initialized'], function(o){
    console.log('hello', o);
});
tf.init();
```

**Comment by pLeBlanc93** [comment]
Ahh perfect! The event emitter did the trick.

Thanks for the quick response.
