### ISSUE TITLE
Update url when filters are selected

### ISSUE THREAD

**Issue by mohitsuman** [koalyptus/TableFilter#127]
When a particular filter is selected from the table, the url should be updated. Is there any configuration parameter for this which can be added?

**Comment by koalyptus** [comment]
If you mean to have a stateful URL to maintain filters state and allow deeplinking, this is definitely a feature in the roadmap and related to #43.

**Comment by koalyptus** [comment]
V0.2.3 now supports deep linking for filters and pagination:
http://koalyptus.github.io/TableFilter/deep-linking.html
