### ISSUE TITLE
Popup filter and single filter configuration not working together

### ISSUE THREAD

**Issue by mohitsuman** [koalyptus/TableFilter#139]
Hi,

I tried implementing "popup_filters" and single_filter together. But only one of them works in conjunction. Is there any configuration that enables both of them. I want to implement single filter on the table and popup_filters on some selected columns.

JS: https://jsfiddle.net/azqwvdqL/

**Comment by koalyptus** [comment]
Hi @mohitsuman,
There is no such a configuration option, `single_filter` and `popup_filters` are mutually exclusive. It might be possible to have an external search box setting the `single_filter` behaviour programmatically upon search and removing it when filtering is completed. However once the table is filtered with the single search, if you filter a column with a popup filter, you will loose the previous filtering.

**Comment by mohitsuman** [comment]
Thanks @koalyptus for the help. However if we need to add programatically the single filter behaviour as external search box.

I am adding > tf.setFilterValue(0, query); But the setFilterValue() function takes only particular column index as first parameter. What specification should be passed so that it performs search on every column of the table.

**Comment by koalyptus** [comment]
Try to generate your single filter as an external one, refer to http://koalyptus.github.io/TableFilter/external-filters.html for that and then once working, try the setFiltetValue with index 0.
