### ISSUE TITLE
Change default dropdown Clear text

### ISSUE THREAD

**Issue by nolbyte** [koalyptus/TableFilter#140]
Hi!
Can we change or replace 'Clear' text on dropdown filter select according to the values on each column?
Thank you

**Comment by koalyptus** [comment]
Hi @nolbyte, 
At the moment the same `display_all_text` option value is applied to all the drop-down filter types, you cannot have a different value per column.
This seems to be a good candidate for a feature request, tagging it as enhancement.
Cheers

**Comment by nolbyte** [comment]
Hi @koalyptus 
Have you  implement my question on your new update?
Thank you

**Comment by koalyptus** [comment]
Hi @nolbyte,
Not yet, it is a nice to have but not yet prioritised as important refactoring tasks in the works.
Cheers
