### ISSUE TITLE
TableFilter is undefined when loading page with IE8

### ISSUE THREAD

**Issue by mmaction** [koalyptus/TableFilter#142]
Hi
I'm getting an error when loading page with tablefilter with IE 8.0.6. No problems with newer browser versions or other browsers.

IE says:
"Object doesn't support this action". tablefilter.js line 7
"TableFilter is undefined" in MyCgi.cgi line 576 --> which is " tf = new TableFilter('tblRemoteUnits',...."

I'm using tablefilter v0.0.7, build date 2015-10-28 with ezEditTable extension v2.3, 15.3.2015

Do you have any idea what causes this problem with IE8?
kind regards
michael

_______________________________________

here is my html code (unimportant stuff removed):

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<title></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="expires" content="0" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="pragma" content="no-cache" />
<link rel="stylesheet" href="../global.css" type="text/css" />
<link href="../tablefilter/style/tablefilter.css" rel="stylesheet" type="text/css"/>
 <script language="javascript" src="../global.js" type="text/javascript"></script>
</head>
 
<body onload="if (typeof onPageLoad == 'function') {onPageLoad();}">
  <div id="divContent">
    <table id="tableContent">
      <tr>
        <td style="vertical-align:top;">
        </td>
        <td style="vertical-align:top; width:100%;">
          <form action="PlatformRemoteUnits.cgi" method="post">
          <table id="tableRightContent">
            <tr><td>
              <table id="tableDialog" style="visibility:hidden;">
                <tr>
                  <td class="boldLeft" style="vertical-align:bottom;padding-bottom:10px;"></td>
                </tr>              
                 <tr style="display:none;">
                  <td>
                  </td>  
                 </tr>                                
                <tr>
                  <td>                   
                    <table class="tblData" id="tblRemoteUnits">
                      <thead>
                         <tr>
                          <th class="bglightgray">No.</th>
                          <th class="bglightgray">Unit&nbsp;ID</th>
                          <th class="bglightgray">Address</th>
                          <th class="bglightgray">Entry&nbsp;Type</th>
                          <th class="bglightgray">Connection</th>    
                           <th style="display:none;"></th>
                           <th style="display:none;"></th>
                           <th style="display:none;"></th>
                         </tr>
                      </thead>                                         
                      <tbody>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </table>
                                      
      <script language="javascript" src="../tablefilter/tablefilter.js" type="text/javascript"></script>    
           <script type="text/javascript">
      //<![CDATA[
 
        var tf = null; 
 
        // --------------------------------------
        function openNewWindow(address)
        // --------------------------------------
        {
        }     
 
        // --------------------------------------
        function onPageLoad()
        // --------------------------------------      
        {                                          
        }
 
        // --------------------------------------
        function reselectEntry()
        // --------------------------------------      
        {    
         }                                       
 
        // --------------------------------------
        function updateButtons()
        // --------------------------------------      
        {         
        }          
 
         // --------------------------------------
        function onAfterFilter(o)
        // --------------------------------------     
         {                                                                                                 
         }
                
            // --------------------------------------
        function adjustCounter(o)
        // --------------------------------------     
         {                                                                                                                        
         }
 
        // --------------------------------------      
        function CheckSelection()
        // --------------------------------------
        {  
        }                                                 
 
        // --------------------------------------      
        function copyCellValues(row)
        // --------------------------------------
        {
         }
 
        // --------------------------------------
        function updateAfterSelection(activeRow)
        // --------------------------------------      
        {               
        }                         
 
        // --------------------------------------
         function afterRowSelected(o, row)   
        // -------------------------------------- 
         {                                              
         }
 
        // --------------------------------------
         function onSelectionInitialized(o)   
        // -------------------------------------- 
         { 
           ...
           document.getElementById("tableDialog").style.visibility = "visible";
        }            
                      
        /* Setup table filtering */
         tf = new TableFilter('tblRemoteUnits',
         {                       
                 /* filters behaviour */
                 base_path: '../tablefilter/',
                 col_widths: [ "38px", "142px", "340px", "81px", "188px", null, null, null ],     
                 col_0: "none",
                 col_3: "select",
            col_5: "none",
            col_6: "none",
            col_7: "none",
                 filters_row_index: 1,  
                 auto_filter: true,
                 auto_filter_delay: 0,
                 remember_grid_values: true,
                 alternate_rows: true,
                 mark_active_columns: true,
                 watermark: "search...",
                 on_after_refresh_counter: adjustCounter,
                 on_after_filter: onAfterFilter,            
 
                 /* drop-down filter */
                 display_all_text: "All",        
 
                 /* grid layout */
                 grid_layout: true,
                 grid_height: '228px',  
                 grid_width: '778px',
 
                 /* status bar, rows counter, help instructions, reset button */
                 status_bar: true,
                 rows_counter: true,    
                 rows_counter_text: 'Number of Entries: ',      
                 btn_reset: true,
                 help_instructions: false,
 
                 /* extensions*/    
                 extensions:
                 [
                 {
                   name: 'sort',
                           types: ['Number', 'String', 'ipaddress', 'String', 'String', 'none', 'none', 'none' ], 
             },
                         {
                           name: 'advancedGrid',
                           vendor_path: '../ezEditTable/',
                           selection_model: 'multiple',              
                           on_after_selected_row: afterRowSelected,
                           on_selection_initialized: onSelectionInitialized,
                           nb_rows_per_page: 11,                                           
                         }      
            ], 
 
         });                  
         tf.init();         
                                                  
      //]]>
      </script>         
            </td></tr>
          </table>
        </form>
      </td>
    </tr>
    </table> 
  </div>
</body>
</html>

**Comment by koalyptus** [comment]
Hi @mmaction,
I am afraid IE8 is no longer supported, applying the (latest version - 2) rule in terms of browsers versions support.
