### ISSUE TITLE
Conditional formatting

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#148]
Is it possible to set the background colour of a cell based on its contents eg >90 = green, <10 = red, otherwise blue, or "yes"= green, "no"= red etc

I've had a quick scan through but can't see anything...

If I coded it myself would the tablefilter css not override it?

**Comment by koalyptus** [comment]
Have a look to this freshly added demo:
http://koalyptus.github.io/TableFilter/conditional-cell-formatting.html
It might help.
Cheers

**Comment by cjohnsonuk** [comment]
Thanks. That looks great!
Might be worth turning pagination on in that demo as that dataset is really
long!
Chris

**Comment by koalyptus** [comment]
Just turned pagination on.
Cheers
