### ISSUE TITLE
Doesn't work in IE <= 10

### ISSUE THREAD

**Issue by andreyjamer** [koalyptus/TableFilter#153]
Plugin doesn't work in IE 9-10 because of class inheritance. The problem is same like https://phabricator.babeljs.io/T3041

It can be fixed by adding 
`plugins:` [['transform-es2015-classes', {loose: true}]]
to the babel section in webpack config.

I,ve built using this option and got working plugin in IE 9-10.

**Comment by koalyptus** [comment]
Thanks a lot Andrey, 
Upgraded to babel6 recently but didn't realize that.
Don't hesitate to raise a PR if you wish.
Cheers

**Comment by andreyjamer** [comment]
Made a PR. 
Check please.

**Comment by koalyptus** [comment]
Thanks for pointing this out @andreyjamer, PR is now merged and demos are now working with IE <= 10.

**Comment by andreyjamer** [comment]
Ok. Thank you
