### ISSUE TITLE
Leaves filter span tag in DOM after filter reset

### ISSUE THREAD

**Issue by ITSecMedia** [koalyptus/TableFilter#155]
Orphan filter markers when the filter gets reset <span class="keyword"></span> 
The marker tags sum up each time you apply a filter and reset 

<td class="pm_oz">
**<span class="keyword"></span>
<span class="keyword"></span>
<span class="keyword"></span>**
1oz</td>

**Comment by koalyptus** [comment]
Thanks for reporting this, are you referring to popup filter types?

**Comment by ITSecMedia** [comment]
I've noticed it when I used **dropdown filters** on certain columns 
as I applied a css style that uses some background together with padding
after resetting the filter I had a growing red bar in front of the cell value

**Comment by ITSecMedia** [comment]
the close was a mistake :(

**Comment by ITSecMedia** [comment]
Sorry

**Comment by koalyptus** [comment]
Hi @ITSecMedia ,
Please give more context about your first comment, I thought it was related to the popup filters but couldn't reproduce the span leftovers issue. It would be helpful to have steps on how to reproduce the issue and also the version you are using.
Cheers

**Comment by ITSecMedia** [comment]
Should be the current version from Github.

Please visit this link and try yourself : [http://www.bullion-investor.com/gold/krugerrand](http://www.bullion-investor.com/gold/krugerrand) 

1. If you pick a value in the OZ column, 
1. then reset by choosing ALLE
1. and then re-pick the same dropdownbox value 
1. and then reset again via ALLE 

you'l see a growing red bar in front.

**Comment by koalyptus** [comment]
Tagging as a bug, I understand now it is a keywords highlighting related issue.

**Comment by koalyptus** [comment]
Hi @ITSecMedia,
It should now be fixed in v0.2.4
Cheers

**Comment by ITSecMedia** [comment]
Verified, it works, thank you very much! :+1:
