### ISSUE TITLE
Performance issues when evaluating innerText

### ISSUE THREAD

**Issue by karlcow** [koalyptus/TableFilter#162]
The bug is fully described with a testcase on Mozilla bugzilla.
https://bugzilla.mozilla.org/show_bug.cgi?id=1260025

An explanation has been given by Mats Palmgren in Comment 3
https://bugzilla.mozilla.org/show_bug.cgi?id=1260025#c3

```
Here's the problematic script:

function tf_GetNodeText(n)
/*====================================================
	- returns text + text of child nodes of a node
=====================================================*/
{
	var s = n.textContent || n.innerText || n.innerHTML.replace(/\<[^<>]+>/g, '');
	s = s.replace(/^\s+/, '').replace(/\s+$/, '')/*.tf_Trim()*/;
	return s.tf_Trim();
}

So when n.textContent returns "" we will evaluate n.innerText which in this case
also returns "" so we will evaluate n.innerHTML too.  This function is called
once for each <td> it seems, about half of which are empty.

Apart from that, n.innerText flushes layout(*) so if there are DOM / style changes
between the calls to tf_GetNodeText this will be very costly.  And this is what
causes the performance problem in this case.

(*) this is documented here:
https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent

So, I think this bug is invalid.  The workaround to the .innerText flush
problem is to set display:none on the subtree while it's being modified.
In this case I'm guessing it's the <table> element. Like so:
tableElement.style.display="none"
// sort the table, i.e. all the tf_GetNodeText calls happens here
tableElement.style.display=""
```

**Comment by koalyptus** [comment]
Hi @karlcow,
Please note your excerpt refers to an old version of the HTML Table Filter Generator (HTFG) plugin, this is the TableFilter which now replaces HTFG.
Please use this plugin instead as HTFG is no longer maintained. Let me know if you experience the same performance issue.

Cheers

**Comment by rimace** [comment]
@koalyptus I am experience the same performance issue. The exact behavior as described in my bug report to mozilla. On large tables the script hangs. 
My problem is that i only found the minified version of TableFilter, so i cannot tell you the exact point where to fix it. I'm not really into javascript development, could you tell me please if there is something like a unminified version for debugging?

**Comment by koalyptus** [comment]
@rimace,
You can find the source files in the `src` folder of your downloaded zip or cloned repository. You can also browse the repository files online on GitHub and this is what you are looking for:
https://github.com/koalyptus/TableFilter/blob/master/src/dom.js#L12
As you can see the exact same code was ported over in this plugin :( and as you point out there is room for improvement... always :) !
I could reproduce the issue and I will have a look into it. I don't think hiding the table element is the way to go though.  As `textContent` is now supported by all browsers, it will be most probably just a question of handling better the empty string case.

If you still want to setup a dev environment locally on your machine, please follow the README instructions:
https://github.com/koalyptus/TableFilter#development

Cheers

**Comment by rimace** [comment]
@koalyptus 
Thanks. 
Yeah, my testcase included ~ 2.000 empty td-Tags. So when getText is called, then node.textContent, node.innerText and the regex is executed, as javascript interprets an empty string as false.
I'll try to setup a test case for the new TableFilter (tomorrow), so that it gets reproducible.

**Comment by koalyptus** [comment]
Thanks @rimace, I am already using your test case pointing to `TableFilter` instead. I will try to spend some time on this today or next days depending on workload.
Cheers

**Comment by koalyptus** [comment]
@rimace,
I just published v0.2.5, give it  a try.
Cheers

**Comment by rimace** [comment]
@koalyptus 
Wow, just tested the new version and it's way faster now. 
Thank you very much for updating it this fast!

**Comment by koalyptus** [comment]
No worries, closing this issue.
Cheers
