### ISSUE TITLE
Linked filters doesn't work properly

### ISSUE THREAD

**Issue by andreyjamer** [koalyptus/TableFilter#163]
I have table formed from Excel file. Table can have many filters, filters can be 'select' or 'range' (external custom filtration).

Configuration for tablefilter is: 

alternate_rows: true,
base_path: "js/tablefilter/",
col_6: "select",
col_number_format: [
    "EU",
    "EU",
    "EU",
    "EU",
    "EU",
    "EU",
    null,
    "EU"
],
display_all_text: "All"
enable_empty_option: false
enable_non_empty_option: false
external_flt_grid: true
external_flt_grid_ids: [
    null,
    null,
    null,
    null,
    null,
    null,
    "col_6",
    null ],
linked_filters: true,
refresh_filters: true,
rows_always_visible: [1, 2],
sort_select: true

I use linked filters to show only possible values in selects. 
But dropdown filters are not updated while table data filtered. If start filtration from any select field (builtin filtration type, i mean) linked filters work properly. But if filtration starts from any range filter, dropdowns are not updated.
Live example: http://andrey.flexites.org/p/filter/example.html
Choose Power min 2,2 max 3,0
Turns output min 20 max 41
After that Gear dimension select should have values 57, 67, 77, 87, but it has all possible values of column.

After that reload example page. Click the Gear dimension select. Choose 'All' value, then select  'Power' and 'Turns output' values from example above. 
After filtration 'Gear dimension' will have values 57, 67, 77, 87 as it should. 

P.S. i hope my english is good enougth to explain the problem :)

**Comment by koalyptus** [comment]
Hi @andreyjamer,
from what I saw in your logic, you are adding additional filters for filtering ranges (good UI idea actually)  but the linked filters only work with the filters that are generated by the script. I don't think there is an issue with the plugin itself, it is not meant to work on additional filters he doesn't know about :)

**Comment by koalyptus** [comment]
Hmmm, nice stuff, have you tried to call the `linkFilters` method (https://github.com/koalyptus/TableFilter/blob/master/src/tablefilter.js#L2033)?
Or alternatively trigger the `build-select-filter` custom event for the `Gear dimension` filter:
```
tf.emitter.emit('build-select-filter', tf, colIndex,  isLinked, isExternal);
```
Where `tf` is an instance of `TableFilter`, `colIndex` is the index for the `Gear dimension` column, `isLinked` is true, but not sure if `isExternal` is false for that column.

**Comment by andreyjamer** [comment]
Problem is not with additional filters. Values in additional filters i rebuild by myself after each filtration. 

Problem is with filters generated by script.

I'll try to explain.
In the example table where are only one script generated filter - 'Gear dimension'. 
Other filters are additional, they are ranges.
I have option `linked_filters: true`, so when i make a filtration on the table (filtration is made using `filter` method of the table class), i suppose that the 'Gear dimension' will be rebuilt to show values in the result column.
But 'Gear dimension' shows all possible values of the column.

If i click on 'Gear dimension' select, `focus` event is emitted and select will be marked as active (even if i didn't select any value). After that filtration on any field will rebuild the 'Gear dimension' select. 

I've found that function `linkFilters` in `tablefilter.js` line 2033 checks `activeFilterId`. This value is defined only if any select had a focus. If not - linked filters won't work at all. 

The problem occurs only if we start filtration from `filter` method, so there is no `activeFilterId` value.

I've resolved the problem with a very dirty hack. After the initialization of the TableFilter, i've found the first script generated select and emit `focus` event on it.

**Comment by andreyjamer** [comment]
Call of `linkFilters` or emitting `build-select-filter` event gave no results. 
I suppose it because of `activeFilterId` check.
The only way is to `focus` on select item. Or change `activeFilterId` check.

**Comment by koalyptus** [comment]
Good work anyway :+1:

**Comment by koalyptus** [comment]
I don't think changing the `activeFilterId` check is a good idea, it is needed, in your scenario that seems to be an obstacle because of your implementation. Assigning the relevant filter id to the `activeFilterId` field might be enough, probably not needed to focus the filter.

**Comment by andreyjamer** [comment]
Yes, may be changing check is not a good idea. The very reason of the problem is that `activeFilterId` is not defined by default.
So, when API filtration is needed, there are a lot of manipulations to do to define `activeFilterId` and make linked filter work as needed.
It's probably better to define `activeFilterId` while the initialization of the table. To set `activeFilterId`as the first filter input in the table. So will be no need to find out this input from external script.

I used focus event because besides defining `activeFilterId` focus handler defines `activeFlt` variable. So i was affraid to break something :)

**Comment by koalyptus** [comment]
Fair enough, I will try to sneak in some enhancements in the next releases. 
I will keep you in the loop.
Cheers

**Comment by koalyptus** [comment]
Hi, I have released a new version with a light refactoring of the active filter logic as per merged PR above. There is now a getter and setter for the `activeFilterId` property and there is no longer a `activeFilter` field to worry about. The `filter-focus` event now sets the `activeFilterId` property. 
This update should already be an improvement.

**Comment by andreyjamer** [comment]
Hi, the linked filters are not working at all. :) Setter and getter work fine, i've checked - `activeFilterId` is set properly. But filtration through method `filter` (or through selecting one of the linked selects) doesn't rebuild linked filters.

**Comment by andreyjamer** [comment]
Adding getter and setter is good, because there is no need to emit focus event on select, but the problem with linked filters is still here. If we start filtration by using API method `filter`, linked filters would not work, because `activeFilterId` is not defined.
So, if there is need to use linked filters and filtration through API, we still need to find out any of internal filters and make one of them active.

**Comment by koalyptus** [comment]
Exactly right, this change does not include setting a default value for the activeFiterId field. Still thinking if it is conceptually right to do so just to satisfy this scenario. Linking filters implies to have an active filter and the API let you easily grab a filter ID too. So in the end, we are talking about saving an API call only. Perhaps exposing a more explicit API called 'activateFilter' accepting a column index would be clearer and more convenient for the developer.

**Comment by andreyjamer** [comment]
Yes, may be you are right. API call to activate filter would be useful thing.

**Comment by koalyptus** [comment]
Version 0.2.9 now exposes the 'activateFilter' method.
Cheers
