### ISSUE TITLE
Select all with filter

### ISSUE THREAD

**Issue by shughes111** [koalyptus/TableFilter#178]
Hi Again!

TableFilter working very well and I have just introduced a "select all" checkbox to check all checkboxes on each row of the table (see code below). However when this happens, the selection made is for those items in the filter selection, plus those not - i.e. all items irrespective of filter applied. If I have a data set of 100 records filtered to 5, the select all results are still all 100 records.

Any ideas much appreciated!

Code for "select all":

	$(document).ready(function(){
		$('#select_all').on('click',function(){
			if(this.checked){
				$('.checkbox').each(function(){
					this.checked = true;
				});
			}else{
				 $('.checkbox').each(function(){
					this.checked = false;
				});
			}
		});
		
		$('.checkbox').on('click',function(){
			if($('.checkbox:checked').length == $('.checkbox').length){
				$('#select_all').prop('checked',true);
			}else{
				$('#select_all').prop('checked',false);
			}
		});
	});

**Comment by koalyptus** [comment]
Hi @shughes111,
If you are not using the [ezEditTable](http://codecanyon.net/item/ezedittable-enhance-html-tables/2425123?ref=koalyptus plugin, what you could do is use the `getValidRows()` API to retrieve the indexes of the filtered rows. Then refine your checkbox selection logic to verify the checkbox is contained in a row whose index appears in the collection returned by the above API, only in that case you should tick the checkbox.

**Comment by shughes111** [comment]
Thanks for the reply - so I would return the getValidRows() API into an array and use it in the TRUE case functions above (sorry, JQUERY not my strong point!)

**Comment by koalyptus** [comment]
Yes, the getValidRows() API returns an array and then you will need to implement your own jquery logic, as explained above, to check a checkbox.

**Comment by shughes111** [comment]
Ok many thanks for your help!
