### ISSUE TITLE
Improvement : selecting empty or non empty values across checklist filter

### ISSUE THREAD

**Issue by Insorior** [koalyptus/TableFilter#180]
Hi there !

Everything is in the title, a good enhancement for the library would be to be able to select empty or non empty values across checklist filters, a bit like in Excel. I had a look into checklist filters options in the wiki but it seems not to be possible at the moment.

**Comment by koalyptus** [comment]
Hello @Insirior,
It is already the case, have a look to this demo:
http://koalyptus.github.io/TableFilter/grouped-headers.html

**Comment by Insorior** [comment]
I did not see about it, I suggest that you link it into checklist filters wiwi. Thanks for support again ! :+1:

**Comment by koalyptus** [comment]
@Insorior thanks for pointing this out, just updated the checklist fllter wiki page:
https://github.com/koalyptus/TableFilter/wiki/1.06-Checklist-filter

Cheers
