### ISSUE TITLE
getValidRows API in JS function

### ISSUE THREAD

**Issue by shughes111** [koalyptus/TableFilter#182]
I have a check all function for checkboxes against each row but only want to check displayed rows. I am struggling to code the getValidRows API in the following function to make this happen (lines I have added are highlighted):

$(document).ready(function(){
    $('#select_all').on('click',function(){
        if(this.checked){
            $('.checkbox').each(function(){
              **_ if(jQuery.inArray(this.checkbox, getValidRows()) != -1) {
_**                    this.checked = true;
              **_ }_**
            });
        }else{
             $('.checkbox').each(function(){
                this.checked = false;
            });
        }
    });

    $('.checkbox').on('click',function(){
        if($('.checkbox:checked').length == $('.checkbox').length){
            $('#select_all').prop('checked',true);
        }else{
            $('#select_all').prop('checked',false);
        }
    });
});

**Comment by emzipoo4u** [comment]
I have the same problem.

**Comment by emzipoo4u** [comment]
@shughes111 can you let me know If you have any luck with this, it is proving a real headache.

**Comment by koalyptus** [comment]
@shughes111 @emzipoo4u,
I will give you a shout whenever the demo is online, although still not a priority for the moment.
Cheers

**Comment by shughes111** [comment]
ok thank you...

**Comment by koalyptus** [comment]
@shughes111  I just published the [Custom checkbox selection](http://koalyptus.github.io/TableFilter/custom-checkbox-selection.html) demo that I hope will help you.
Cheers

**Comment by shughes111** [comment]
Thank you for this!

**Comment by shughes111** [comment]
Just want to say thanks again - this worked brilliantly!!
