### ISSUE TITLE
Checkboxes in table

### ISSUE THREAD

**Issue by emzipoo4u** [koalyptus/TableFilter#184]
I have TableFilter applied to a table I pull back from a database. On each row there is a checkbox.

`
<input name="emailsend<%=orderlineno%>" type="checkbox" id="emailsend<%=orderlineno%>" value="TRUE"/> `

On the header row I have another checkbox that enables the users to "select all checkboxes"

```
<input name="ticktoggle1" type="checkbox" id="ticktoggle1" onclick="selectall1();" />

<script type="text/javascript">
<!--
function selectall1() {
 
  for (var i = 0; i < document.forms['form1'].elements.length; i++) {
    var e = document.forms['form1'].elements[i];
 
    if ((e.name.charAt(0) == 'e') && (e.type == 'checkbox')) {
      e.checked = !e.checked;
    }
  }
}
-->
</script>
```
The problem is, if my table is filtered, it selects ALL the tickboxes regardless of the filter. Is there anyway for it to take the tablefilter into consideration.

**Comment by koalyptus** [comment]
Hi @emzipoo4u,
Please refer to this answer: https://github.com/koalyptus/TableFilter/issues/178#issuecomment-209471647

Cheers

**Comment by emzipoo4u** [comment]
Thank you, but no idea how to implement this.

**Comment by emzipoo4u** [comment]
OK, so I see we can get an array with a comma between values, again, no idea how to use this. I am not a JavaScript programmer.

**Comment by koalyptus** [comment]
@emzipoo4u,
I will try a certain point in the future to provide a demo showing how to implement that.
Please note, I don't provide general javascript support, issues raised here have to be closely related to the plugin (ie enhancement, bug fix, regression).
Cheers

**Comment by emzipoo4u** [comment]
@koalyptus  - yes please I think it would be much appreciated as that other person seems to be struggling too.

**Comment by emzipoo4u** [comment]
@koalyptus - How long would It take and how much would you charge for helping me integrate it ?

**Comment by koalyptus** [comment]
Sorry @emzipoo4u I don't have capacity for that at the moment, already too stretched :P

**Comment by koalyptus** [comment]
@emzipoo4u I just published the [Custom checkbox selection](http://koalyptus.github.io/TableFilter/custom-checkbox-selection.html) demo that I hope will help you.
Cheers
