### ISSUE TITLE
"Remember filter values" may have an issue with filter values with "," in them

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#187]
I have a table created by some other software that I've added table filter to.  It creates table cell entries of "call categories" separated with commas ",".  When I visit this page I like to have the same filter applied each time.  It seems to remember all the categories that don't have commas but I have to reselect the ones with commas each time.  Filtering works fine, just not remembering the values.
I'm on v0.1.11.

**Comment by koalyptus** [comment]
Hi @cjohnsonuk, thanks for pointing this out, however the `remember_grid_values`, `remember_page_number` and `remember_page_length` options will soon be deprecated (in 2 releases) and replaced by the [state](https://github.com/koalyptus/TableFilter/wiki/1.17-State) option.
I advise you to install the latest version (0.2.12) and use the `state` configuration option instead. Refer to the following demos to see it in action:
- [persistence](http://koalyptus.github.io/TableFilter/persistence.html)
- [deep linking](http://koalyptus.github.io/TableFilter/deep-linking.html)
- [paging](http://koalyptus.github.io/TableFilter/paging.html)
- [grouped headers](http://koalyptus.github.io/TableFilter/grouped-headers.html)

**Comment by cjohnsonuk** [comment]
Updated today to 0.2.13, updated filter options to use state rather than remember_.+ and all appears to work with the testing so far. 

Thank you! :-)
