### ISSUE TITLE
tf not defined

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#193]
I've added TF to OSTicket and I'm getting this error from Firefox firebug:  
`ReferenceError: tf is not defined
  ...his.buildManager(),this.initialized=!0,this.emitter.emit("columns-visibility-ini...
tf-1.js (line 7, col 17089)`

As the page loads it shows a translucent overlay div until its loaded which I'm assuming never gets removed as the javascript fails before this time. Clicking page reload in Firefox makes it work correctly but going to the page from another via a link doesn't.
I've removed all the tf config in sections and narrowed it down to the colsVisibility extension (the clue was also in the error  ;-)

If the page is reloaded it appears to work fine, its just when you load it via a link from another page.
Cols visibility works fine on pages I've written myself its just in the context of OS Ticket that it falls over...

Not sure if this is an easy one. We've turned cols visibility off for now.

I've tested with 0.2.13 and 0.2.14 although it did happen with the previous version I had installed as well.

Chris

**Comment by koalyptus** [comment]
I think it is a bug, I just reviewed the columns visibility extension code I modified recently and I can see the `tf` var is never assigned:
https://github.com/koalyptus/TableFilter/blob/master/src/extensions/colsVisibility/colsVisibility.js#L18
Tagging this as a bug, I will try to fix it later in the day and give you a sign when done.
Cheers

**Comment by koalyptus** [comment]
I just pushed v0.2.15 with the bug fix, give it a try and tell me how it goes.

**Comment by cjohnsonuk** [comment]
only used it for 10 minutes so far but this appears to have fixed it. (0.2.18)  Thank you ! :0)

**Comment by koalyptus** [comment]
Ok cool, closing this issue then.
