### ISSUE TITLE
No sort on header with popup filter checklists

### ISSUE THREAD

**Issue by KGFTW** [koalyptus/TableFilter#200]
I am facing an issue using TableFilter, it seems that it is not possible to use the sorting feature (with the arrows) while using checklists as popup filters.
That would be marvellous since it is exactly what I'm trying to set up.
Here's the code i'm using to implement it : 
>var filtersConfig = {
        base_path: '/path/to/tableFilter/',
        col_0: 'checklist',
        col_1: 'checklist',
        col_2: 'checklist',
        col_3: 'checklist',
        col_4: 'checklist',
        col_widths: [
            '105px', '105px', '105px', '105px', '105px'
        ],
        popup_filters: true,
        mark_active_columns: true,
        filters_cell_tag: 'td',
        extensions: [{ 
            name: 'sort',
            types: [
                'String', 'String', 'Number', 'String', 'String'
            ],
            on_sort_loaded:function(o, st){ 
                console.log('Sort loaded'); 
            }
        }],
        sort: true
    };
    var tf = new TableFilter('myTable', filtersConfig);
    tf.init();

The console.log actually displays what it is intended to on load of the page and of the sort module (at least I guess so), but the arrows are not displayed, nor is it possible to interact with the headers (the cursor isn't a pointer, and clicking on it doesn't change the order of the elements of my table).
The checklists as popup filters work fine which is why I quite don't understand what's wrong in my code.
I tried to type tf.extension('sort'); in the chrome console and it answered the following : 
`e {initialized: true, name: "sort", desc: "Sortable table", sorted: false, sortTypes: Array[5]…}`

The sorting extension seems to have been initialized but isn't working properly.
Can you help me figure it out ?

**Comment by koalyptus** [comment]
Hi @KGFTW,
Try to disable the popup filters, it might be the issue.
BTW you don't need to define `sort: true` setting, the sort extension is enough.

**Comment by KGFTW** [comment]
Hi @koalyptus and thank you for your answer.
I tried your solution but it doesn't settles the problem though :(
Plus I will need the popup filters feature since it's so great ! (Would be amazed to get both)
Any other Idea ?

**Comment by koalyptus** [comment]
All right, make sure you have a thead explicitly defined in your table markup.

**Comment by KGFTW** [comment]
That was it ! It works now with the `thead`.
Thanks for your work and your support, it's awesome :)
