### ISSUE TITLE
Problem filtering numbers with separators

### ISSUE THREAD

**Issue by dsl101** [koalyptus/TableFilter#202]
I've got a table which is generated by other code ([editablegrid](https://github.com/webismymind/editablegrid)) and it converts my original table with plain numbers into text with separators. So the table cell looks like this:

    <td class="editable number editablegrid-to" data-title="To port">65,535</td>

But, if I type '65535' into the column filter, it excludes that row. Clearly it isn't an exact match - but is there a way to specify that column X is of type 'int' and therefore should be stripped of punctuation before matching? I tried setting the various options such as `thousands_separator` and `col_number_format`, but couldn't figure out any combination which would help in this scenario...

**Comment by koalyptus** [comment]
Hi @dsl101,
Tagging this as an enhancement, I will give you a sign when the plugin will support the scenario described above.

**Comment by koalyptus** [comment]
:+1:

**Comment by koalyptus** [comment]
Starting from v0.2.19, you should be able to filter by `65535` in the column with formatted numbers as described in your scenario above. The default `thousands_separator` is `,` anyway, so just define the `col_number_format` option. Tell me how it goes.

**Comment by dsl101** [comment]
Many thanks for looking at this. I just ran npm update and saw this in the console:

`tablefilter@0.2.23 node_modules\tablefilter`

so I'm presuming that's got me the new functionality. This is the config I'm using:

`var filterConfig = {col_number_format: [null, null, null, null, null, 'us', 'us']};`

Columns 5 and 6 have port numbers in the thousands, but I still don't see them when filtering without including the commas in the filter box. Some possibilities:

- Is it case sensitive? In the WIKI, it's listed as 'US' in the help, and 'us' in the example (although I tried both and couldn't get it to work either way)
- Is this actually using locale at all? I'm in the UK (which is current still in Europe :), but we use dot for decimal and comma for thousands...

Or did I miss something else I need in the config?

**Comment by koalyptus** [comment]
Yeah I know, unfortunate and misleading naming 'eu' or 'EU' :P 
Anyway, I confirm it is case insensitive and not using locale. Have a look to this demo:
http://koalyptus.github.io/TableFilter/data-types.html
You can filter the € and US $ columns with unformatted numbers (ie `1176`)

This should be possible in your table too, assuming you are importing the latest version in your page and the `us` values in `col_number_format` are in the expected position.

**Comment by dsl101** [comment]
Hmm. Not sure what's going on there then. I can see this works in your demo, but for me, I have to enter the comma still. The only thing I noticed in your demo was that the td element contained a div (to right-align the numbers). Does that make a difference? Mine is just plain text.

I guess it could be some combination of tablefliter and editablegrid - I'll try to remove the edit features and see if it changes.

**Comment by koalyptus** [comment]
@dsl101,
This comment https://github.com/koalyptus/TableFilter/issues/209#issuecomment-218431421 is also valid for this issue, correct?

**Comment by dsl101** [comment]
No - still seeing the issue. I had thought it was because I was using editablegrid (npm package), but I've changed everything to use HTML5 editablecontent now, and am only adding in your package. But I still see the problem that if I type '1,234' into a cell, and '1234' in the filter, the cell with the comma is excluded from the list. I'll update that other issue with the underlying cause, in case it's of help - it was to do with a mismatch between the `<th>` and `<td>` elements.

Here is the config I'm using:
`{display_all_text: "*",
auto_filter: true,
auto_filter_delay: 100,
linked_filters: true,
col_0: "select",
col_1: "select",
col_2: "select",
col_3: "select",
col_4: "select",
col_11: "none",
col_number_format: [
	"null",
	"null",
	"null",
	"null",
	"null",
	"us",
	"us",
	"null",
	"null",
	"null",
	"null",
	"null"
]}`

There are 12 columns in total, with 5 & 6 being numbers. Since dropping editablegrid, the simplest fix for me is just not have have separators - but it would be great to figure out why it's not working...

**Comment by koalyptus** [comment]
Try to turn off the `linked_filters` configuration option, and see if it works.

**Comment by dsl101** [comment]
I'm afraid it didn't - note that this code is running on node/electron locally, so I can't give you a link to it I'm afraid. I wonder if there's something about that environment which could cause a problem? node v4.4.2 and electron-prebuilt v0.37.8

**Comment by koalyptus** [comment]
BTW, `"null"` should be `null` and the `base_path` setting should be also defined, especially if you import the package from the `node_modules` directory.
Tried different things could not reproduce the issue. Double check again the version is correct and your HTML table is valid (same number of columns in body and header).

What you could also do is copy the `http://koalyptus.github.io/TableFilter/data-types.html` example into your electron project, package it with electron-prebuilt and see if you have the same issue. 
Can't think of anything else for the moment.

**Comment by dsl101** [comment]
I had copied the files out into a folder within the main app, but I guess things had got mismatched. I removed my copes and included directly from within `node_modules`, set the `base_path` and all working correctly now - I guess that's best practice anyway, since updates will be available immediately too.

Tx.
