### ISSUE TITLE
Normalisation of config parameters

### ISSUE THREAD

**Issue by dsl101** [koalyptus/TableFilter#211]
Just curious - column format is specified with `col_0: "select"`, etc. but number format with `col_number_format: ['us', null, null]`, etc. Is there some reason why that isn't `col_0_format: 'us'`? Then you'd only have to include columns for which you want something other than default...

**Comment by koalyptus** [comment]
It is in the roadmap to merge the `col_number_format` and `col_date_type` into one configuration option most likely called `col_types`, 2nd item in #197 .

**Comment by dsl101** [comment]
Ah - sorry, hadn't spotted that. Tx - great package by the way :)

**Comment by koalyptus** [comment]
Thx @dsl101, j
ust answered to https://github.com/koalyptus/TableFilter/issues/202#issuecomment-218707990
