### ISSUE TITLE
Filtering is unpredictable when columns contain numbers and characters

### ISSUE THREAD

**Issue by miket6000** [koalyptus/TableFilter#217]
When attempting to filter by typing in text only everything works perfectly when the column only contains alphabetical characters. If however the column contains cells with both numbers and characters, alphabetical filters can include numeric results that don't match the filter or can exclude results that do match the filter. I've not worked out exactly when each outcome occurs.

Example:

```
<HEAD>
<TITLE>Page Title</TITLE>
<script language="javascript" type="text/javascript" src="./tablefilter/tablefilter.js"></script>
</HEAD>
<BODY>

<table id='mytable'>
<tr><th>col 1</th><th>col 2</th></tr>
<tr><td>alpha a</td><td>alpha b</td></tr>
<tr><td>alpha c</td><td>alpha d</td></tr>
<tr><td>alpha e</td><td>numeric 1</td></tr>
<tr><td>alpha f</td><td>numeric 2</td></tr>
</table>

<script data-config>
    var tf = new TableFilter('mytable', {
        base_path: './tablefilter/',
        alternate_rows: true
    });
    tf.init();
</script>
</head>
</html>
```
<table id='mytable'>
<tr><th>col 1</th><th>col 2</th></tr>
<tr><td>alpha a</td><td>alpha b</td></tr>
<tr><td>alpha c</td><td>alpha d</td></tr>
<tr><td>alpha e</td><td>numeric 1</td></tr>
<tr><td>alpha f</td><td>numeric 2</td></tr>
</table>
Filtering column 1 works as expected, I can type 'alpha' and get all results or 'f' and only get the last row. Filtering by column 2 however if I type numeric I get no results. I can work around this by using the 'like' operator (*) but this behaviour is inconsistent and difficult to explain to non-technical users.

Cheers, Mike.

**Comment by koalyptus** [comment]
Thanks for pointing this out I will have a look. Btw which version are you using?

**Comment by koalyptus** [comment]
Starting from v0.2.28, the filtering inconsistency for columns with alphanumeric values should be fixed.
Give it a try.
Cheers

**Comment by miket6000** [comment]
Hi, I'm using 0.2.23. I will try 0.2.28 and let you know how it goes. Thanks for the very quick reply.

**Comment by koalyptus** [comment]
Cool, closing this issue then!
