### ISSUE TITLE
Inconsistent sorting

### ISSUE THREAD

**Issue by rs2** [koalyptus/TableFilter#218]
Sorting of numerical columns with `NaN`s can be inconsistent. There are several examples.

* Go to http://koalyptus.github.io/TableFilter/conditional-cell-formatting.html and keep clicking on **cgdp**. `na` start appear in unexpected locations on every 4th click.
* Conditional formatting can disrupt the sorting sequence. Perhaps worth adding at least a warning regarding modifying innerHTML, e.g. using `.localeToString('en-US')`.

**Comment by koalyptus** [comment]
Thanks for pointing this out. The first issue is a known issue, may not be captured in a ticket yet but considered as low priority.
In second item, you are referring to a demo, with some external code disrupting column sorting. Can you expand a little bit more on that?
Cheers

**Comment by rs2** [comment]
In my experience the users expect behavior nearly identical to Excel, i.e. various numerical formats are treated as numbers and sort/filter functions are expected to be bulletproof. Unfortunately, if the latter is not the case the product cannot be accepted. I would lobby to upgrade the priority of the first issue on this basis.

**Comment by koalyptus** [comment]
Thanks for sharing your experience @rs2, there is always room for improvement!

**Comment by koalyptus** [comment]
As of v0.3.0, sorting of numerical columns containing `NaN` is more consistent, na values no longer appear in the middle of the results set.

**Comment by rs2** [comment]
:+1:

**Comment by Aman-Chopra** [comment]
I am importing contents from mongoDB and rendering it into the table, everything seems to work except the sorting, so whenever I am locally creating table, sorting works but in case of dynamic rendering of table, none of the columns is sorting.

**Comment by koalyptus** [comment]
Make sure your dynamically generated table has a THEAD and TBODY.

**Comment by Aman-Chopra** [comment]
It has thead and tbody, all the other functions are working fine, the sorting arrows are also coming but nothing happens when I click them. So while trying to fix it, I added two static data rows before my dynamic data rows and the sort operation works on static data and just the first row of dynamic data, I have also tried asynchronous: true but still no luck:(
