### ISSUE TITLE
setFilterValue disrupts the scope of parseRows/formatCell

### ISSUE THREAD

**Issue by rs2** [koalyptus/TableFilter#219]
1. Add `o.setFilterValue` and `o.filter()` to http://koalyptus.github.io/TableFilter/conditional-cell-formatting.html
2. Load the page. Remove the filter. Sort/unsort a column. Some cells that should have been highlighted are not.

**Comment by koalyptus** [comment]
Where I would add `o.setFilterValue` and `o.filter()`?
There is no `o` object referencing a `TableFilter` instance in that example.
