### ISSUE TITLE
Error: Cannot read property 'style' of undefined when table is edited

### ISSUE THREAD

**Issue by dsl101** [koalyptus/TableFilter#220]
I've got linked filters, one of which is a select dropdown, another is a plain text box. If I filter by the select box, then type a few characters into the text box, I can narrow down the results. But the table row includes a 'delete row' feature which removes the row from the table. This leaves the filter result as empty, since there are now no matching rows. But my guess is that TableFilter doesn't really like having rows removed from underneath it. I tried calling the `filter()` method immediately after updating the table, but that didn't seem to help, and I couldn't see an obvious `refresh()` method in the docs. The precise error is:

> `	Uncaught TypeError: Cannot read property 'style' of undefined`
> `		e.TableFilter.t.filter @ tablefilter.js:7`
> `		e.Dropdown.e.onSlcChange @ tablefilter.js:8`
> `		(anonymous function) @ tablefilter.js:8`

Is there a way to make TableFilter happier about this situation?

**Comment by koalyptus** [comment]
Thanks for pointing this out, I will have a look to it. Could be just a question of having more defensive code.

**Comment by koalyptus** [comment]
Hi again @dsl101,
starting from v0.2.29, `TableFilter` should better support underlying changes in the number of row DOM elements. As you say there is no obvious `refresh` method at the moment but you shouldn't need it.
Give it a try and tell me how it goes.
Cheers

**Comment by dsl101** [comment]
Hi - I ran `npm update`, but it is only offering 0.2.28. I'm fairly new to npm - do I need to do something special to allow the latest version? I also tried `npm install tablefilter@0.2.29`, but that gave a 'version not found' error...

**Comment by koalyptus** [comment]
Sorry mate I haven't published it on npm yet and I can't until tomorrow morning (Sydney timezone), I left my laptop at the office, just using my phone. However it is available on GitHub if you want.
Cheers

**Comment by dsl101** [comment]
Tx - no rush! I'm on UK time so I guess it will be there by tomorrow for me :).

**Comment by koalyptus** [comment]
How did this go?

**Comment by dsl101** [comment]
My basic testing that I used before to cause the error has certainly gone
away. I haven't had chance to do any unit tests - e.g. making sure the
remaining rows are all still indexed correctly, etc. I'm afraid. Let's call
it fixed :)

Many thanks

**Comment by koalyptus** [comment]
Ok, you can always raise another ticket :)
Cheers
