### ISSUE TITLE
Feature request: enable support for sorting currency-formatted numbers

### ISSUE THREAD

**Issue by rs2** [koalyptus/TableFilter#221]
E.g. correctly order

```
(7.2%)
-0.2
1,225.22%
3,253,567.27
```

**Comment by koalyptus** [comment]
@rs2 have a look to this demo to define the column types:
http://koalyptus.github.io/TableFilter/data-types.html

and this demo to eventually support the accounting convention for negative figures (7.2%):
http://koalyptus.github.io/TableFilter/sort-custom-type.html

**Comment by koalyptus** [comment]
As of v.0.3.0, TableFilter now understands the accounting convention for negative figures `(number)` if `number` or `formatted-number` type is set for relevant column.

**Comment by rs2** [comment]
:+1:
