### ISSUE TITLE
Enhancement: Something between responsive and grid_layout...

### ISSUE THREAD

**Issue by dsl101** [koalyptus/TableFilter#224]
I really like the `responsive: true` behaviour, but would also like the header rows to stay at the top of the window when scrolling, like with `grid_layout: true'. To be honest, I'm not a fan of `grid_layout` and prefer the table to follow the browser size. But keeping the headers is nice.

I tried installing [sticky-table-headers](https://github.com/jmosbech/StickyTableHeaders) but it doesn't really play nicely - it creates a second `<thead>` section and swaps their visibility depending on scroll position. The column widths of the 2 headers don't line up and tend to jump around, and the second header row also appears in the filter select dropdowns. I'm pretty sure with TableFilter doing so much 'management' of the table, adding extra plugins isn't the way forward anyway - things are so much better since I uninstalled editable-grid and implemented it myself :)

Would it be possible to add a `freeze_header: true` option to the config, and keep that part of the table visible somehow?

**Comment by koalyptus** [comment]
Out of curiosity have you seen the responsive grid layout example:
http://koalyptus.github.io/TableFilter/responsive-grid-layout.html ?

**Comment by dsl101** [comment]
I have - and whilst I like the header behaviour, I _don't_ really like the fixed width with scroll bars. Also needing to fix the height of the grid layout means if the browser height changes, you end up with _two_ vertical scrollbars.

I much prefer the responsive layout where the columns change size to fit and the browser deals with vertical scrolling. I know I could probably fix it up with grid layout using some javascript on window size change, but it seems to be solving the wrong problem when really all I want is a header row that says put - everything else about responsive is just as I want it...

**Comment by koalyptus** [comment]
I don't think you would need any javascript to fix grid layout's vertical scrolling, should be solvable with CSS only. Fear enough, I will tag this as an enhancement although not yet a priority, a lot of refactoring work in the pipeline before adding any new feature unless it is a quick win.

**Comment by dsl101** [comment]
I'm going to see if I can make [this](https://jsfiddle.net/dPixie/byB9d/3/) work using CSS. Will keep you posted.

**Comment by dsl101** [comment]
OK - it's close, but not quite there. What worked:

- Fixed header row but still responsive to window width changing
- All done in CSS

What didn't work:

- End up with 2 'header' rows after calling `filter.init()` - I'm guessing the init routine updates the header row height which is set to 0 in that fiddle's css
- Filters end up 'between' the div-based header and the actual header
- Filters end up scrolling off the screen, even though the header row sticks
- Need to set absolute height for the container - 100% goes back to the default behaviour, and this would need updating on window size change

Hopefully there's enough to go on there though to persuade both the filters _and_ the header to stay put

**Comment by koalyptus** [comment]
Nicely done, perhaps a bit of duplication going on with the repeated header text in a div to satisfy a CSS trick :) 
I wonder how well this would integrate with other DOM elements generated by the sorting or pop-up filters features.

**Comment by dsl101** [comment]
I think it's a bit of a lost cause what I'm _actually_ after - see [here](http://joshondesign.com/2015/05/23/csstable). I've tried various alternatives, but the all suffer from some major flaw, such as:

- Extra inactive scroll bars (this seems to be a chromium/windows speciality)
- Auto column sizing breaking the link between header and body
- Needing to have the table body given an absolute height, breaking responsiveness to the browser window height without javascript hacks

As the author of that blog states, this would seem to be a pretty common use case and HTML5 / CSS3 just doesn't seem to support it very well. I guess I'll go back to the simple case of having the header vanish on scrolling - too many other edge cases to deal with otherwise... :(

**Comment by koalyptus** [comment]
Those are definitely sliding grounds, the previous library used to have an option for fixed headers long time ago, but not in a responsive way. Ten years later this feature still seems to be luxury as not natively supported by the browsers, perhaps not even included in the HTML5 spec. 
Closing this one.
