### ISSUE TITLE
Feature : Disabled sorts on certains row

### ISSUE THREAD

**Issue by Mayeut73** [koalyptus/TableFilter#228]

**Comment by Mayeut73** [comment]
Hi, I search on the documentation but I don't think it realy exists ... I would like to set row_always_visible and these rows wont be affect by the sorting ? It already exists ?

**Comment by koalyptus** [comment]
Hi @Mayeut73,
I am afraid it does not exist. What would you do with the unsorted rows? Keep them at the same row index position, in the middle of sorted rows? Needs some thought I think.
Anyway, at the moment the library is going through a refactoring/stabilizing process and there won't be any new features until that is done.
Cheers

**Comment by Mayeut73** [comment]
Hi, I am doing some collaspe row in the table Html on two or three level ... It looks like this 
![htmltable](https://cloud.githubusercontent.com/assets/10164966/15494441/bc5b4870-218a-11e6-87db-1535228f595a.PNG)

And I want we I sort the column, to sort just the expanded row, if the other are collapse the sort wont affect this row ... Do you think it's possible if I try myself ? And by the way I used the HTML Table Filter Generator v2.5

**Comment by koalyptus** [comment]
I don't think it can be easily done, the sort functionality sorts all the rows inside the tbody, from memory there are no hooks before or after a row is sorted.
By the way, I advise you to upgrade to TabkeFilter instead, HTFG is no longer mantained and this is not the appropriate forum anyway.
Cheers
