### ISSUE TITLE
on_filter_loaded / o.filter() does not apply filter

### ISSUE THREAD

**Issue by seisen** [koalyptus/TableFilter#241]
On the example:
http://koalyptus.github.io/TableFilter/data-types.html
on_filters_loaded: function(o){
            o.setFilterValue(3, '>1.000');
            o.setFilterValue(4, '<2,500');
            o.setFilterValue(6, '>23-01-95');
            o.filter();
        },

The filters are correctly set up but o.filter() does not apply the filtering.
Is it a bug ?

tested on:
firefox: 46.0.1
Chrome: 51.0.2704.84 m
IE 11

**Comment by koalyptus** [comment]
@seisen thanks for pointing this out, it is indeed an unfortunate regression as a result of latest refactoring, I will give you sign when fixed.

**Comment by koalyptus** [comment]
@seisen the issue should now be fixed in v0.2.38,
Cheers
