### ISSUE TITLE
Toggle function works for pagination but not for grid

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#243]
Not sure if this is me or table filter.  I saw the toggle feature example and can get it working for pagination but when I tried to toggle the grid on and off nothing seemed to happen (grid was on all the time).  Is this something that should work?

**Comment by koalyptus** [comment]
What do you mean by 'grid'? The whole TableFilter instance? Or the grid-layout mode?

**Comment by cjohnsonuk** [comment]
grid layout mode, Sorry for not being clear.  Many of our tables have lots of optional columns that cause the width to be wide enough that grid layout is better, but many, in their simple form look better and are easier to use without the grid layout option.

**Comment by koalyptus** [comment]
No worries, what I suggest to do to toggle a grid-layout to a regular table with filters and vice-versa is:
- destroy the TableFilter instance
- create a new instance with a different configuration (grid layout turned off)
- initialize new instance

Tell me how it goes

**Comment by koalyptus** [comment]
Code example of function toggling grid-layout mode:
```
var configGridLayout = {
    base_path: 'tablefilter/',
    grid_layout: true
};

var configRegular = {
    base_path: 'tablefilter/'
};

var tf = new TableFilter('tableId', configGridLayout);
tf.init();

function toggleGridLayout(evt){
    var chx = evt.target;
    tf.destroy();
    
    if(chx.checked){
        tf = new TableFilter('tableId', configRegular);
    } else {
        tf = new TableFilter('tableId', configGridLayout);
    }

    tf.init();
}
```
As per demo you mentioned above, assuming here there is a checkbox in the UI toggling the grid-layout mode.

**Comment by cjohnsonuk** [comment]
You are a complete star! Thank you! I'll give it a try tomorrow Chris

**Comment by koalyptus** [comment]
Trying to keep issues tidy, did you get a chance to try this?

**Comment by cjohnsonuk** [comment]
Its working from the console.  Just need to integrate it into the code.  :-)
