### ISSUE TITLE
img.sort-arrow makes column headings "jump up" when reducing the width of the browser window, even when unsorted 

### ISSUE THREAD

**Issue by rs2** [koalyptus/TableFilter#245]
`tablefilter v0.2.39`

**Comment by koalyptus** [comment]
Try the responsive behaviour by setting the responsive option to true.

**Comment by rs2** [comment]
Unfortunately the placeholder for `img.sort-arrow` is still there, and the text still "jumps up". The workaround could be to set `display` to `none` for `.sort-arrow` and `inline` for `.ascending` and `.descending`.

**Comment by koalyptus** [comment]
Ok, tx @rs2 for the workaround, you can raise a PR if you want to, otherwise the fix will be included in next release(s).
Cheers

**Comment by koalyptus** [comment]
Try `v0.2.40`, the column headers should no longer jump vertically when sort is on.
Also be aware you can also implement your own custom sort indicator by using the following options:
- `image_class_name`
- `image_asc_class_name`
- `image_desc_class_name`
as described in https://github.com/koalyptus/TableFilter/wiki/3.1-Sort
