### ISSUE TITLE
Allow both popup filters and external filters

### ISSUE THREAD

**Issue by KGFTW** [koalyptus/TableFilter#253]
Hi Koalyptus,
I have recently been trying to generate external filters since it would be useful to me.

The problem I encountered is that it seems not to be possible to handle both popup filters and external filters.
I need both of them (let's get awesomeness to the next level !), to allow the table to be filtered from its headers popup filters, and by external filters linked to hidden columns.
Filtering on columns hidden after external filter generation actually works, which is awesome for external filters to be applied, especially if there are only 3-4 values for hundreds of lines, that saves a column width on the screen.
I could use static picklists to handle it but since my table data is retrieved dynamically before initializing the tablefilter, and the available values for both those columns could evolve, that would be great to handle it that way.

I suspect this to be an enhancement if there is no viable workaround :)

Thanks for your hard work !

**Comment by koalyptus** [comment]
Thanks @KGFTW,
What you could do is use the `getFilteredDataCol(colIndex)` API to retrieve the data of a column and then remove all the doubles and populate you external filter with that data.
Let me know how it goes.

**Comment by koalyptus** [comment]
@KGFTW,
I just added the following demo:
http://koalyptus.github.io/TableFilter/dynamic-external-filters.html
which should help you achieve what you described above. The demo combines popup filters with  dynamically generated external filters.

**Comment by KGFTW** [comment]
@koalyptus Just a little comment to let you know I managed to achieve what I wanted, since I didn't work on this for a while. :)

**Comment by koalyptus** [comment]
Cool, was the above demo useful?

**Comment by KGFTW** [comment]
Kinda, but I pretty much used the getFilteredDataCol(colIndex) API, then re-created the popup checklist filter html and handled on click events on custom html buttons to generate the external filters.
I couldn't manage to generate the external filter values as  you did in the demo though :(

Still, I now have efficient dynamic external filters based on hidden columns of the tablefilter, which is awesome to avoid useless columns space.

I use it for a geographical filtering purpose, it is not needed to display a whole column for my usecase, and for few values.

Thanks anyway :+1:
