### ISSUE TITLE
Default value of dropdown filter

### ISSUE THREAD

**Issue by snacke** [koalyptus/TableFilter#257]
Hello!

Is it possible to set another default value than "show all" for a drop-down filter? I want the table to be filtered already when the page is loaded, but with the possibility to show hidden rows if desired.

**Comment by koalyptus** [comment]
Hello,
Use the *display_all_text* option for that.

**Comment by snacke** [comment]
Thank you for the answer, but I think that my question probably was a bit unclear. Suppose that my table looks like this:

A
B
C

When the page is loaded, I want rows with 'A' or 'B' to be visible and rows with 'C' to be hidden. If the visitor chooses "show all", the rows with 'C' should also appear.

In other words, what I'm looking for is a way to filter the table automatically at page load, without any action from the visitor. Is that possible using TableFilter? :)

**Comment by koalyptus** [comment]
Sure, you can interact programmatically with the TableFilter instance by using the API.
Assuming `tf` is an instance of `TableFilter`, you can use the `setFilterValue` method to set the value of a filter for a specified column, in this case a `input` type:
```
tf.setFilterValue(0, 'A||B');
```
and then simply filter the table:
```
tf.filter();
```
Cheers

**Comment by snacke** [comment]
Brilliant!! Many thanks for that great advice! :D

**Comment by snacke** [comment]
I'm reopening this issue, since I found a little problem when using linked filters. Suppose that this is my table: 

A   X
B   Y
C   Z

The code you gave me works well, showing only the first two rows at page load. However, at page load, the drop-down filter on column 2 has three options: X, Y and Z. Since I'm using linked filters, I only want options X and Y to be visible when the row with Z is hidden. The 'linked filters' feature works fine otherwise, but not at page load. Can you please give me some more help with this? :)

**Comment by koalyptus** [comment]
@snacke,
for the linked filters feature you will simply need to activate the filter in the first column, as per example above:
```
tf.setFilterValue(0, 'A||B');
tf.activateFilter(0);
tf.filter();
```
Activating the master filter in linked filters makes the linking possible.
Tell me how it goes.

**Comment by koalyptus** [comment]
If you have a `checklist` or `multiple` filter types `setFilterValue` also accepts an array:
```
tf.setFilterValue(0, ['A', 'B']);
tf.activateFilter(0);
tf.filter();
```

**Comment by snacke** [comment]
Thank you again, but unfortunately I couldn't make it work.

This is the code that I am using right now. At page load, the table is filtered so that only rows with 'A' or 'B' in the 7th column are visible. As I mentioned earlier, the drop-down filters in other columns are showing options that aren't visible in the table.

`var filtersConfig = {  /* Lots of configuration settings... */  };`
`var tf = new TableFilter(document.querySelector('.mytable'), filtersConfig);`
`tf.init();`
`tf.setFilterValue(7, 'A || B');`
`tf.filter();`

If I understood your previous reply correctly, you suggested me to try the following code:

`var filtersConfig = {  /* Lots of configuration settings... */  };`
`var tf = new TableFilter(document.querySelector('.mytable'), filtersConfig);`
`tf.init();`
`tf.setFilterValue(7, 'A || B');`
`tf.activateFilter(7);`
`tf.filter();`

When I use this piece of code, the whole table is shown at page load (not just rows with 'A' or 'B'). Have I misunderstood your answer, or is there any other problem?

**Comment by koalyptus** [comment]
Seems correct to me. Can you tell me what is the filter type for column 7 and also the version of TableFilter you are using? Also can you post the config too?

**Comment by snacke** [comment]
Aaaahh... checking the version of TableFilter was a great idea :P I was using version 0.0.22, but I updated to the latest version and now it works perfectly. Thank you once again for your very useful help! :)
