### ISSUE TITLE
Destroy not removing event handlers

### ISSUE THREAD

**Issue by archisgore** [koalyptus/TableFilter#258]
I have a use case where I want to create and destroy "stateful" tables over the course of the same page.

That's when I discovered, that even deleted tables aren't unregistering event handlers. I looked at the minified javascript and what's going on is:

addEvt('foo', ()=>this.sync());
removeEvt('foo', ()=>this.sync());

Those closures ()=>this.sync() aren't the same function (in terms of the reference.)

So the corresponding remove doesn't end up removing the function which was added.

I believe caching the function in a variable is necessary to make it correct.

I'll try it out later today.

**Comment by koalyptus** [comment]
Hi @archisgore,
Thanks for pointing this out, just try:

addEvt('foo', this.sync);
removeEvt('foo', this.sync);

Cheers

**Comment by koalyptus** [comment]
Sorry forgot bind:
addEvt('foo', this.sync.bind(this));
...
Totally agree should be stored in variable.

**Comment by archisgore** [comment]
Thanks for the guidance koalyptus.

I submitted a PR. Do provide any feedback if you deem fit: https://github.com/koalyptus/TableFilter/pull/259
