### ISSUE TITLE
Some filtering does not work

### ISSUE THREAD

**Issue by jdachik01** [koalyptus/TableFilter#263]
The attached text file is an HTML page. Typing TEST1430 into the Keywords/Description column works, filtering out the rows that do not contain that string, but typing Joanne does not have the same effect.

I'm sure there's a good chance I'm doing something wrong, but I have had no luck figuring it out.

[1166231768170739.txt](https://github.com/koalyptus/TableFilter/files/380019/1166231768170739.txt)

**Comment by koalyptus** [comment]
Hi @jdachik01,
Remove the `col_number_format` and `custom_options` options from the configuration object (they do not make sense in your table) and should work as expected.
Cheers

**Comment by jdachik01** [comment]
Yes, I don't know how I missed that. Thank you. Now I'll try to figure out how to hide the toolbar...

Thanks again!
