### ISSUE TITLE
setting pre-checked values and delete default "show all" on Checklist element

### ISSUE THREAD

**Issue by altank52** [koalyptus/TableFilter#273]
Hi, 
is it possible to set pre-checked checklist elemets? unfortunately i couldn't find them in your demos.
also can i delete that default element appears always on top which the name comes from display_all_text: "show all" ?

Thank you for amazing script by the way :)

**Comment by koalyptus** [comment]
Thanks @altank52,

- Yes, you can programmatically select a `checklist` items with the `selectOptions(colIndex, values = [])` method of a `CheckList` instance. Assuming the checklist filter is in the first column:
```
var tf = new TableFilter('tableId', myConfig);
tf.init();
var checkList = tf.feature('checkList');
checkList.selectOptions(0, ['value',  'another_value']);
tf.filter();
```

- You can set the `enable_checklist_reset_filter` option to `false` to remove the first item. 
The configuration options names are a bit inconsistent, unclear and confusing, the wiki and the auto-generated documentation are not completed yet, so I understand it is difficult to find things :smile: 
https://github.com/koalyptus/TableFilter/wiki/1.06-Checklist-filter
http://koalyptus.github.io/TableFilter/docs/class/src/modules/checkList.js~CheckList.html#instance-member-enableResetOption

**Comment by altank52** [comment]
Hello @koalyptus ,
thank you for yor answer and `enable_checklist_reset_filter` is exactly what i wanted :)
However i couldn't set `selectOptions(colIndex, values = [])` method. Then i realize i never use `tf.init()` or `tf.filter()` and that makes me wonder if i am using one of the old versions.
```
/*------------------------------------------------------------------------
	- HTML Table Filter Generator v2.5.1
	- By Max Guglielmi (tablefilter.free.fr)
	- Licensed under the MIT License
--------------------------------------------------------------------------
Copyright (c) 2009-2012 Max Guglielmi
```
I guess that is the old version :) 

And this is how my code is;

`<script type="text/javascript" language="javascript" src="js/tablefilter_all.js"></script>`
```
<script language="javascript" type="text/javascript">  
	//<![CDATA[  
		var table2_Props =  {		
						custom_slc_options: {    
							cols:[3],
							texts: [[' Linux',' Windows']],    
							values: [['*Linux','*Windows']], 
							sorts: [false]    
						},						
						enable_checklist_reset_filter: false,
						col_1: "select",						
						col_3: "checklist",					
						col_4: "select", 
						col_5: "select",
						display_all_text: " [ Show all ] ",
						loader: true,  
						loader_html: '<div id="myModal" class="modal"><div class="modal-content">Processing... Please Wait<img src="images/processing.gif"></div></div>',			
						sort_select: true,
						input_watermark: 'Type to Search', 		
						col_width: ['120px','120px','110px','320px','240px','100px'],
						grid_width: '1200px',     						  
						checklist_item_css_class: 'myClass',						
					};  	
		var tf2 = setFilterGrid('example',table2_Props );
	//]]>  	

// My aproach:
//var tf = new TableFilter('example', table2_Props);
//	tf.init();
//		var checkList = tf.feature('checkList');
//		checkList.selectOptions(3, ['*Linux', '*Windows']);
//		tf.filter();
// Unfortunately didn't work

	</script>
```

Till now everything works fine except this checklist. 
What i really aim is:
having 2 checkbox in the list, one of them checked as default, if none of them checked it will list just nothing, also if both of them checked then list all. I hope i made myself clear about that :) English is not my prime :)

I also got crazy idea and i want to know if it is possible to make. Can i combine `checklist` and `select` in a same column. Let's say first we will check one of the list items, table filters itself, then we will select from filtered results again.
Let me explain with example;
![os2](https://cloud.githubusercontent.com/assets/19151747/17476341/e5942746-5d5f-11e6-863a-43bad8c62e6f.png)
I had first this much elements in the drop-down and it wasn't help much so i change them with check box.
![os1](https://cloud.githubusercontent.com/assets/19151747/17476431/4cff73c2-5d60-11e6-8016-b504ebd56ae0.PNG)
Now i need drop-down list again because of Usability and after i checked `Linux` , drop-down list should appear like this:
![os3](https://cloud.githubusercontent.com/assets/19151747/17476525/cf35eef2-5d60-11e6-997a-c4d228b95724.png)

Sorry to bother you with this, but possibilities are very wide with this script and i really love it :)
I hope you can find what is my problem and how to solve it, also i am looking forward to your aproach about second part of this comment :)

Thank you

**Comment by koalyptus** [comment]
Please note this is TableFilter's repository and HTML Table Filter Generator is no longer maintained. If you want to take advantage of new features and API, you would probably want to upgrade to TableFilter.
Cheers
