### ISSUE TITLE
Improved row counting on tbody

### ISSUE THREAD

**Issue by rimace** [koalyptus/TableFilter#278]
Would it be possible to only count rows in the tbody-tag?

The reason why this matters is that some "sticky table header"-libraries are appending an extra caption-tag and thead-tag to the table, so there are 2 extra rows. TableFilter is currently able to handle this behaviour flawlessly, except (of course) for row counting.

It could be something like "if a tbody-tag exists, only count those rows".  Thanks for any answer!

Regards

**Comment by koalyptus** [comment]
Hi @rimace,
Have you tried the rows_always_visible option?
http://koalyptus.github.io/TableFilter/rows-always-visible.html
I am not sure in terms of rows counting if it fixes the issue though.
Let me know

**Comment by rimace** [comment]
I tried it just now. `rows_always_visible: [0, 2]` has the effect that the caption-tag is also counted. So when no rows are visible, it says "Rows: 2" (instead of "Rows: 1").
So I would need more something like an option `ignore_rows` or something to correct the number of rows by -2.

Btw this isn't a urgent request. It could be seen as an improvement to support some sticky header libraries. In the mean time I work around it by manipulating the span "totrows_span" when on_after_refresh_counter is fired. This should do it for now, not beautiful though.

Thanks for that fast response!

**Comment by koalyptus** [comment]
Try to hook into on_before_refresh_counter to modify the tf.nbHiddenRows property to adjust the counter to expected total and then use on_after_refresh_counter to set nbHiddenRows back the original value.
Very ugly, not supposed to touch internals, but it might work.

**Comment by koalyptus** [comment]
Tidying up the issues.
