### ISSUE TITLE
Sort by date and time

### ISSUE THREAD

**Issue by schmelzpunkt** [koalyptus/TableFilter#283]
Sorting a column wich contains date and time is not possible yet.
E.g.: 24.08.2016 16:09

is there a plan to support this? Many tables contain datetime data like this.

**Comment by koalyptus** [comment]
What you could do at the moment is implementing your own custom sorter handling this date time format, refer to http://koalyptus.github.io/TableFilter/sort-custom-type.html

Date time support is currently very limited, the plan in the long term is to switch to the 'moment' library to support any format. This will happen once the current refactoring is completed.

**Comment by schmelzpunkt** [comment]
Super, thanks - did it as you recommended!
 
Date: Wed, 24 Aug 2016 14:31:46 -0700

**Comment by altank52** [comment]
@schmelzpunkt  how did you solved that? Could you please share it?
i am using this for a very large table with 14 columns and my 3rd(index 2) column has dates in such format "01/08/2016 14:28:54" and time is not important for me. 
Other fields hold string values and i was following with example that @koalyptus shared and i edited it little bit to fit my own situation.

`extensions: [{name: 'sort',
    types: ['string', 'string', 'dmydate', 'string',
    'string', 'string', 'string', 'string', 'string', 
    'string', 'string', 'string', 'string', 'string', 'string'],`

and ofcourse:

`on_sort_loaded: function(o, sort) {
                sort.addSortType('dmydate', customCaster, customSorter);
            }`

I have to say that i am pretty new on JS and ofc this script.
thanks for any help

**Comment by schmelzpunkt** [comment]
My Approach was quite simple:

// Cast to Date contained in string
function customCaster(val) {
    var dt = val.split(/\/|\s|:/);
    var day = Number(dt[0]);
    var month = Number(dt[1]);
    var year = Number(dt[2]);
    var mydate = new Date(year, month, day, 0, 0, 0, 0);
    return mydate ;
}

// Custom sorter
function customSorter(n1, n2) {
    if (n1.value < n2.value) {
        return -1;
    }
    if (n2.value < n1.value) {
        return 1;
    }
    return 0;
}

**Comment by koalyptus** [comment]
:+1: @schmelzpunkt
