### ISSUE TITLE
sort_select: true does only order by String - implement custom sorter hook

### ISSUE THREAD

**Issue by schmelzpunkt** [koalyptus/TableFilter#284]
The sorting of the values in a Dropdown list filter should consider the data type. Right now it seems to sort always by string even if it is a number or a date

**Comment by koalyptus** [comment]
What you can do at the moment to sort numeric drop-down options in a ascending or descending manner is use the `sort_num_asc` or `sort_num_desc` options:
```
var tfConfig = {
  col_0: 'select',
  col_1: 'checklist',
  sort_num_asc: [0],
  sort_num_desc: [1]
};
```
The above configuration instructs TableFilter to sort the the drop-down filter numeric options in a ascending manner for the first column and in a descending manner for the second one.

Date sorting for drop-down options is currently not supported, this is another story as the script needs first to support any formatted datetime (refer to #283). However, we could add a callback for sorting the drop-down options, where you would implement your own custom sorter as it is already the case for column sorting (#283).

**Comment by albertonbass** [comment]
Hello. First of all, thank you for this TableFilter. I love it! And second, sorry about my english, it's not my main language.

I would like to sort the drop-down filter. It's the only thing that I need at this moment. It's for a date, and for a custom type. In your last message, you say:

> However, we could add a callback for sorting the drop-down options, where you would implement your own custom sorter as it is already the case for column sorting.

But I don't find anything about how to implement this. I don't know if you talked about a posibility to implent in a future, or if there is a real way to implement this. 

Sorry if this is answered in another post, I have been searching but I don't find anything.

**Comment by koalyptus** [comment]
Hi @albertonbass,
no worries, I only spoke about the possibility of adding a hook for allowing a custom sorter for drop-down options. Unfortunately at this stage this is not implemented yet.

**Comment by albertonbass** [comment]
Oh! What a pity! I will wait for it. But one question more. Is there a way to tablefilter don't sort by alphabetic order the drop down filters? At first, i thought the list was filled in order of a appeareance, but it always sort in alphabetic.

Thank you!

**Comment by koalyptus** [comment]
Yeah I know, I remember thinking about doing it but got dragged away by other priorities.
You can set the `sort_select` option to false to disable the default alphabetic order for the `select`, `multiple` and `checklist` filter types. Unfortunately this is a global flag so it will apply to all those filter types on your table, if you have more than one.

**Comment by albertonbass** [comment]
Well. I've read the docs many times, but I don't know sort_select! Why!!!??? Thank you. This solves one thing, because my tabla has a dates in order. But don't solve the custom types.
Although I think it's simple, now I know that it's not possible by options I've decide to use javascript to modify DOM. There is a lot of examples on how to sort a html options. This works for me. It uses a version of functions of @schmelzpunkt in #284, to sort custom types. In function SortOptions I've referenced Id 'flt2_mociones', because is the name of my select options. Every one must search yours. I think the name is 'flt'+col_number+id_table.

```
<script>
function customSort(val) {
      
    var valor = val.split("separator");
    if (valor[0]==="Todos/as") { valor[0]="01-01-1900"};
    var dt = valor[0].split("-");
	var day = Number(dt[0]);
	var month = Number(dt[1]);
	var year = Number(dt[2]);
	var mydate = new Date(year, month-1, day, 0, 0, 0, 0);
	return mydate;
}

function SortOptions(){
vec=document.getElementById('flt2_mociones').options;
tmp=new Array();
for(i=0;i<vec.length;i++){
tmp.push(vec[i].text+'separator'+vec[i].value);
}
tmp.sort(function(a,b){
     if ((customSort(a)) < (customSort(b))) 
       {return -1;}
     if ((customSort(a)) > (customSort(b)))
     {return 1;}
	  return 0;
});

document.getElementById('flt2_mociones').length=0;
for(i=0;i<tmp.length;i++){
aux=tmp[i].split('separator');
document.getElementById('flt2_mociones').options[i]=new Option(aux[0],aux[1]);
}
}


</script>

```

And I call SortOptions(), after TableConfig.

```
<script>
var tf = new TableFilter('mociones', filtersConfig);
tf.init();
SortOptions();
</script>
```

It's not the most efficient code, but it works. You can use jquery or whatever do you want. I share it, because it could useful to another rookie like me.

**Comment by koalyptus** [comment]
Tx for sharing your code @albertonbass 
By the way:
- the `sort_select` option appears in this [wiki page](https://github.com/koalyptus/TableFilter/wiki/1.05-Drop-down-filter) and also in the title of this issue.
- The `getFilterId(columnIdex)` public method on the `TableFilter` instance gives you the filter's element ID of a specified column: http://koalyptus.github.io/TableFilter/docs/class/src/tablefilter.js~TableFilter.html#instance-method-getFilterId, no need to hardcode `flt2_mociones`

I have prioritised this issue, I'll probably pick this one as the next task, to recap:
- sort the filter options based on the type of the column (string, number, date) therefore making the `sort_num_asc` and `sort_num_desc` obsolete (TBC)
- allow a hook to allow a custom sorter

**Comment by albertonbass** [comment]
Thank you, thank you, thank you! It wasn't a complain about the documentation, it was a complain about my reading skills! 

Also, I don't control public methods, but I think that is a good start point. 
Again, thank you.

**Comment by koalyptus** [comment]
Starting from v0.5.12, `TableFilter` will sort by default the dropdown filter options based on the column type. It will also be possible to sort a filter options with a custom sorter by using the new `filter_options_sorter` [configuration option](https://github.com/koalyptus/TableFilter/wiki/1.05-Drop-down-filter).
Cheers
