### ISSUE TITLE
Feature request: add sort order to location hash

### ISSUE THREAD

**Issue by rs2** [koalyptus/TableFilter#294]
Using `tablefilter v0.2.39 by Max Guglielmi`

**Comment by koalyptus** [comment]
Sort order is already supported, refer to this demo:
http://koalyptus.github.io/TableFilter/deep-linking.html

Don't hesitate to upgrade to a more recent version.
Cheers

**Comment by rs2** [comment]
Thank you, works as expected. I think the term `deep linking` is a bit vague, and it was not immediately obvious that this is what I'm after.
