### ISSUE TITLE
Colspan not supported

### ISSUE THREAD

**Issue by KGFTW** [koalyptus/TableFilter#295]
Hi Koalyptus,

I am using tablefilter to handle a table, and would like to use colspans on the headers to group subheaders, but without any filter on the colspan rows (see example below)
 
![headers](https://cloud.githubusercontent.com/assets/6064738/18627430/223c1016-7e5b-11e6-98b1-01cf0ea933b3.png)

It seems that this cannot be accomplished directly from integrating pure html colspan tags directly into the page, but I actually found a way to achieve it: 
After tablefilter init, I prepend the colspaned ths in the thead, move the .fltrow element after the second row (the one already present in the html, initialized with the filters) and applying a display: none !important class to it (else it would appear after filtering).

After doing this, it works pretty well ! (Here's the [code sample integrated in jsfiddle](https://jsfiddle.net/KGFTW/wLexc6pt/))
The filter image does not display but its still works, and in my real page it does not "reload" on filter.

I think that this is more of an enhancement request than an issue since it is actually not directly supported.
You already answered [a similar question](https://github.com/koalyptus/TableFilter/issues/62), but I thought that this might be usefull to anyone with the same usecase as mine, and that would be amazing to include such a feature in the future :)

**Comment by koalyptus** [comment]
Hi @KGFTW,
Thanks for your detailed comment, have you seen this demo
http://koalyptus.github.io/TableFilter/grouped-headers.html ?
It shows how to handle multi-line and grouped headers :smile:

**Comment by KGFTW** [comment]
Hi @koalyptus,
Actually yes I did, and it does not seem to handle both grouped headers and popup filters unfortunately (forgot to mention it sorry about that).
Here are two fiddles to demonstrate it :
[With popup filters](https://jsfiddle.net/KGFTW/wLexc6pt/3/)
[Without popup filters](https://jsfiddle.net/KGFTW/wLexc6pt/4/)

I need those damn popup filters :P

**Comment by koalyptus** [comment]
Indeed it is a bug, this is the workaround, basically adding an empty row to the table headers and update the corresponding config properties accordingly:
https://jsfiddle.net/wLexc6pt/5/

Cheers

**Comment by koalyptus** [comment]
Hi @KGFTW,
I just published v0.2.66 which should fix this issue, this is the corresponding fiddle:
https://jsfiddle.net/wLexc6pt/6/

Cheers

**Comment by KGFTW** [comment]
Hi @koalyptus,

Works pretty well, thanks a lot for the fast answers, the workaround, and the fix (as always :D) :+1:
