### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#297]
on the grid layout the columns display nicely and headers are always visible but for those with large screens viewing the table in the original "small" size can be annoying.  Would it be possible to add a "View table in full screen" option as can be seen on the panels in this bootstrap panel extension so that the user can temporarily fill the whole screen with the table?
http://lobianijs.com/site/lobipanel#examples

Or make the corner of the table dragable for resizing?

**Comment by koalyptus** [comment]
Have a look to this demo, it might help:
http://koalyptus.github.io/TableFilter/responsive-grid-layout.html

**Comment by cjohnsonuk** [comment]
I'll try popping that demo table into a bootstrap panel and making the
table 100% and see if it follows the size of the panel when I make the
panel fullscreen...  If it works I'll let you know...

Thanks for getting back so quickly, again! :-)

Chris Johnson
