### ISSUE TITLE
column calculations

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#298]
Not sure if this is just an issue with the demo page but on this page :

http://koalyptus.github.io/TableFilter/column-calculations.html

the calculated values are not showing in the rows at the bottom as they have done previously and the JS console displays : 
ReferenceError: assignment to undeclared variable k

**Comment by koalyptus** [comment]
Thanks for pointing this out, @cjohnsonuk, unfortunate bug not caught by unit tests. I will release a fix whenever I have some spare time.
Cheers

**Comment by koalyptus** [comment]
It is now back on track (v.0.2.67)
