### ISSUE TITLE
Select/multiple options with "*" in don't filter correctly

### ISSUE THREAD

**Issue by nwp90** [koalyptus/TableFilter#30]
If I have a column in a table that contains some "P", some "PD" and some "P\*", it's impossible to filter correctly to see only those rows with "P*" in that column. It seems that there is some attempt to make this work in _containsStr, but it doesn't work. I haven't debugged as I have no easy access to an un-minified version of tablefilter.

**Comment by koalyptus** [comment]
Hi Nick,
Currently in remote locations with no internet access. Try the ''exact_match: true'' property.
Cheers

**Comment by nwp90** [comment]
IIRC exact_match only works per-table, and other columns require the usual matching style. I'll try it anyway, to check that that does at least work.

**Comment by koalyptus** [comment]
Correct it is a global flag, make it on a per column basis would be a good candidate for a feature request.

**Comment by nwp90** [comment]
Surely it *should* be possible to match it with a regexp filter too...
