### ISSUE TITLE
highlightKeywords does not clean properly after unhighlighting

### ISSUE THREAD

**Issue by jerefrer** [koalyptus/TableFilter#309]
Hi there and many thanks for this quite easy-to-use and powerful piece of work :)

I realized that after I filter a column with a search term of say 3 chars, then when removing the filter it leaves the original text split in 3 parts : `before the search term` + `the 3 chars of the search term` + `after the search term`.

Then when trying to search for a term of 4 chars or more, the results are actually filtered but the search terms are no longer highlighted. I guess this happens because the text is actually split from before.

I would try fixing it myself but I'm afraid I'm not fluent enough in JS to make it as performant as possible.

All my love to anyone willing to pick up this fight :bowing_man:

**Comment by koalyptus** [comment]
Hi there,
Which version are you using?

**Comment by koalyptus** [comment]
I am able to reproduce this issue on latest version (v0.3.1) on http://koalyptus.github.io/TableFilter/highlight-keywords.html demo page.
Thanks for pointing this out, I will try to sneak a fix in in one of next release(s).
Cheers

**Comment by koalyptus** [comment]
@jerefrer,
It should now work starting from v0.3.2.
Cheers

**Comment by jerefrer** [comment]
Haha no time like the present, right ?
Thanks a bunch, it's now working smoothly ! :tada:
