### ISSUE TITLE
Data type of date+time

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#313]
I've modded our helpdesk software to use tablefilter for the ticket list but the time and date field for when the tickets were logged doesn't appear to work with sorting / filtering.  I've modded the output so that its just the dates showing and the time of the call is in a mouseover pop up and this sorts / filters now (just on date).  This worked well when there were few calls but on busy days with many tickets it would be good to be able to sort / filter on a full date/time rather than just date.

Does/should this work?

**Comment by cjohnsonuk** [comment]
found this : https://github.com/koalyptus/TableFilter/issues/283, working through it now...

**Comment by koalyptus** [comment]
Starting from v0.3.0, it should now be possible, just have look to this demo:
http://koalyptus.github.io/TableFilter/data-types.html
If your datetime format is a known format, the default 'en' locale should handle it. Otherwise try a more specific locale or define your format.

**Comment by cjohnsonuk** [comment]
My datetime data is in the format

2016-10-14 10:52:42 	

I added this : 
col_types: ['None','String', {type: 'date', locale: 'en-GB', format: ['{yyyy|yy}-{MM}-{dd} {HH}:{mm}:{ss}']}, 'ymddate','String','String', 'String','String', 'String', 'String'],

but get this error:

TypeError: t is undefined
...(t,e,i){"use strict";function n(t){var e=t.join("");return t&&t.length?e.length=...
tablefilter.js (line 11, col 8339)

(in firebug, using TableFilter v0.3.3)


Changed it to using this:


and it works great, both for sorting and for filtering

**Comment by koalyptus** [comment]
Not sure it is related to the js error, but 'ymddate' is no longer a valid type, use 'date' or literal object as you did for the other column. 'locale' can be used as a global flag.

**Comment by cjohnsonuk** [comment]
OK, its working for me now without any errors, I'll correct the ymddate later...

**Comment by ebw44** [comment]
Not sure if it's related or if a885c8c is supposed to fix it but for me the 24 hours format
`{ type: 'date', locale: 'fr', format: ['{dd}/{MM}/{yy} {HH}:{mm}'] }`
raise a TyperErrror when the 12 hours doesn't
`{ type: 'date', locale: 'fr', format: ['{dd}/{MM}/{yy} {hh}:{mm}'] }`
however the sorting seems to work whatever I use.

The full error output is:
```
dateType.js:134 TypeError: Cannot read property 'join' of undefined
    at arrayToRegAlternates (arrayToRegAlternates.js:7)
    at getTokenSrc (getNewLocale.js:244)
    at getNewLocale.js:278
    at String.replace (<anonymous>)
    at formatToSrc (getNewLocale.js:273)
    at parseInputFormat (getNewLocale.js:287)
    at Locale.addFormat (getNewLocale.js:290)
    at dateType.js:131
    at Array.forEach (<anonymous>)
    at dateType.js:130
```

**Comment by koalyptus** [comment]
hi @ebw44,
from what I see that commit adds a try catch around the sugar's `locale.addFormat` which throws, the exception gets logged in the catch. I can't remember if I raised an issue for that on sugars repo. [This](https://github.com/andrewplummer/Sugar/blob/ea596dcb0e554b646f7250268e547c591a611b91/lib/date.js#L1938) seems to be the culprit, somehow no array is passed `arrayToRegAlternates`...
