### ISSUE TITLE
Ignore diacritics in filtering ?

### ISSUE THREAD

**Issue by jerefrer** [koalyptus/TableFilter#314]
I'm using TableFilter inside an application that's going to be used by french speaking people, so there will for sure be accented vowels everywhere, in people names for example.

It would then be nice to be able to type "Jer" in the first name column filter and have results showing for "Jérémy" and "Jérôme".

Is that already possible ?
If not I think this would definitely be useful for all non-english languages such as French, Spanish or German.

I haven't digged into custom function or anything so I bet that it would be possible using those, but since it's such a common case in these languages I'd rather see a proper option `ignoreDiacritics: true/false`.

What do you think ?

**Comment by koalyptus** [comment]
Hi there,
Good point that's not possible at the moment, I totally agree with you for having a proper `ignoreDiatcritics` option perhaps even on a column basis.
Currently you could use the badly named `custom_cell_data` callback (stands for `cell_parser`) to strip the diacritics out, have a look to this example for usage:
http://koalyptus.github.io/TableFilter/filter-images.html

**Comment by koalyptus** [comment]
Starting from v0.4.0, filtering can ignore diacritics with the `ignore_diacritics` option:
https://koalyptus.github.io/TableFilter/docs/file/src/tablefilter.js.html#lineNumber389

Let me know how it goes,
Cheers
