### ISSUE TITLE
partial table rendering issue

### ISSUE THREAD

**Issue by stevenryals** [koalyptus/TableFilter#315]
I'm importing sortabletable.js, tfAdapter.sortabletable.js, tablefilter.js
my table id = table
thead and tbody exist
js config has no errors

the rendering is only partial.  any thoughts? 

![image](https://cloud.githubusercontent.com/assets/1985628/19393999/70c5b92e-91f4-11e6-9306-0bdc621bea2a.png)

**Comment by koalyptus** [comment]
TableFilter has no tfAdapter.sortabletable.js file, which makes me think you are using HTML Table Filter Generator. Please post an issue in its own GitHub repo or upgrade to TableFilter.
Cheers

**Comment by stevenryals** [comment]
I'm not, that was an old line.  it's removed now.

This is the error I get when it tries to apply the TableFilter to the table

`Uncaught TypeError: Cannot read property 'split' of undefinedTF._PopulateSelect @ tf_populateSelect.js:46_AddGrid @ tablefilter.js:1049(anonymous function) @ tablefilter.js:906`

**Comment by stevenryals** [comment]
OK, I've commented out each line of the filter configs individually.  this line:

`remember_grid_values: true,`

is causing the error.  with that line commented out, everything works fine.  
Strange.

**Comment by koalyptus** [comment]
You are still using the old one, all the errors above refer to old scripts. Clean your project from old files. Btw remember_grid_values is not a configuration option for TableFilter.
Once you start from a clean state, you'll see nothing is strange ☺
