### ISSUE TITLE
when a page is updated, the filter values ​​are cleared

### ISSUE THREAD

**Issue by SergoVL** [koalyptus/TableFilter#322]
when a page is updated, the filter values ​​are cleared. What should I do to filter the values ​​preserved?

**Comment by koalyptus** [comment]
If you want to persist the filter values use the 'state' option as per:
http://koalyptus.github.io/TableFilter/persistence.html

**Comment by SergoVL** [comment]
If you want to persist the filter values use the 'state' option as per:
http://koalyptus.github.io/TableFilter/persistence.html

**Comment by SergoVL** [comment]
What parameters are recorded for example in Table5?
