### ISSUE TITLE
Cols visibility vs state

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#327]
Which takes precedence?  I've got state recording the visible columns
`state: { types: ['local_storage'],filters: true, sort: true, columns_visibility: true, page_number:true, page_length: true},`
and I also have 
`extensions : [{name: 'colsVisibility', at_start: [3,4,6,7,9,17,18], text: 'Untick to hide:', enable_tick_all: true, tick_to_hide:false },...`

Ideally I'd like the visible columns at_start to only apply if there is no state to say "I've already unhidden these columns : x,y,z"

**Comment by koalyptus** [comment]
`at_start` overrides `state` at `ColsVisibility` initialization. Columns persisted as visible by `state` are simply hidden by `at_start`. What you could do is remove the `at_start` property in the config and hook into the `columns-visibility-initialized` event to implement your conditional logic, for example (untested logic):
```
var tf = new TableFilter('table-id', yourConfiguration);
tf.emitter.on(['columns-visibility-initialized'], function(tf, colsVis) {
  var hideConditionally = [3, 4, 6, 7, 9, 17, 18];
  var colsHiddenByState = tf.feature('state').hiddenCols || [];
  hideConditionally.forEach(function(idx) {
    if(colsHiddenByState.indexOf(idx) === -1) {
      colsVis.hideCol(idx);
    }
  });
});
tf.init();
```
