### ISSUE TITLE
exact_match setting per column

### ISSUE THREAD

**Issue by nwp90** [koalyptus/TableFilter#34]
Feature request: exact_match being settable per-column. e.g. I have a name field which needs a standard regexp filter in column 1, and a mark selected from a dropdown which needs exact_match in column 2...

**Comment by koalyptus** [comment]
Feature request now captured in the WIKI [TODO](https://github.com/koalyptus/TableFilter/wiki/TODO) page.

**Comment by koalyptus** [comment]
Master branch now implements exact match filtering on a column basis. Just added relevant example pages to the project's website: [http://koalyptus.github.io/TableFilter/examples](http://koalyptus.github.io/TableFilter/examples).
Cheers
