### ISSUE TITLE
Add filter popup persistence option

### ISSUE THREAD

**Issue by KGFTW** [koalyptus/TableFilter#340]
Hi @koalyptus,

I just got a feedback that's quite relevant: once clicked on an option of a popup filter, its popup disappears and we have to click back on the popup button to display it again, select another option, and repeat for every filter we want to apply on the table (which is the normal behavior).

Is there any available option in the filters configuration that could enable a "persistence" mode on popup filters ?

I couldn't find itin the wiki so I expect this to be an enhancement.

Just so you know, I added this code to my page so that when the user clicks out of the popup, it would automatically close (not natively), which is I believe a pre-requirement to what I'm asking from you :)

```
// On mouse up event, check if the user clicked out of a popup filter if any is active
$(document).on('mouseup', function(e){
    var container = $('.popUpFilter:visible');
    if(!container.is(e.target) && container.has(e.target).length === 0) { 
        container.hide();
    }
});
```

**Comment by koalyptus** [comment]
Hi @KGFTW,
Is your description same as point 3 in https://github.com/koalyptus/TableFilter/issues/339#issue-189348907 ?
Trying to understand if you refer to same thing. 
Your code seems to me to perform an auto-close behaviour when user clicks away.

**Comment by KGFTW** [comment]
@koalyptus You're right that's what I'm refering to.
About my code, you're right too. I added this to the page to make popup filters more user-friendly, and think that it would be great having it with the multi-filter-selection from popup filters since it wouldn't automatically close on selection.

**Comment by koalyptus** [comment]
Starting from v0.4.11, enhanced popup filters behaviour as per discussion above:
- multiple selection filter types now remain open upon filtering
- added `popup_filters_close_on_filtering` option (defaulting to true) to choose if the filters should close upon filtering
- filters automatically close when user clicks away 

Cheers

**Comment by KGFTW** [comment]
@koalyptus Works like a charm ! :+1: 
Thanks a lot, once again, for your great work and support :)
