### ISSUE TITLE
Filter width

### ISSUE THREAD

**Issue by GandRWebDev** [koalyptus/TableFilter#345]
I'm using popup filters and would like them to be bigger than what my columns are, where do I change that? The code is hard to read. I could just manually do it after the table loads, but I'd love to be able to just set the filter widths independently of column widths.

**Comment by koalyptus** [comment]
You can unlock the popup filter widths by using a property called ``popUpFltAdjustToContainer `` which unfortunately is not currently available as configuration option:
```
var yourConfig = {
...
  on_filters_loaded: function(tf) {
    var feature = tf.feature('popupFilter');
    feature.popUpFltAdjustToContainer = false;
  },
...
};
```
Refer to http://koalyptus.github.io/TableFilter/docs/class/src/modules/popupFilter.js~PopupFilter.html#instance-member-adjustToContainer

Then to control the filter widths independently: 

1. you can simply use a custom CSS class for the filters:
```
var yourConfig = {
...
  flt_css_class: 'my-filter-css-class-name',
...
};
```
Refer to 
https://github.com/koalyptus/TableFilter/wiki/1.01-Appearance 
http://koalyptus.github.io/TableFilter/docs/class/src/tablefilter.js~TableFilter.html#instance-member-fltCssClass

2. Override the default `flt` CSS class defining a filter's style by including the width

**Comment by koalyptus** [comment]
Starting from v0.4.13 you can take advantage of the `popup_filters_adjust_to_container` configuration option to control whether the popup filter container should match the column's width or not.
