### ISSUE TITLE
Sorting Date column with blank rows

### ISSUE THREAD

**Issue by Nexpola** [koalyptus/TableFilter#347]
Hi', I'm having trouble with sorting date columns where there are some empty rows.
Sorting seems to be random... but works perfectly where all rows are filled with dates.

This defect can be saw even with a basic configuration. 
This is mine:

```
    var filtersConfig = {
	highlight_keywords: true,
	popup_filters: true,
	linked_filters: true,
	alternate_rows: true,
	btn_reset: true,
	rows_counter: true,
	locale: 'it-IT',
	col_types: ['string', 'string', 'string', 'date', 'string', 'date'],
	
	extensions:[{ name: 'sort' }]
    };
    var tf = new TableFilter('table1', filtersConfig);
    tf.init();
```

Thank for your help

**Comment by koalyptus** [comment]
@Nexpola, thanks for pointing this out, I will have look.
Cheers

**Comment by koalyptus** [comment]
Starting from v0.4.14 should be fixed.
Cheers

**Comment by Nexpola** [comment]
Great! 
Thank you!

**Comment by Nexpola** [comment]
Just downloaded v0.4.14: **it works perfectly!**
Thankyou!
