### ISSUE TITLE
Coloumn containg select html tag show all options appended

### ISSUE THREAD

**Issue by vikas17a** [koalyptus/TableFilter#35]
If i have a table as follows
```
<table>
   <tr><td><select><option value='test1' selected>test1</option><option value='test2'>test2</option></select></td></tr>
</table>
```
I am getting available options in filter as
```
[Show All]
test1test2
```
I need them to be separated out any help ?

**Comment by koalyptus** [comment]
It depends on your requirements, you could use the ``custom_options`` option as shown in this [pen](http://codepen.io/koalyptus/pen/dYXwMg).
Note that I had to fix a bug to make it work, so you better pull the master branch, [latest commit b1bc351858](https://github.com/koalyptus/TableFilter/commit/b1bc351858ccb821f97c5d2e5beebf2d0ef4ecc4).

Another option would be to take advantage of the ``custom_cell_data`` delegate, to parse the selected option on each cell, as shown in this demo of the previous HTML Table Filter Generator library:  
[http://tablefilter.free.fr/custom-data.htm](http://tablefilter.free.fr/custom-data.htm). Have a look at the ``Contact type`` column. The usage of that option is the same in ``TableFilter`` but there is no demo available yet in the project website.

**Comment by koalyptus** [comment]
Added example page featuring the ``custom_cell_data`` callback, :
http://koalyptus.github.io/TableFilter/custom-filtering.html
