### ISSUE TITLE
Can TableFilter provide a row label with row index?

### ISSUE THREAD

**Issue by WaiPang** [koalyptus/TableFilter#350]
It  is possible to have  a row count for each and every row. This will be a bit like excel. 
This row count will by dynamic so that when you filter the columns and not hard coded to a particular column. The row column a sequential list of number adjusted based on the number of rows visible.
Preferably the row count is a label rather than a filter. The label should have the same css style as the column header.

Currently I have a hack, which is to create an empty column who's type is "none". I have a separate js to set 
this empty column.  Bit of a hack - should really be implemented on TableFilter. 

This is a really powerfull API - thanks a lot.

**Comment by koalyptus** [comment]
Thanks @WaiPang for suggesting this feature, probably not a priority at current stage but a good to have.
Also, if you use `TableFilter` APIs to implement it, then it's probably more a mashup then a hack 😄

**Comment by WaiPang** [comment]
I definitely prefer a mashup than a hack. I don't know css and html but I do know how to code.  Is there a convenient method to add a column and then assign a value to every element. I could see this being a powerful feature like adding prices to every column and use a new column to display it's subtotal.
