### ISSUE TITLE
Export filtered data via CSV

### ISSUE THREAD

**Issue by Nexpola** [koalyptus/TableFilter#352]
Hi,
I suppose it could be very useful if TF could integrate a native button to generate a CSV to download filtered data.

I'm trying to create CSV myself with the getFilteredData funcion but is very tricky because all the values in result are divided with a comma only without any line break. Else I should try to retrieve filters applied by the user, build a MySQL query and via PHP execute it directly on the database...

Thankyou in advance

**Comment by koalyptus** [comment]
Thanks for suggesting this feature, it is now captured as a feature request but not a priority for the moment as still in the refactoring process.

> all the values in result are divided with a comma only without any line break
that's normal, javascript arrays do not have line breaks.

Cheers

**Comment by Nexpola** [comment]
Thank you @koalyptus 
In the meantime I solved using a very simple PHP script. :smiley: 
A JS send data via POST to another file called "export_filtered.php" which generate the output file.

I post the code here, I hope this could help someone:


This code goes in the same page where is the table, it send header and filtered data via POST.
```
<button onclick="export_csv();">Export CSV</button>

<script>
function export_csv() {

    var form = document.createElement("form");
    form.setAttribute("method", "post");	
    form.setAttribute("action", 'export_filtered.php');

            var hiddenField = document.createElement("input");
            hiddenField.setAttribute("type", "hidden");
            hiddenField.setAttribute("name", "Header");
            hiddenField.setAttribute("value", tf.getHeadersText());

            form.appendChild(hiddenField);
		 
            var hiddenField = document.createElement("input");
            hiddenField.setAttribute("type", "hidden");
            hiddenField.setAttribute("name", "String");
            hiddenField.setAttribute("value", tf.getFilteredData());

            form.appendChild(hiddenField);
    

    document.body.appendChild(form);
    form.submit();
}
</script>
```


This code instead is the PHP script (highly commented :wink: : ) which generate the CSV file:
```
<?php
$string=$_POST['String'];
$header=$_POST['Header'];

$report= explode("," , $string); //place data into an array
$titles= explode("," , $header); //place column titles into an array

$cols= count($titles);
$fields= count($report);
$rows= $fields / ($cols+1); //cols+1 because there is an index column in data export

//start outputting CSV file
//write the title row

header("Content-type: text/csv");
header("Content-Disposition: attachment; filename=Export.csv");

$p=0; //initial id of the record in the titles array

while ($p < $cols) {	 //loop titles array and print it out
	echo "\"".$titles[$p]."\";"; 
	$p++;
}
echo "\n"; //add a line break at the end of titles row

//now write the data rows

$p=0; //initial id of the record in the data array
$i=0; //current row in the data array

while ($i < $rows) { //loop every single row	
	$o=0; //initial id of the record in the data array, set to zero every new row
	$p++; //add 1 to skip the first index column in data array
	
	while ($o < $cols) { //loop data array until the end of the row and print it out
		echo "\"".$report[$p]."\";";
		$o++;
		$p++;	
	}
		
	echo "\n"; //add a line break at the end of data row
	$i++;
}
?>
```

Bye!

**Comment by koalyptus** [comment]
Thanks for sharing your solution @Nexpola.

**Comment by hoverduck** [comment]
Another big thanks to @Nexpola for sharing that solution, it works great!  But one note for anyone else who stumbles on this thread - depending on what you need in your report you may want to change

`tf.getFilteredData()` to `tf.getFilteredValues()`

That will return what's actually displayed in the table, vs the behind-the-scenes values.

**Comment by nadenislamarre** [comment]
thanks a lot.
I've improved a bit to get more robust result (coma where causing troubles)

        <button onclick="export_csv();" id="export_csv">Export result as CSV</button>

<script>
function export_csv() {
    var form = document.createElement("form");
    form.setAttribute("method", "post");
    form.setAttribute("action", 'csv.php');

    var hiddenField = document.createElement("input");
    hiddenField.setAttribute("type", "hidden");
    hiddenField.setAttribute("name", "Header");
    hiddenField.setAttribute("value", JSON.stringify(tf.getHeadersText()));

    form.appendChild(hiddenField);

    var hiddenField = document.createElement("input");
    hiddenField.setAttribute("type", "hidden");
    hiddenField.setAttribute("name", "Lines");
    hiddenField.setAttribute("value", JSON.stringify(tf.getFilteredData())); // tf.getFilteredValues()

    form.appendChild(hiddenField);

    document.body.appendChild(form);
    form.submit();
}
</script>


<?php

header("Content-type: text/csv");
header("Content-Disposition: attachment; filename=export.csv");

if(isset($_POST['Header'])) {
    $lines = json_decode($_POST['Header']);
    foreach($lines as $value) {
        echo $value.";";
    }
    echo "\n";
}
if(isset($_POST['Lines'])) {
    $lines = json_decode($_POST['Lines']);
    foreach($lines as $rawline) {
        foreach($rawline[1] as $value) {
            echo $value.";";
        }
        echo "\n";
    }
}

exit(0);
?>

**Comment by nadenislamarre** [comment]
Thanks. i'm improved a bit cause coma where causing issues:

`<button` onclick="export_csv();" id="export_csv">Export result as CSV</button>

<script>
function export_csv() {
    var form = document.createElement("form");
    form.setAttribute("method", "post");
    form.setAttribute("action", 'csv.php');

    var hiddenField = document.createElement("input");
    hiddenField.setAttribute("type", "hidden");
    hiddenField.setAttribute("name", "Header");
    hiddenField.setAttribute("value", JSON.stringify(tf.getHeadersText()));

    form.appendChild(hiddenField);

    var hiddenField = document.createElement("input");
    hiddenField.setAttribute("type", "hidden");
    hiddenField.setAttribute("name", "Lines");
    hiddenField.setAttribute("value", JSON.stringify(tf.getFilteredData())); // tf.getFilteredValues()

    form.appendChild(hiddenField);

    document.body.appendChild(form);
    form.submit();
}
</script>


header("Content-type: text/csv");
header("Content-Disposition: attachment; filename=export.csv");

if(isset($_POST['Header'])) {
    $lines = json_decode($_POST['Header']);
    foreach($lines as $value) {
        echo $value.";";
    }
    echo "\n";
}
if(isset($_POST['Lines'])) {
    $lines = json_decode($_POST['Lines']);
    foreach($lines as $rawline) {
        foreach($rawline[1] as $value) {
            echo $value.";";
        }
        echo "\n";
    }
}

exit(0);
?>
`
