### ISSUE TITLE
Grid layout with adaptive column width

### ISSUE THREAD

**Issue by shlimi** [koalyptus/TableFilter#354]
I love the grid layout, but: it has fixed column width :-(
The standard (non grid) layout sets the width according to the column content and this is what I'd like grid layout could do. The option 'grid_default_col_width' is the only one I've found, but no success...
Any idea how to get it work?

Thanks a lot!
Michael

**Comment by koalyptus** [comment]
Unfortunately, it is currently one of the requirements to have fixed column widths for the grid-layout mode. I am afraid there is no easy work-around, this is what you could do:
1. Set `grid_default_col_width` to `'auto'` and remove `col_widths` option if any
2. Subscribe to the `initialized` event and programmatically set the content table columns widths to the headers table columns:
```javascript
    var tf = new TableFilter('your-table-id', yourConfigObject);
    tf.emitter.on(['initialized'], function(tf){
        var gridLayout = tf.feature('gridLayout');
        var headerTable = gridLayout.headTbl;
        var headerCols =  headerTable.getElementsByTagName('col');

        [].forEach.call(tf.tbl.rows[0].cells, function(cell, idx){
            headerCols[idx].style.width = cell.clientWidth + 'px';
        });
    });
    tf.init();
```

**Comment by shlimi** [comment]
Thanks for the prompt reply! The solution was promising, but unfortunately the header looses the synchronization to the rest of the table. Means that header has now its own column widths and you cannot relate it to the data columns:
![losingrelationtoheader](https://cloud.githubusercontent.com/assets/24245645/20925517/cc7cd486-bbb7-11e6-919c-83b005d68c27.jpg)

After applying column visibility extension you get this:
![afterselectingvisiblecolumns](https://cloud.githubusercontent.com/assets/24245645/20925534/e337c8f2-bbb7-11e6-8165-76a0fb5fb08d.jpg)

What I'd like to have actually is a table with a **frozen header** that does not scroll. Maybe there is another way to do this apart from using grid layout?

**Comment by koalyptus** [comment]
For both scenarii, try to import the main stylesheet filtergrid.css in page head or before the table element as mentioned in http://koalyptus.github.io/TableFilter/grid-layout.html demo.
