### ISSUE TITLE
Table filter won't initialize until there are 2 elements

### ISSUE THREAD

**Issue by thenning** [koalyptus/TableFilter#381]
When my table is empty, instead of initializing, it fails at getCellsNb. The argument seems to default to 2 which tries to reference an element in the table that doesn't exist. Please advise.

**Comment by koalyptus** [comment]
Previous refactoring work introduced a regression at instantiation when the HTML table contains only 1 row. This is now covered by tests. 
Starting from v0.4.31 when the HTML table contains 1 row, `TableFilter` will instantiate without javascript exception.
It will continue to throw an error when the HTML table has 0 rows.
Tell me how it goes.

**Comment by thenning** [comment]
Looks like the file in the dist folder isn't actually the tablefilter.js file or just looks drastically different. Let me know

**Comment by koalyptus** [comment]
Accidentally committed the unminified files in dist folder. Thanks for pointing this out, use v0.4.32 instead.
Cheers
