### ISSUE TITLE
sum, count, min, max functions?

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#39]
Does this TableFilter script support the same math functions as the previous Tablefilter Generator? (http://tablefilter.free.fr/)  I'd like to start using this version but I need to caluclate percentages (number of visible rows out of total fields in table which I think will need some code tweaking.  I thought it best to do that on a current version of the script.

**Comment by koalyptus** [comment]
Yes, it does. Check this example out:
http://koalyptus.github.io/TableFilter/data-types.html
