### ISSUE TITLE
Tables with Fixed Headers, but no grid layout?

### ISSUE THREAD

**Issue by shlimi** [koalyptus/TableFilter#399]
Thank you for this great tool!
Do you know how to get the header rows to stay at the top of the window when scrolling? Using the grid layout is no option. Any idea?

**Comment by koalyptus** [comment]
thanks @shlimi, there is no sticky headers feature at the moment. What you could do is implement your own CSS based solution for that, as an example: https://jsfiddle.net/dPixie/byB9d/3/

**Comment by shlimi** [comment]
Do you think it's possible to implement a CSS based solution that has sticky headers + sticky column filter + sticky status row?

**Comment by koalyptus** [comment]
I think it should be possible. You probably want the  thead element of your table to be sticky, as an example:
https://codepen.io/tjvantoll/pen/JEKIu
