### ISSUE TITLE
section total rows take up table filter

### ISSUE THREAD

**Issue by koboy55** [koalyptus/TableFilter#407]
Hi, I'm taking this sum sum1 sum2 total rows in the table at the top of the section, I can show you how to

I added the file: https://github.com/koboy55/kob

**Comment by koalyptus** [comment]
Please note this is `TableFilter`'s repository and you are using HTML Table Filter Generator (HTFG) in your example.
This is not the appropriate channel.

I advise you to consider upgrading to `TableFilter` as HTFG is no longer maintained.

Cheers
