### ISSUE TITLE
Compatibilty IE11

### ISSUE THREAD

**Issue by Ileouleyuki** [koalyptus/TableFilter#408]
Hye,
I begin to do crazy :)
I used tablefilter.js with no problem on Firefox 45.2.0 and i begin to make test on IE 11 and there is no filter.
I tried to go to sample page on [http://koalyptus.github.io/TableFilter/examples] with IE11 and the tablefilter works fine on Internet Explorer. 
I don't understand, i tried to change base_path or declaration and nothing work.
So its's not the configuration of my IE 11, it will be a bad declaration.
can you help me ?

I used the sample test.html in examples repo with modification for my server.

I have this error 

Global failure :Identificateur attendu 
Source:  http://myserver/tablefilter24022017/tablefilter.js:7 

Global failure : « TableFilter » est indéfini
Source:  http://myserver/test.html:142 

`
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>TableFilter basic test</title>
        <link rel="stylesheet" href="libs/qunit/qunit.css">
        <script src="libs/qunit/qunit.js"></script>
        <script src="libs/polyfill.js"></script>
    </head>
    <body>
        <table id="demo" cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <th>From</th>
                    <th>Destination</th>
                    <th>Road Distance (km)</th>
                    <th>By Air (hrs)</th>
                    <th>By Rail (hrs)</th>
                </tr>
                <tr>
                    <td><strong>Sydney</strong></td>
                    <td>Adelaide</td>
                    <td>1412</td>
                    <td>1.4</td>
                    <td>25.3</td>
                </tr>
                <tr>
                    <td><strong>Sydney</strong></td>
                    <td>Brisbane</td>
                    <td>982</td>
                    <td>1.5</td>
                    <td>16</td>
                </tr>
                <tr>
                    <td><strong>Sydney</strong></td>
                    <td>Canberra</td>
                    <td>286</td>
                    <td>.6</td>
                    <td>4.3</td>
                </tr>
                <tr>
                    <td><strong>Sydney</strong></td>
                    <td>Melbourne</td>
                    <td>872</td>
                    <td>1.1</td>
                    <td>10.5</td>
                </tr>
                <tr>
                    <td><strong>Adelaide</strong></td>
                    <td>Perth</td>
                    <td>2781</td>
                    <td>3.1</td>
                    <td>38</td>
                </tr>
                <tr>
                    <td><strong>Adelaide</strong></td>
                    <td>Alice Springs</td>
                    <td>1533</td>
                    <td>2</td>
                    <td>20.25</td>
                </tr>
                <tr>
                    <td><strong>Adelaide</strong></td>
                    <td>Brisbane</td>
                    <td>2045</td>
                    <td>2.15</td>
                    <td>40</td>
                </tr>
            </tbody>
        </table>

        <div style="width: 300px;">
        <table class="test">
            <tbody>
                <tr>
                    <th>From</th>
                    <th>Destination</th>
                    <th>Road Distance (km)</th>
                    <th>By Air (hrs)</th>
                    <th>By Rail (hrs)</th>
                </tr>
                <tr>
                    <td><strong>Sydney</strong></td>
                    <td>Adelaide</td>
                    <td>1412</td>
                    <td>1.4</td>
                    <td>25.3</td>
                </tr>
                <tr>
                    <td><strong>Sydney</strong></td>
                    <td>Brisbane</td>
                    <td>982</td>
                    <td>1.5</td>
                    <td>16</td>
                </tr>
                <tr>
                    <td><strong>Sydney</strong></td>
                    <td>Canberra</td>
                    <td>286</td>
                    <td>.6</td>
                    <td>4.3</td>
                </tr>
                <tr>
                    <td><strong>Sydney</strong></td>
                    <td>Melbourne</td>
                    <td>872</td>
                    <td>1.1</td>
                    <td>10.5</td>
                </tr>
                <tr>
                    <td><strong>Adelaide</strong></td>
                    <td>Perth</td>
                    <td>2781</td>
                    <td>3.1</td>
                    <td>38</td>
                </tr>
                <tr>
                    <td><strong>Adelaide</strong></td>
                    <td>Alice Springs</td>
                    <td>1533</td>
                    <td>2</td>
                    <td>20.25</td>
                </tr>
                <tr>
                    <td><strong>Adelaide</strong></td>
                    <td>Brisbane</td>
                    <td>2045</td>
                    <td>2.15</td>
                    <td>40</td>
                </tr>
            </tbody>
        </table>
        </div>

       <script src="../tablefilter24022017/tablefilter.js"></script>
       <script language="javascript" type="text/javascript">
		var filtersConfig = {
			base_path : '../tablefilter24022017/',
			stylesheet: '../tablefilter24022017/style/tablefilter.css'
		};

    var tf = new TableFilter('demo', filtersConfig);
    tf.init();
	   </script>

        <div id="qunit"></div>
        <div id="qunit-fixture"></div>
    </body>
</html>

`

**Comment by koalyptus** [comment]
Hi @Ileouleyuki, in the code you posted the HTML table doesn't have any id set... It should be
```<table id="demo" class="test">```
That's one thing.

The error `« TableFilter » est indéfini` seems to indicate `tablefilter.js` is not imported in your page as `TableFilter` global var is `undefined`. Make sure the js file is loaded by the browser, inspect your browser's network panel to check the HTTP status of that resource.

Cheers

**Comment by Ileouleyuki** [comment]
Thanks @koalyptus !!
Sorry for my first post, it is not really readable but there is an id=demo1 on the first table.
I used the developper tools on IE11 and IE 11 arrived to load the file tablefilter.js and find a mistake in it.

HTML1300: Une navigation s’est produite.
Fichier : test.html
HTML1122: Internet Explorer is running in Enterprise Mode emulating IE8.
SCRIPT1010: Identificateur attendu
Fichier : tablefilter.js, ligne : 7, colonne : 1440
SCRIPT5009: « TableFilter » est indéfini
Fichier : test.html, ligne : 81, colonne : 5

And at the line 7, column 1440, there is 
`
// getDefaultExport function for compatibility with non-harmony modules
 	__webpack_require__.n = function(module) {
 		var getter = module && module.__esModule ?
 			function getDefault() { return module['default']; } :
 			function getModuleExports() { return module; };
 		__webpack_require__.d(getter, 'a', getter);
 		return getter;
 	};
`

There is no problem in Firefox.

:(

**Comment by koalyptus** [comment]
I am afraid IE8 is not supported, not even sure it would work with polyfills though, give it a try, never know.

**Comment by tbc233** [comment]
Maybe this wil help someone someday:
Including polyfill.js did the trick for me. At least with IE11.

<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
