### ISSUE TITLE
Large Data Table

### ISSUE THREAD

**Issue by andoni34** [koalyptus/TableFilter#410]
Firstly, I want to say thank you very much for this incredible tool. I've gotten great use out of it so far and continue to learn new aspects every day when I use it. This has changed the way I build apps!

The issue I'm having is that I am dealing with a very large table (about 15,000 rows by 50 columns). I've set up my table exactly how I want it, it's functional and even talks with a SQL server. If I'm printing less than 2 or 3,000 rows, the wait time is acceptable. However, when I need to print 3,000 or more rows, sometimes the wait is very long (~30 seconds or more), and sometimes the app crashes entirely.

This is a problem, because without being able to display the entire table, some of the features like the sorting and filtering options on tops of columns aren't as useful as they could be.

Do you know if any kind of workaround for this? Your help is greatly appreciated.

Thank you very much in advance!

**Comment by koalyptus** [comment]
Thanks @andoni34, it probably takes time to render such a huge table anyway even without `TableFilter`.
You could try to use the `load_filters_on_demand` option to reduce parsing time, with this option selection filters are populated the first time they are used.

**Comment by koalyptus** [comment]
Probably not a good idea to send more than 3000 rows with 50 columns to the client with or without `TableFilter` in the first place. 
What do you mean by 
> it didn't seem to make the change I needed 
? 
I advise to have a look to this resource I posted years ago for HTML Table Filter Generator also valid for `TableFilter`.

**Comment by andoni34** [comment]
Got it -- I was browsing through that page and saw some good information in there. I apologize for my lack of knowledge, but I do not know much about JS. How would I build this into my R Shiny application? It looks like what code is given on that page has to do with the `tableProps` argument.

I found that if I reduce the number of rows to only a few, I'm able to print 15,000 rows in far less time, so a series of smaller applications could accomplish what my larger overarching application was supposed to accomplish. Thanks again very much for your help thus far.

**Comment by qianhuili** [comment]
@tsouchlarakis, I am experiencing a similar issue you might have had before and hope you can give me some guidance.
 I am pulling data from SQL server to HTML table and wanted to use the sort the data with the sorting feature. But it seems like the tool recognizes the rows from SQL as one row so the sorting doesn't work. Did you meet the same problem? If so, can you share your solutions with me?

**Comment by tsouchlarakis** [comment]
@qianhuili My previous issue was due to slow client render times of large data tables. It didn't have to do with sorting, and in my case I didn't have the problem that the "tool recognizes the rows from SQL as one row". This seems like a different issue.

Without understanding your use case fully, I might try adding an intermediate step in the process SQL query → R dataframe (make sure SQL query returns multiple rows in this dataframe) → send to client for display.
