### ISSUE TITLE
Adding Filters in html

### ISSUE THREAD

**Issue by EstherBoneta** [koalyptus/TableFilter#412]
Hi,

I am using http://tablefilter.free.fr/doc_ext.php to add filters in an html table.

Do you knmow if I could add a default value for one of the filters?

My table has 8 columns; i would like add a default filter in column 3 for example columns 3 = Africa to show only rows that contains this value in column 3.

Thanks!

Esther

**Comment by koalyptus** [comment]
Hi @EstherBoneta,
Please note you are referring to `HTML Table Filter Generator` which is no longer maintained and replaced by `TableFilter` which is actually this repo. I advise you to use `TableFilter` instead.
To answer your question:

- under HTML Table Filter Generator refer to this demo to set filter values:
http://tablefilter.free.fr/data-types.htm
check the `on_filters_loaded` callback

- under `TableFilter` you don't need to use the `on_filters_loaded` callback:
```
var tf = new TableFilter('table-id-here', yourConfigHere);
tf.init();
tf.setFilterValue(0, 'value here');
tf.filter();
```
Cheers

**Comment by balpha937** [comment]
Hi,

Just my experience on how can we set default values for various rows.
It is possible to add various filters one after the other:

`tf.setFilterValue(0, 'default value first row');`
`tf.setFilterValue(1, 'default value second row');`
`tf.setFilterValue(2, 'default value third row');`
