### ISSUE TITLE
Number formatting

### ISSUE THREAD

**Issue by vikaslamba** [koalyptus/TableFilter#413]
Quick question: Is there an easy way to allow me to specify custom number formats while filtering and sorting and for column operation outputs?

Specific problem: the numbers in one of my table columns always have the character "m" after them. Currently, I deal with this in filtering by defining a cell_parser that strips out this character from the end of the string...

However, this still leaves the issue of the output of the colOps (I have a min and max at the bottom) - is there an easy way to add this character "m" in the output of the colOps below as well? Currently, I have an ugly hack as a solution by listening to the event "after-column-operation" and manually changing the innerHTML of the output cells (basically append the character "m" to the existing string)...

I was thinking an easier method would be if somehow we could specify a prefix and a suffix for all columns with numbers. This could also help if the prefix was a currency character (e.g. "$") and suffix for the units (e.g. "m" or "th")... Also the key here is that the output of the colOps should also append these prefixes and suffixes...

I would make this change myself but can't get the npm build to work on my machine - when I run the npm run dist on my machine (after doing an npm install), I get a 1.6MB file as output (in the dist folder) which somehow does not look right (compared to the existing dist file)...

**Comment by koalyptus** [comment]
Hi @vikaslamba,
Nice to see your use of `TableFilter`.
To have a configuration setting for formatting the operation results in `colOps` would be a nice to have although in my opinion taking advantage of a hook whether a callback or event is not such a ugly hack solution. If you wish to share your change refer to the [guidelines for contributing](https://github.com/koalyptus/TableFilter/blob/master/CONTRIBUTING.md) to raise a PR.

After running `npm run dist` you should have a log similar to this 
![image](https://cloud.githubusercontent.com/assets/8214629/23787917/68a70b24-05c8-11e7-9412-1b2cea8b3404.png)

 It can take up to 10 mins or more depending on the machine to complete all the tasks.
Also ensure you don't have a concurrent `npm start` or `npm dev` running on another terminal as they may override the `dist` folder.

Cheers

**Comment by vikaslamba** [comment]
Thanks. I'll continue with my current methodology for now.

Also, will try to build the project again this week and see if I can add this specific functionality within the core source code itself.

**Comment by koalyptus** [comment]
@vikaslamba,
`ColOps` now features a `format_result` option that allows to format the operation results by using a `prefix` or `suffix` and many other options provided by per https://github.com/componitable/format-number module. By default, `ColOps` will match the column type in terms of decimal and thousands separators.
The `http://koalyptus.github.io/TableFilter/data-types.html` now uses this new option.
Cheers
