### ISSUE TITLE
Column Operations

### ISSUE THREAD

**Issue by vikaslamba** [koalyptus/TableFilter#414]
Is it possible to get the column operations in the same table? Perhaps under different tbody tags... Or perhaps there is a way to tell the Table Filter to exclude some rows from the bottom of the table for the filtering, sorting, pagination operations etc.

In the current system, colOps rows are defined in a different table and aligning their cell widths match those in the main table is a pain... Note that I use bootstrap layout and a responsive table - so don't know the column widths in advance.

I have already tried playing with the "rows_always_visible" and "exclude_row" configuration options (while keeping the column options in the same table at the bottom) but nothing works properly!

**Comment by koalyptus** [comment]
Yes it is possible, refer to this demo http://koalyptus.github.io/TableFilter/data-types.html to see how to use `rows_always_visible` option and `exclude_row` and `tot_row_index` options under `ColOps` extension. Also note the totals row is inside a `tfoot`.

**Comment by vikaslamba** [comment]
Thanks. The example you pointed to above solved my problem.

Finally figured out how to use the extensions...
