### ISSUE TITLE
Quartile Calculations

### ISSUE THREAD

**Issue by vikaslamba** [koalyptus/TableFilter#415]
Hi there

Quick question on the quartile calculations. I see that the quartiles calculated through the colOps extension are different from those calculated by Excel. The reason being that Excel uses a N-1 quartile function while the current colOps extension uses a standard quartile function (same as my Maths school teacher had taught me).

However, some of my users are asking to replicate the Excel quartile functionality. Any easy way to do so?

Best,
Vikas

**Comment by koalyptus** [comment]
Adding a calculation is not a big issue, if you are able to write the formula used by Excel in pseudo javascript you would make your users happy :) This document may help you: https://www.ischool.utexas.edu/~wyllys/IRLISMaterials/quartiles.pdf
Once you are confident your formula has same results as Excel give ia sign and I will make it available in ColOps extension.
Cheers
