### ISSUE TITLE
Translation or documentation if string translation is available

### ISSUE THREAD

**Issue by CPASimUSante** [koalyptus/TableFilter#426]
I'm using your great tool on a project, but my end user don't speak english. So it would be great if the (few) strings could be translated : 

- the "Row: 50"
- the "Clear filter" tooltip
- the "Clear" option in select box 
- the help in the "?"

Thank you. 
If this is already available i didn't find the documentation about it.

**Comment by koalyptus** [comment]
Hi @CPASimUSante,
You can modify all of those texts as per documentation:
- `rows_counter_text` option in https://github.com/koalyptus/TableFilter/wiki/1.07-Rows-counter
- `btn_reset_tooltip` option in https://github.com/koalyptus/TableFilter/wiki/1.09-Submit-and-reset-button
- `clear_filter_text` option in https://github.com/koalyptus/TableFilter/wiki/1.05-Drop-down-filter
- `help_instructions_btn_text` in https://github.com/koalyptus/TableFilter/wiki/1.13-Help-instructions

**Comment by CPASimUSante** [comment]
Sorry, i clearly didn't check enough :)
I searched for the word "translation" in you repo.

Thank you for this great plugin
