### ISSUE TITLE
Page loads with 2 search rows instead of just the 1

### ISSUE THREAD

**Issue by kyleabens** [koalyptus/TableFilter#427]
When I load my html page I'm getting 2 search rows above my table instead of just 1.  The first row filters no problem.  The second row does nothing and I'm not sure why it's being generated.  

**Sidenote:** My table is pulling from a database and I use flask to pull all the data into a table.

Let me know if you've had an issue like this before.

Thanks in advance!

**Comment by koalyptus** [comment]
I never saw that before on `TableFilter`, from memory I saw that on `HTML Table Filter Generator`, the previous generation of this library which is no longer maintained. Make sure you are using `TableFilter` and if it is the case please follow the reporting bugs template available [here](https://github.com/koalyptus/TableFilter/blob/master/CONTRIBUTING.md#reporting-bugs) to have an easy way for me to reproduce the issue.
Cheers
