### ISSUE TITLE
IE11 problem

### ISSUE THREAD

**Issue by txofox** [koalyptus/TableFilter#428]
I have some issues with TableFilter and IE11. In Chrome or Edge everything is working great. 
For IE11, I tried with <meta htpp-equiv="X-UA-Compatible" content="IE=9" /> and I get dropdown filter but when I try to pick something nothing happens. And sorting doesn't work too. 
In console I get this error: SCRIPT5009: 'Promise' in undefined. tablefilter.js (7,1166).

Can you help me somehow? 

Thank you!

**Comment by koalyptus** [comment]
@txofox I advise you to use a promise polyfill you could load conditionally if `window.Promise` does not exist. Make sure you load it before you import and instantiate `TableFilter`.
This is a webpack >= v2.0 related issue: dynamic requires (code splitting) implementation is now `Promise` based.
Below an quick example on how to dynamically import the polyfill in your page:
```javascript
<script>
  window.Promise || document.write('<script src="https://unpkg.com/es6-promise@3.2.1/dist/es6-promise.min.js"><\/script>');
</script>
```

**Comment by txofox** [comment]
Thank you, this worked perfectly!
