### ISSUE TITLE
Change grid layout bottom bar position

### ISSUE THREAD

**Issue by nicolotucci** [koalyptus/TableFilter#444]
Hi! Is there a way or property to set the Grid Layout bottom bar (the one with row counter and clear filter) in the top/head section?

**Comment by koalyptus** [comment]
Hi @nicolotucci,  you could use the `toolbar_target_id` property to generate the toolbar in a desired element as shown in this demo: http://koalyptus.github.io/TableFilter/external-toolbar.html
In your case, you would place the custom element at the top of the grid-layout table.
Cheers
