### ISSUE TITLE
Error "Promise is undefined" in IE11

### ISSUE THREAD

**Issue by mmaction** [koalyptus/TableFilter#447]
we've been using the tablefilter library for a while now. due to performance problems when filtering large tables (10'000 entries containing empty string values) i tried to update the "old" tablefilter library (v0.0.7).
the filtering issue is solved with release v0.4.40 but our pages are not displayed correctly anymore in IE11. The browser console complains with the following error:  'Promise' is undefined. tablefilter.js, Line: 7, Column: 1166. The status bar keeps displaying "Loading extensions...". We are using the sort and advancedGrid extensions. When i exclude the extensions in the tableFilter config part of the *.htm IE11 seems to be happy...
Firefox and other browsers are fine with release v04.40.
Also tested the current master version v05.9 but same problem here with IE11.
What can i do? Is there any workaround?

-----------
here is my configuration:

....

        /* Setup table filtering */
      	tf = new TableFilter('tblOptions', 
      	{            		
      		/* filters behaviour */
      		base_path: '../tablefilter/',
      		col_widths: [ "45px", "93px", "455px", "120px", "70px", null ],      
      		col_0: "none",
      		col_3: "select",
                col_5: "none",
      		filters_row_index: 1,	
      		auto_filter: true,
      		auto_filter_delay: 0,
      		remember_grid_values: true,
      		alternate_rows: true,
      		mark_active_columns: true,
      		watermark: "search...",
	      	on_after_refresh_counter: adjustCounter,	
      		clear_filter_text: "All",	 
      		grid_layout: true,
      		grid_height: '228px',	
      		grid_width: '778px',
      		status_bar: true,
      		rows_counter: true,	
      		rows_counter_text: 'Number of Entries: ',	
      		btn_reset: true,
      		help_instructions: false,
      
      		/* extensions*/     
    		extensions:
      		[
            	  {
            	          name: 'sort',
      			  types: ['Number', 'Number', 'String', 'String', 'String', 'none' ],	 
        	    },
      		   {
      			  name: 'advancedGrid',
       			  vendor_path: '../ezEditTable/',	
      			  on_after_selected_row: afterRowSelected,
       	                  on_selection_initialized: onSelectionInitialized,
      			  nb_rows_per_page: 12,			      			
      		    }	
            ],  
      
      	});        	     
      	tf.init();
...

**Comment by koalyptus** [comment]
Hi @mmaction, please refer to #428.
Cheers
