### ISSUE TITLE
Single_filter for not all columns ?

### ISSUE THREAD

**Issue by sinayou67** [koalyptus/TableFilter#454]
Hello,
 Is it  possible to use a checklist for 1 columns and  a single_filter for the rest of the columns ?

**Comment by koalyptus** [comment]
It's not possible at the moment, the `single_filter` option does not give you the possibility to exclude  columns from filtering. I tried for fun in this codepen:
http://codepen.io/koalyptus/pen/aWqqqP

A lot of tricks and hacks but still a confusing behaviour.

**Comment by sinayou67** [comment]
Ok thinks you it seems to work but unfortunately, the external filter took to much space on my web site. I will try something else maybe with another library.

**Comment by koalyptus** [comment]
Good luck
