### ISSUE TITLE
"input + select" combo filter requested

### ISSUE THREAD

**Issue by alamsha** [koalyptus/TableFilter#455]
ref:
http://koalyptus.github.io/TableFilter/auto-filter.html

In the above example, i can change the filter property to select and get a dropdown list. I would like to edit the selected item or type whatever i want as well in the filter. In short, i would like to have a "input + select" combo filter, something like this.

        col_0: 'select', 'input',
        col_1: 'select', 'input',
        col_2: 'select', 'input',
Is it possible?. BTW, i love TableFilter.
-------------------------

In case a "input + select" combo filter is not possible immediately, is it possible to have 2 seperate filter rows, one for "auto filter, filter as you type" and another row for "select" from drop down list ?.

I tried something like this but it works only for one row.

    var filtersConfig = {
        base_path: 'tablefilter/',
        auto_filter: true,
        auto_filter_delay: 1100, //milliseconds
        filters_row_index: 0,
        state: true,
        alternate_rows: true,
        rows_counter: true,
        btn_reset: true,
        status_bar: true,
        msg_filter: 'Filtering...'
    };
    var tf = new TableFilter('demo', filtersConfig);
    tf.init();

    var filtersConfig = {
        col_0: 'select',
        col_1: 'select',
        col_2: 'select',
        col_3: 'select',
        base_path: 'tablefilter/',
        auto_filter: true,
        auto_filter_delay: 1100, //milliseconds
        filters_row_index: 1,
        state: true,
        alternate_rows: true,
        rows_counter: true,
        btn_reset: true,
        status_bar: true,
        msg_filter: 'Filtering...'
    };

    var tf = new TableFilter('demo', filtersConfig);
    tf.init();

**Comment by koalyptus** [comment]
Hi @alamsha,
1. It is not possible to set two filter types for a column via configuration and I don't think it is a good idea. What you probably want is a typeahead filter type, something that completes your selection while you are typing. Not in the works anyway, but I guess you could build such a filter and use the TableFilter's API to filter the table accordingly.

2. Yes, you can add an additional filters row programmatically as per this codepen example:
http://codepen.io/koalyptus/pen/ybjYWZ

Cheers

**Comment by alamsha** [comment]
Hi Koalyptus

http://codepen.io/koalyptus/pen/ybjYWZ
Thanks for the support. The second filter row (input type) doesn't work. Something is missing.. pls look into that. Cheers.

**Comment by koalyptus** [comment]
Ah ok, all fillters in second row should work now.
Cheers
