### ISSUE TITLE
Popup filter & Grouped Headers doesn't working together

### ISSUE THREAD

**Issue by Nexpola** [koalyptus/TableFilter#460]
Hi,
like in issue #295, I'm still having troubles on v0.5.11
When i use "select" or "multiple" popup filters with grouped header tables, the heading row goes inside the dropdown menu. 

Could it be a bug or I'm doing something wrong?
This is the same kind of table I'm trying to build: https://jsfiddle.net/wLexc6pt/6/

Thank you!

**Comment by koalyptus** [comment]
I have found a regression that could be related to this issue. I will make a fix that should also fix the fiddles in #295.

**Comment by koalyptus** [comment]
Starting from `v0.5.18` the regression is fixed, https://jsfiddle.net/wLexc6pt/6/ fiddle now works as expected again and you should be able use popup filters with grouped headers.
Cheers

**Comment by Nexpola** [comment]
Great! 
Thank you very much!
