### ISSUE TITLE
Change request for Column visibility extension to work better in grid layout

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#465]
When using grid layout there are table col defines
eg (from http://koalyptus.github.io/TableFilter/grid-layout.html)
```
 <table id="demo" class="countries" style="table-layout: fixed; width: 930px;">
<col style="width: 150px;"><col style="width: 70px;">
<col style="width: 70px;">
<col style="width: 120px;">
<col style="width: 120px;">
<col style="width: 100px;">
<col style="width: 100px;">
<col style="width: 100px;">
<col style="width: 100px;">
    <tbody>...
```

When using Columns visibility extension hidden columns are marked with 
`display:none;` 
to make them disappear
but the `<col style="width: 100px;">` display property is not set to none at the same time.  This means that the columns don't automatically expand to fill the grid width leaving a blank section of the grid.

Can the show/hide columns code be tweaked to also change the display parameter for the `col` tags in the header table and content table so that the columns will expand to fit?

**Comment by koalyptus** [comment]
@cjohnsonuk, I don't think it is 'better' to have the visible columns fill the grid width, it is a possible behaviour but I wouldn't make it as the default one anyway when grid layout is on. If you look at the javascript datagrids components, you will see this is pretty much a common behaviour to keep the blank space left by a hidden column (eg https://www.ag-grid.com/javascript-grid-width-and-height/?framework=all#gsc.tab=0). This also helps user to easily understand there are hidden columns.

Setting the `col` element to `display` none is probably not enough with grid layout on, but you could leverage the ColsVisibility API, eg subscribe to the `column-hidden` event to recalculate the widths of the visible columns whenever a column is hidden. Same would apply when a column is displayed (`column-shown` event).

**Comment by cjohnsonuk** [comment]
We've had a go at this using the on-after-col-hidden, on-before-col-hidden, on_after-col-displayed, and on_before_col_displayed functions.  The only functions we can get to work for each of these is   on_before_col_hidden and on_before_col_displayed.  We've removed all other parameters from the TF definition in case there was a conflict and found that the grid_layout:true was preventing the on_after_col_hidden and on_after_col_displayed triggers from running.

We've run the same tests on your example pages by loading a similar example page from http://koalyptus.github.io/TableFilter/examples and then in the console performing a tf.destroy(), redefining tf using our parameters including the on_after_col_hidden and a tf.init() to start it up and it works fine for all functions UNLESS we use the on_after_col_xxx functions with Grid enabled.

 ```  
var tfConfig = {
        base_path: 'tablefilter/',
        paging: true,
        state: { types: ['cookie'] },
        alternate_rows: true,
        rows_counter: true,
        btn_reset: true,
        btn_reset_text: 'Clear',
        status_bar: true,
        col_1: 'select',
        col_2: 'select',
		grid_layout: true, 
        
        col_types: [
            'number', 'string', 'string',
            'formatted-number', 'formatted-number', 'string'
        ],

        /* columns visibility and sort extension */
        extensions: [{
              name: 'colsVisibility',
              at_start: [3, 5],
              text: 'Columns: ',
              enable_tick_all: true,
			  on_after_col_hidden: function(o) {console.log('afterh');},
            on_before_col_hidden: function(o) {console.log('beforeh');},
            on_after_col_displayed: function(o) {console.log('afterd');},
            on_before_col_displayed: function(o) {console.log('befored');}
          }, {
              name: 'sort'
        }]
    };
    var tf = new TableFilter('demo', tfConfig);
    tf.init();
```

**Comment by koalyptus** [comment]
There is still some legacy code from HTML Table Filter Generator overriding those two callbacks for some reason when `grid_layout` is on: 
https://github.com/koalyptus/TableFilter/blob/master/src/extensions/colsVisibility/colsVisibility.js#L280

What I am suggesting is to use the `column-hidden` and `column-shown` events instead: 
```javascript
var tfConfig = {
       base_path: 'tablefilter/',
       paging: true,
       state: { types: ['cookie'] },
       alternate_rows: true,
       rows_counter: true,
       btn_reset: true,
       btn_reset_text: 'Clear',
       status_bar: true,
       col_1: 'select',
       col_2: 'select',
       grid_layout: true, 
       
       col_types: [
           'number', 'string', 'string',
           'formatted-number', 'formatted-number', 'string'
       ],

       /* columns visibility and sort extension */
       extensions: [{
             name: 'colsVisibility',
             at_start: [3, 5],
             text: 'Columns: ',
             enable_tick_all: true
         }, {
             name: 'sort'
       }]
   };
   var tf = new TableFilter('demo', tfConfig);

   // subscribe to ColsVisibility 'column-shown' and 'column-hidden' events
   tf.emitter.on(['column-shown'], function(tf, colsVisibility, colIndex, hiddenCols) {
     console.log(tf, colsVisibility, colIndex, hiddenCols);
   });
   tf.emitter.on(['column-hidden'], function(tf, colsVisibility, colIndex, hiddenCols) {
     console.log(tf, colsVisibility, colIndex, hiddenCols);
   });

   // could be reduced to 
   //tf.emitter.on(['column-shown', 'column-hidden'], function(tf, colsVisibility, colIndex, hiddenCols) {
   //  console.log(tf, colsVisibility, colIndex, hiddenCols);
   //});

   tf.init();
```

I will try to sneak in a fix for the overriden callbacks in the next releases.

Cheers

**Comment by cjohnsonuk** [comment]
Thanks for this.  We'll revisit next week and try the alternatives suggested.
:-)

**Comment by koalyptus** [comment]
@cjohnsonuk I have just posted a codepen showing how to use the `column-shown` and `column-hidden` events to adjust the column widths: https://codepen.io/koalyptus/pen/yXQJRK
