### ISSUE TITLE
Grid layout Columns don't quite line up 

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#466]
in http://koalyptus.github.io/TableFilter/grid-layout.html
when scrolling all the way to the right the table content scrolls a little further than the table headers.  This appears to be just the width of the scroll bar.

IN teh demo with no vertical borders on the table elements its not that obvious but when using different styles with vertical borders the result is a table which some say isn't as pretty as it could be...

Is it possible to account for the width of the scroll bar so that the column boundaries remain aligned?  Maybe adding a padding-right to the header table to account for the width of the scroll bar?

**Comment by koalyptus** [comment]
Tx for pointing this out, should be possible, I will try to fix it in the next versions.

**Comment by koalyptus** [comment]
Starting from v0.5.22 this should be fixed.
Tell how it goes.
