### ISSUE TITLE
Paging length or results_per_page doesn't work?

### ISSUE THREAD

**Issue by TaylorTai** [koalyptus/TableFilter#467]
I followed http://koalyptus.github.io/TableFilter/paging.html to set results_per_page, but Records span wasn't shown. if i set the length like 50, the page was still shown default 10 lines. Any suggestion for solving this issue?

**Comment by koalyptus** [comment]
You probably just need to upgrade your local version to 0.5.21, as paging configuration options were rationalised starting from that version.

**Comment by TaylorTai** [comment]
Thanks, already fixed it.
