### ISSUE TITLE
Make search accent insensitive

### ISSUE THREAD

**Issue by BrunMartins** [koalyptus/TableFilter#476]
I, I have a little problem.

I'm using this as a phone list and accented names can't be searched if I write them without accents, thanks

**Comment by koalyptus** [comment]
Hi @BrunMartins,
Just set the 'ignore_diacritics' option to true, as per this example:
http://koalyptus.github.io/TableFilter/ignore-diacritics.html

Cheers

**Comment by BrunMartins** [comment]
Hey, thansk for geting back to me, I set that flag, but it still doesn't
work, mind you I might be doing something wrong:

var props = {
filters_row_index: 1,
sort: true,
themes_path: "TF_Themes/SkyBlue",
help_instructions: false,
filters_row_index:1,
remember_grid_values: true,
alternate_rows: true,
rows_counter: true,
rows_counter_text: "Linhas Visiveis: ",
btn_reset: true,
status_bar: true,
mark_active_columns: true,
col_3: "select",
col_4: "select",
display_all_text: "< Show all >",
ignore_diacritics: true,
btn_reset_html: "<input type=\'button\' value=\'Remover Filtros\'
class=\'reset\' text-align=\'left\' background=\'rgba(165, 150, 150, 0)
url(../img/btn_clear_filters.png) center right no-repeat !important\'>"
}
var tf = setFilterGrid("table",props);

           *Bruno Martins*
    *B&T Informática*
Em associação com Tiago Cardoso (tcardoso1995@gmail.com), e Bruno Rafael (
brunorafjesus@gmail.com)

Copyright @ 2014 B&T Informática

2017-07-05 12:28 GMT+01:00 koalyptus <notifications@github.com>:

**Comment by koalyptus** [comment]
Once you upgrade to TableFilter then it will work. You are using the HTML Table Filter Generator instead, which is a old plugin no longer maintained.

**Comment by BrunMartins** [comment]
Oh wow okay, any detailed steps on how to do that?

**Comment by koalyptus** [comment]
Just follow the README of the GitHub project here.

**Comment by BrunMartins** [comment]
Alright thanks
