### ISSUE TITLE
getTableData vs getFilteredData

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#48]
getFilteredData allows me to pass "true" as a parameter to include the header row

It would be nice if there was the same option for getTableData (please).  I did try it but it didn't appear to work on my test table.

getFilteredData returns an empty array if no filter has yet been applied since the page loaded (but will return a full table with header row if the filters are applied then all cleared).  This is fine, I've got some logic to pull the full table with getTableData()  but I need the header row too.

Thanks

**Comment by koalyptus** [comment]
``getTableData`` does not accept a parameter at the moment, I will add it to make it possible to include the header row values. I tagged this issue as enhancement and it should be part of the next version.

**Comment by koalyptus** [comment]
I just deployed version 0.0.7 which includes this enhancement.
Cheers

**Comment by cjohnsonuk** [comment]
Thanks, that's great! :-)  Just thought you'd like to know that feedback on
Tablefilter from our initial test users is really positive!

Chris

Chris Johnson

**Comment by koalyptus** [comment]
Cool, thanks for the feedback
