### ISSUE TITLE
Optimization in getColValues method

### ISSUE THREAD

**Issue by rimace** [koalyptus/TableFilter#481]
I think one loop in getColValues is not needed: https://github.com/koalyptus/TableFilter/blob/master/src/tablefilter.js#L2099
In my understanding, removing this loop (and it's content) in line 2099 and replace it with just 
```
let data = getContent(cell[colIndex]);
colValues.push(data);
```
should improve performance, as the browser doesn't need to check every column if it's the right column, and just get the data from the right column directly.
This could throw an error if the column doesn't exists though, but i think the user of the library is responsible for not trying to get data of non existing columns. If you think otherwise, you could check the existence once (out of the loop) and just return the empty colIndex array.

Greetings

**Comment by koalyptus** [comment]
Hi @rimace ,
Thanks for pointing this out, totally agree just an unnecessary loop, probably some legacy code that survived many refactors 😄 
If you want you can raise a PR, if you do so you can follow these steps:
https://github.com/koalyptus/TableFilter/blob/master/CONTRIBUTING.md#pull-requests
The above does not mention you also need to bump the package version in `package.json`.
If you don't raise a PR a will sneak this optimisation in in next release(s).
