### ISSUE TITLE
Pop-up filters incompatible with filters_row_index

### ISSUE THREAD

**Issue by noraj1337** [koalyptus/TableFilter#485]
[Pop-up filters](http://koalyptus.github.io/TableFilter/popup-filters.html) are incompatible with `filters_row_index: 1,`. Sounds normal to me but it can be good to write a *red warning* message in the documentation as a known limitation.

**Comment by koalyptus** [comment]
There is definitely room for enhancement, `TableFilter` should simply ignore that setting when pop-up filters is on. I will add a message to the demo and doco

**Comment by noraj1337** [comment]
Currently if `filters_row_index: 1,` is set and pop-up filters are used that broke the app, yes `filters_row_index` should be ignore if pop-up filters are used.

**Comment by koalyptus** [comment]
Starting from `v.0.5.32`, the `filters_row_index` configuration option should no longer break the app.
Cheers

**Comment by noraj1337** [comment]
@koalyptus Thanks 👍
