### ISSUE TITLE
Gblobal config for all tables

### ISSUE THREAD

**Issue by noraj1337** [koalyptus/TableFilter#486]
I have a html document with multiple different tables.

I wanted to know if it's possible to use a global config for all tables and a per table config for thing that change for each table.

I tried to include this global script at the end of my html file (`all_tables.js`):

```js
var filtersConfig = {
    base_path: 'vendor/js/TableFilter/dist/tablefilter/',
    alternate_rows: true,
    highlight_keywords: false,
    ignore_diacritics: true,
    no_results_message: true,
    responsive: false,
    auto_filter: true,
    auto_filter_delay: 0, //milliseconds
    rows_counter: true,
    btn_reset: true,
    status_bar: true,
    msg_filter: 'Filtering...',
    popup_filters: true,
    extensions: [{
        name: 'sort',
        sort_col_at_start: [0, false]
    }],
    enable_slc_reset_filter: true,
    help_instructions: true,
};
var tf = new TableFilter(document.querySelectorAll('table'), filtersConfig);
tf.init();
```

And a per table config under each table, for example:

```js
var filtersConfig = {
    base_path: 'vendor/js/TableFilter/dist/tablefilter/',
    col_0: 'input',
    col_1: 'select',
    col_2: 'checklist',
    col_3: 'none',
    col_types: [
        'string',
        'string',
        'string',
        'none',
    ],
};
var tf = new TableFilter(document.querySelector('#onetable'), filtersConfig);
tf.init();
```

Also I was asking myself if there is a way to put `base_path: 'vendor/js/TableFilter/dist/tablefilter/',` only once.

And if it is possible to make a global config for all tables it will be nice to write it in the DOC.

Edit : and if it's possible that means that [TF constructor](https://github.com/koalyptus/TableFilter/wiki/2.0-TableFilter-class) need to support not only a `table` DOM element but an array of `table` DOM element. For example something returned by `document.querySelectorAll` instead of `document.querySelector`.

**Comment by koalyptus** [comment]
okay different things here which in my opinion are not a concern of `TableFilter` :
1. config wise, you could create a `base` config for the commonalities and then create clone objects where you would just assign the values you want to change, eg:
```javascript
var baseConfig = { foo: 'bar' };
var myConfig = Object.assign({}, baseConfig);
myConfig.col_types = [...];
var otherConfig = Object.assign({}, baseConfig);
// etc
```
2. TableFilter applies to a single DOM table instance by design, so you can solve the `querySelectorAll` problem the other way around:
```javascript
[].forEach.call(document.querySelectorAll('table'), function(tbl) {
  new TableFilter(tbl, myConfig);
});
```

**Comment by rimace** [comment]
I hope i can give some ideas too. This is how i solved it: 
```javascript
function generateFilteredTable(selector, options = {}) {
	let table = new TableFilter(selector, $.extend({
		base_path: 'js/tablefilter/',
		help_instructions: false,
		// and more default options whatever you want
	}, options));

	return table;
}
```
I call this function when generating the filtered table and via the options parameter i can append options or overwrite my default ones. 
This example required jQuery though.  If you don't use it then $.extend needs to be replaced.

**Comment by noraj1337** [comment]
Thanks a lot @koalyptus and @rimace .
Here is what I did:

index.pug:

```pug
[...]
    body
        script(src='vendor/js/TableFilter/dist/tablefilter/tablefilter.js')
        script(src='vendor/js/jquery-3.2.1.min.js')
        script(src='js/tablefilter/base_config.js')
[...]
        table.table#table1
        script(src='js/tablefilter/table1.js')
        table.table#table2
        script(src='js/tablefilter/table2.js')
[...]
```

base_config.js:

```js
var baseConfig = {
    base_path: 'vendor/js/TableFilter/dist/tablefilter/',
    alternate_rows: true,
    highlight_keywords: false,
    ignore_diacritics: true,
    no_results_message: true,
    responsive: false,
    auto_filter: true,
    auto_filter_delay: 0, //milliseconds
    rows_counter: true,
    btn_reset: true,
    status_bar: true,
    msg_filter: 'Filtering...',
    popup_filters: true,
    extensions: [{
        name: 'sort',
        sort_col_at_start: [0, false]
    }],
    enable_slc_reset_filter: true,
    help_instructions: true,
};
```

table1.js:

```js
var filtersConfig = Object.assign({}, baseConfig);
jQuery.extend(filtersConfig, {
    col_0: 'input',
    col_1: 'select',
    col_2: 'checklist',
    col_3: 'none',
    col_types: [
        'string',
        'string',
        'string',
        'none',
    ],
});
var tf = new TableFilter(document.querySelector('#table1'), filtersConfig);
tf.init();
```

table2.js:

```js
var filtersConfig = Object.assign({}, baseConfig);
jQuery.extend(filtersConfig, {
// [...] other config here
});
var tf = new TableFilter(document.querySelector('#table2'), filtersConfig);
tf.init();
```

etc...

**Comment by noraj1337** [comment]
@koalyptus is that possible to mention something about that in the documentation for people who are newbie of javascript like me ?

**Comment by koalyptus** [comment]
@noraj1337 what do you mean exactly by `mention something`? 
The way you deal with configuration literal objects is not really within the scope of `TableFilter` documentation.
Also in my opinion the documentation is clear enough about the constructor accepting an id or a table DOM instance.
Cheers

**Comment by noraj1337** [comment]
@koalyptus You seems right. But when a javascript noob like me read the documentation, he see only examples for one table, he see nothing about a global config for multiple tables and a per table config.
You're right again, this is nott really the scope of TableFilter but it may help less advanced user and make TableFilter more user friendly.
The decision is up to you.

**Comment by koalyptus** [comment]
thanks @noraj1337 for your contribution, I wouldn't introduce a notion of global config for `TableFilter` as this has more to do with how developers intend to implement configuration objects with the possibilities offered by the javascript language. But as you suggest, I might add a demo featuring multiple filtered tables in the same page.

**Comment by noraj1337** [comment]
@koalyptus sounds great, thanks

**Comment by cjohnsonuk** [comment]
Not strictly javascript but: We use a PHP class to add Tablefilter to an existing table.  We use PHP to build our table as an object then if it needs TF we apply that method to it having set the properties (tf custom configuration options).  It makes sure we have a unique (on that page) table ID so we can add as many TF tables as we want to a single page.  The "global" TF properties are defined in the php class.  The "per table" or custom properties are defined in the DB along with the scripts to generate the table contents.  That way we can create new table definitions through a simple entry in the DB.  When a new TF version is released or the format of the configuration changes we change it once in the php class and all 160+ pages with 300+ tf tables are automatically using the new version and config.
