### ISSUE TITLE
returning a count based on the remaining data

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#49]
I have an example table of orders with a year column, a month column a status column and a customer column that I can filter on that I'd like to present stats for the data remaining in the table once its filtered.

eg if I filter by year I'd like to show a count of the visible orders and a percentage of the visible orders for each month (for the selected year) and a count and percent of the orders for each customer so we can see which months who placed how many orders.  I can see your column operations will do sum, max, min etc but not count, and from what I can see not count of each remaining visible distinct value. If it doesn't exist I'd like to try writing a function that given a column number returns an array of the unique visible values in the table and their count.   

My idea is to create an additional table with a row for each visible unique value in each column (like the list in the linked filters) with a percentage/ count next to each entry. 

Something along the lines of
pseudo code : 

foreach (item in linkedFiltersList){
  print (item, count(item), (count(item) / totalVisibleDataRows *100) + "%", (count(item) / totalDataRows *100 +"%"
}

That way the people looking at the orders can create any subset of the data using the filters and get the stats for that dataset rather than me have to write out new code for every combination they ask for....

Can this be done?  If you can give me a hint as to where in the code to start with
a) pulling a list of unique values that are visible in the filtered table (I think this is already done for the linked columns) 
b) where to look for the column operations in order to count unique in stead of sum/av min/ max etc

Thanks

**Comment by koalyptus** [comment]
I am not sure I completely understood your requirements, but you probably won't need to modify the ``colOps.js`` extension to do so. A way to achieve this, would be to hook on the ``on_after_filter`` callback, retrieve the data on a per column basis (``getFilteredDataCol(colIndex)``), make your count/calculations of unique items and inject the results into the other table.
Tell me if it makes sense.
Cheers

**Comment by cjohnsonuk** [comment]
OK. I'm going to use getColValues(<col>,false) to return all the data in each column then use a simple loop to count the number of each element.  However I also need the column header to label the stats that I generate.  Is there an easy way to get this using the table filter properties as there is with getFilteredData(<includeheaders:boolean>)?
If there's not an easier way tt would seem logical to extend getColValues to have an option to include the header row as well...  What do you think? 

Also : I've edited the wiki for the getValidRowsIndex() entry as in all the versions on tablefilter.js I have there is no reference to getValidRowsIndex only to getValidRows().  It appears to return the same data.  Hope you don't mind...

**Comment by cjohnsonuk** [comment]
I've sorted it : I use this to get the column headers : 
    myTableData = tf.getTableData(true);	// get all the table data
    myHeaderRow = myTableData[myHeadersRowIndex-1]; 
    myTitleData = myHeaderRow[1];
    myColumnHeader = myTitleData[<required Column number goes here>];
Not sure how robust it is but it works for me.

**Comment by koalyptus** [comment]
Hi,
I totally agree all data retrieval helpers should have the include headers option, it makes sense to me.
Thanks for updating the doco page, good catch!

A shorter way to grab a column's header text:
```
myColumnHeader = tf.getCellData(0, tf.getHeaderElement(0));
```
Just realising the ``getCellData`` method signature is weird, it shouldn't require the ``colIndex``, just a cell element:
```
myColumnHeader = tf.getCellData(tf.getHeaderElement(0));
```
I will also fix that in the next release.

**Comment by koalyptus** [comment]
In ``v0.0.10`` the ``getColValues`` and ``getFilteredDataCol`` helpers now accept a ``includeHeaders`` parameter. I also added a ``getHeadersText`` method, extracted after minor refactoring of ``getTableData`` and ``getFilteredData`` methods.
