### ISSUE TITLE
Using Grid layout, auto filtering on rightmost columns scrolls to left on no results

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#490]
When adding text to a filter that is to the right of a scrolling grid if the filter returns no data then the grid scrolls back to the left, "hiding" the filter box you're typing in.

Eg on this example : 
http://koalyptus.github.io/TableFilter/grid-layout.html

in console run this : 
```
tf.destroy();
var filtersConfig = {
        base_path: 'tablefilter/',
        grid_layout: true,
        alternate_rows: true, auto_filter: true,
        auto_filter_delay: 1100,
        no_results_message : {content:'There are no records matching the search criteria you have selected.' }, 
        btn_reset: true,
        rows_counter: true,
        loader: true,
        status_bar: true,
        col_1: 'select',
        col_2: 'select',
        col_widths: [
            "150px", "70px", "70px",
            "120px", "120px", "100px",
            "100px", "100px", "100px"
        ],
        col_types: [
            'string', 'string', 'number',
            'number', 'number', 'number',
            'number', 'number', 'number'
        ],
        extensions:[{
            name: 'sort'
        }]
    };
    var tf = new TableFilter('demo', filtersConfig);
    tf.init();
```
Scroll to the right most column "ci"
enter 1 in the filter box, wait
it filters and displays matches without scrolling right
press 1 again (so filter is 11) , wait
it filters and displays matches without scrolling right
press 1 again (so filter is 111) , wait
it filters, finds no matching rows, scrolls left, removes the horizontal scroll bar so you can't scroll back right again to find the filter box and displays the "no matching records" text 
press `<backspace>` (so filter is 11), wait
as that filter was active/had focus it filters again, finds results and lets you scroll.  However it automatically scrolls the filter row back right to show the column headers but doesn't scroll the table body to the right. 
IF you click elsewhere the filter loses focus and you can't get back to it again (unless you clear ALL filters).

We've got a number of reports that have dates in the columns to the right of our grids and are off screen by default.  Users are typing in filters on the visible columns, scrolling right and typing in  partial date ranges (eg ">2000"), pausing, then losing the ability to see the filter box to update or amend the date.  

Is it possible to prevent the "scroll left on no data" ?

(tested in google chrome v59 and Edge. (in edge you still get the horizontal scroll bar so you can scroll back))

**Comment by koalyptus** [comment]
Tx @cjohnsonuk for your detailed description. 
Starting from `v0.5.34`, users will be able to scroll back to the overflowing columns as the 'no matching records' message will preserve the horizontal scrollbar. This fix will not prevent the headers to be out of sync with the content when using the `backspace` key but since the scrollbar is available there will be less need to workaround that situation by using the keyboard anyway.

**Comment by cjohnsonuk** [comment]
Thanks, I'll give it a try when I get back to work.  Why does it scroll left to display the message? I know some of our users will not grasp the concept of scrolling back again...

**Comment by koalyptus** [comment]
Probably browser's default behaviour... `TableFilter` is not performing any programmatic scrolling anyway.
