### ISSUE TITLE
Wrong style when using column calculation and bootstrap 4

### ISSUE THREAD

**Issue by rimace** [koalyptus/TableFilter#502]
When using bootstrap 4 (beta 1) and TableFIlter's Column calculations feature, the calculated value is on the bottom of the table, as the caption tag (which the value is in) is styled by bootstrap 4 with "caption-side: bottom;".

**Reproduction steps:**

1. Try to use bootstrap 4 with this example https://koalyptus.github.io/TableFilter/column-calculations.html

**Expected behavior:**

The caption tag should be on the top of the table.

**Observed behavior:**

The caption tag is is on the bottom of the table.

**Screenshots and GIFs**

**TableFilter version:** v0.5.39
**Browser and version:** Firefox 55.0
**OS and version:** KDE Neon 5.10

**Additional information:**

* Problem started happening recently, didn't happen in an older version of 
TableFilter: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by rimace** [comment]
I just thought about this again. Maybe it's not a bug, because TableFilter and Bootstrap do not explicit support each other. Also you can easily work around it by overwriting the caption-side property on the caption tag.
So see this more as an information than a bug and close it if you think this should be fine.

**Comment by koalyptus** [comment]
tx @rimace for the heads-up, I haven't tried to integrate with bootstrap 4 yet. Just in case pointing you to a demo showing how to integrate with older versions of bootstrap:
http://koalyptus.github.io/TableFilter/using-bootstrap.html
