### ISSUE TITLE
implementing SORT after Filter

### ISSUE THREAD

**Issue by FilterSort** [koalyptus/TableFilter#503]
Hello,

Novice web programmer here.  I've implemented the filter portion, but have been unable to implement the SORT.  Looking at the downloaded zip file, it seems like I just need to copy those files to my site, and reference the JS files in my web page.  But when I click on the cell headings, they do not sort.  Any thoughts?

Thanks!

**Comment by koalyptus** [comment]
Hi @FilterSort,
You just need to place the content of the `[dist](https://github.com/koalyptus/TableFilter/tree/master/dist)` folder at desired location of your website. There is a `starter.html` file in it which implements column sorting, I advise you to have a look at that file to get familiar with the configuration options.
Also check the demos out: http://koalyptus.github.io/TableFilter/examples.html
Cheers

**Comment by FilterSort** [comment]
Thanks koalyptus for your prompt reply!  

Unfortunately, am still having issues.  I've attached my file.  This file is in my directory "httpdocs" at the web hosting company, and within that "httpdocs" directory, I've created a "tablefilter" directory, where I've put all the contents of the following link:  "https://github.com/koalyptus/TableFilter/tree/master/dist/tablefilter"

Any thoughts on what I'm doing wrong?

Thanks

[TestTableLearn.php.zip](https://github.com/koalyptus/TableFilter/files/1257923/TestTableLearn.php.zip)

**Comment by FilterSort** [comment]
I think I solved the issue by implementing another sorting function (that I modified to account for the extra filter row in HTML table that your filtering functionality adds), so hopefully I'm good, thanks for replying.

Only thing at this point I'm trying to figure out is how to have the reset button left-justified rather then right, will look thru the docs.

Thanks!
