### ISSUE TITLE
Linked filters column 0 not working?

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#506]
In the example at http://koalyptus.github.io/TableFilter/linked-filters.html clicking an option in column 2  (Continent region) affects the entries in column 3 (country territory) and vice versa. 

Our data page has data in column 1 and 2 and its paginated too.

If you take the example for pagination :  http://koalyptus.github.io/TableFilter/paging.html

and inspect it and in the console run this to add linked filters to an example table with data in column 1:

 ```
  tf.destroy();
  var filtersConfig = {
        base_path: 'tablefilter/',
        linked_filters:true,
        paging: {
          results_per_page: ['Records: ', [10, 25, 50, 100]]
        },
        state: {
          types: ['local_storage'],
          filters: true,
          page_number: true,
          page_length: true,
          sort: true
        },
        alternate_rows: true,
        btn_reset: true,
        rows_counter: true,
        loader: {
          html: '<div id="lblMsg"></div>',
          css_class: 'myLoader'
        },
        status_bar: {
          target_id: 'lblMsg',
          css_class: 'myStatus'
        },
        col_0: 'multiple',
        col_1: 'multiple',
        col_2: 'multiple',
        col_types: [
            'string', 'string', 'number',
            'number', 'number', 'number',
            'number', 'number', 'number'
        ],
        extensions:[{
            name: 'sort'
        }]
    };
    var tf = new TableFilter('demo', filtersConfig);
    tf.init();
```

then you should see that choosing an option in column 1 does not affect the entries in the column 2 filter as you would expect from the example page but selecting an option in column 2 does affect those in column 1

Is this expected?  I'm sure this didn't used to work this way as our "stats" table with data in columns 1 and 2 used to work well...

Could this be a zero index column issue?

**Comment by koalyptus** [comment]
@cjohnsonuk thanks for pointing this out, if you test same demo with same config but without paging, it will work, I will investigate further. I confirm there is an difference in the filters behaviour when paging is on.

**Comment by koalyptus** [comment]
accidentally closed this issue.

**Comment by cjohnsonuk** [comment]
We'd found the same re paging.   I forgot to mention it. We're implementing a toggle for paging.

**Comment by koalyptus** [comment]
I have fix in the pipeline that will make linked filters behave in the same way with or without paging.

**Comment by koalyptus** [comment]
@cjohnsonuk please try v`0.5.41` and tell me how it goes.
