### ISSUE TITLE
Toggle Grid Layout?

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#509]
Not sure if this is even possible: 
On this page http://koalyptus.github.io/TableFilter/toggle-features.html
We added 
```
<div class="navbar-form navbar-left">
          <label for="chxGrid">Grid:</label>
          <input id="chxGrid" type="checkbox" checked="" class="form-control" onclick="toggleGrid(event);">
      </div>
```
to the html within <div class="navbar navbar-default"> through the console in Chrome

and then ran 
```
function toggleGrid(evt){
        var chx = evt.target;
        // Get grid layout feature instance
        var feature = tf.feature('gridLayout');

        if(chx.checked){
            tf.gridLayout = true;
            feature.reset();
        } else {
            tf.gridLayout = false;
            feature.destroy();
        }
    }
tf.destroy();
var tf = new TableFilter(
        document.querySelector('.countries-tiny'),
        {
            base_path: 'tablefilter/',
            alternate_rows: true,
            rows_counter: true,
            paging: true,
// added grid_layout    
grid_layout: true,
            col_widths: [
                '120px','120px','120px',
                '120px','120px','120px',
                '120px','120px','120px'
            ],
            on_filters_loaded: function(tf){
                // hide the filters row
                tf.dom().rows[tf.getFiltersRowIndex()].style.display = 'none';
            }
        }
    );
    tf.init();
```
In our browser the table reappears with a different theme (looks like skyblue).  The first three checkboxes continue to act as you would expect, toggling the features.  However the Grid toggle removes the page controls.  We're not sure if this is an issue with Grid Layout or if we're just not toggling it right.

**Comment by koalyptus** [comment]
@cjohnsonuk  yes it is possible, I have updated the http://koalyptus.github.io/TableFilter/toggle-features.html to show how to toggle grid-layout, as it is a special case.
I confirm the default color for the grid-layout is a light blue which is not the skyblue theme.
I understand it is a bit confusing, it should match the default theme.
