### ISSUE TITLE
Display table in full width when responsive is enabled

### ISSUE THREAD

**Issue by MathieuThiry** [koalyptus/TableFilter#511]
First thing first, thanks for your work, TableFilter is amazing!

Maybe I didn't notice in the docs but when responsive table is enabled it added "display: block;" and the result is that the table didn't take the full width of his container.

For now I use a bad hack to set my table taking full of the width available.

	$(window).resize(function() {

		var containerWidth = $('.containerWidth').width();
		var tableWidth = $('#tablefilter thead').width();

		if (containerWidth > tableWidth) {
			$('#tablefilter').css({'display': 'table'});
		} else {
			$('#tablefilter').css({'display': 'block'});
		}
	}).trigger('resize');

That would be great to have a better solution than mine!

Thanks again anyway!

What it does now:
![before](https://user-images.githubusercontent.com/8198643/30389503-4c780e02-98b3-11e7-8788-f9b571c9c59b.png)

What i'm trying to achieve:
![after](https://user-images.githubusercontent.com/8198643/30389573-80be58e2-98b3-11e7-91c0-00b51b1be700.png)

**Comment by koalyptus** [comment]
Tx @MathieuThiry,
let me point you to this demo if you haven't checked it out yet:
http://koalyptus.github.io/TableFilter/responsive.html
The table takes all the available space of the container and will display a horizontal scroll with small view ports.

From your screenshots I can tell the styling is different or missing, please describe your changes.
Have you tried to simply apply a 100% width to your table?
Bty, what TableFilter version are you using?

**Comment by MathieuThiry** [comment]
Thanks for your reply @koalyptus,

I use the last version: "0.5.40"

And this is my configuration:


    base_path: '/vendor/tablefilter/',
    paging: {
        length: 15,
        results_per_page: ['Résultats par page : ', [15, 20]]
    },
    rows_counter: {
        text: 'Nombre de lignes : '
    },
    help_instructions: false,
    state: {
        types: ['local_storage'],
        filters: true,
        page_number: true,
        page_length: true,
        sort: true
    },
    responsive: true,
    alternate_rows: true, 
    highlight_keywords: true,
    no_results_message: {
        content: '<div class="alert alert-danger">Aucun résultat</div>'
    },
    display_all_text: ' ',
    extensions: [{ 
        name: 'sort',
    }], 
    col_0: 'input',
    col_types: [
        'string',
    ],
    //bootstrap
    filters_cell_tag: 'th',
    themes: [{
        name: 'transparent'
    }]

As you can see i use Bootstrap styles, and by default Bootstrap set width 100% on table.

On your example i think it takes full width because there's enough columns to fill all the container width.

In my case i don't always have enough colums. That's why i'd like to set width 100%. And this is by default on Bootstrap but when responsive is enabled in TableFilter, this css class is added: 

    table.TF.resp {
        display: block;
    }

I can't override directly this css class because it is needed for small view ports. But in large view, tables won't take 100% width of his container parent anymore.

You know what i mean ?

I don't know if this is possible but it would be great to have an option to change that if we want to! :)

**Comment by koalyptus** [comment]
Tx for providing more context, makes sense in your use case. However, not convinced it is worth adding a configuration setting to satisfy this scenario, that is, when responsive mode is on make the columns become fluid under some arbitrary conditions (the columns do not fill the container element for example).
It seems to me this is a good example of creating a custom behaviour by leveraging the available APIs, I have posted this codepen to give a rough idea: https://codepen.io/koalyptus/pen/KXpjjB
The conditions under which the columns should become fluid would be similar to the logic of your `resize` function.

**Comment by MathieuThiry** [comment]
Yeah, you're right after all. Thanks for you new idea, that'll help me a lot! :)
