### ISSUE TITLE
Filter by an input (button or checkbox) outside from the table

### ISSUE THREAD

**Issue by david13013** [koalyptus/TableFilter#515]
Hi Koalyptus,

First I would like to thank you for your amazing work. TableFilter is very easy to implement for a non-expert as I am.

I got an issue with my current project. I would like to add buttons or checkboxes to fill in a specific filter input in the TableFilter.

In fact, my table contents in some cells more than one information. For example, in a column, I have : 
- a cell with : Text1, Text2
- a cell with : Text2
- a cell with : Text1, Text 3

So I can not use the default filters of TableFilter (input, checkbox, select...) to filter with one or more occurences.

To resolve my issue, I thought to add buttons : Text1, Text 2, Text 3. When I click on one of these buttons, the text is put directly on the input of the TableFilter. Exemple, if I click on the Button Text 1, it will write Text1 in the input TableFilter. It could be interesting to be able to click on the Button Text1 and then on Text2 to get both on the TableFilter input (Text1, Text2). The must have would be to get a multiple checkbox, rather than buttons, which it implements the texts directly in the TableFilter input.

If you have any idea of HTML/JS codes to implement this, I will be thankful.

Thank for your help.

Kind regards,

David

**Comment by koalyptus** [comment]
Thanks @david13013, I have posted this codepen that should implement the behaviour you described above: https://codepen.io/koalyptus/pen/qPjLdB

Let me know how it goes,
Cheers

**Comment by david13013** [comment]
Hi Koalyptus,

Thank you for your help. I have one more question. Your script works with a OR logic. Is it possible to make it work with a AND logic ? I mean when I click on Text1 and Text2, only cells with Text1 and Text2 will appear.

Kind regards,

David

**Comment by koalyptus** [comment]
Use && operator instead.
