### ISSUE TITLE
Footer is filtered & paginated too

### ISSUE THREAD

**Issue by shekharsom** [koalyptus/TableFilter#519]
When creating a table with a footer (tfoot), the footer row has the "tr" tag to it. This is resulting into an unexpected behaviour - Footer is getting paginated and filtered.

Probably the tag should be "tbody tr" instead of just "tr".

**Comment by koalyptus** [comment]
Hi @shekharsom,
it is a known issue not addressed yet. As a workaround, you can use the `rows_always_visible` option to excluded the desired row(s) from filtering and for pagination you will need to validate the rows every time a page is collected for pagination, this is what I mean:
https://codepen.io/koalyptus/pen/dVadqY

Unfortunate naming, `exclude_rows` would be better, that property will be renamed at a certain point.
Cheers

**Comment by shekharsom** [comment]
Thanks. That works. Hope this gets added as a standard feature.

**Comment by koalyptus** [comment]
@shekharsom starting from `v0.6.0` rows in the `tfoot` section will be disregarded from `TableFilter` operations such us filtering, paging, rows counting etc. You will no longer need to use the workaround above.
Cheers

**Comment by shekharsom** [comment]
Where do i get the v0.6.0? I don't have the facility to compile. The last release is 0.4.40.

**Comment by koalyptus** [comment]
fork/download master or get it from npm: https://www.npmjs.com/package/tablefilter
