### ISSUE TITLE
Extend alphabet sorting

### ISSUE THREAD

**Issue by averebazmadar** [koalyptus/TableFilter#524]
Please add Hungarian alphabet sorting capabilities. We have some spec characters witch the table can't handle.

Order: A Á B C D E É F G H I Í J K L M N O Ó Ö Ő P Q R S T U Ú Ü Ű V W X Y Z

https://en.wikipedia.org/wiki/Hungarian_alphabet

Thank you and have a great day :)

**Comment by koalyptus** [comment]
Tx @averebazmadar,
Please be aware the sorting capability is flexible enough to allow the implementation of custom sorters for desired columns, have a look to this demo:
http://koalyptus.github.io/TableFilter/sort-custom-type.html

In your case the custom sorter function would sort the terms based on the order you provided above, may be worth checking this stackoverflow [thread](https://stackoverflow.com/questions/10951167/sorting-in-javascript-with-special-characters) to have an idea.

Cheers
