### ISSUE TITLE
Sorting date with eu format not working

### ISSUE THREAD

**Issue by TomasZmuda** [koalyptus/TableFilter#527]
Hi, 

I have issue with date sorting, when there is dots. I specified the format in js, but, it's still sorting by first number in date. As you can see in Finish date column. What I'm doing wrong? Thank you!

Config code: 
`var tfConfig = {
        base_path: basePath,
        col_3: 'checklist',
        col_5: 'checklist',
        col_7: 'checklist',
        col_8: 'none',
        col_types: [
            'number',
            {type: 'date', format: ['{dd}.{mm}.{yyyy}']},
            'string',
            'string',
            'string',
            'string',
            'string',
            {type: 'date', format: ['{dd}.{mm}.{yyyy}']},
            'string',
            'none'
        ],`
![image](https://user-images.githubusercontent.com/17382905/32367694-4a034efa-c083-11e7-997a-e524d7fd1591.png)

**Comment by koalyptus** [comment]
Hi @TomasZmuda ,
Please note in your format, month should read `MM` and not `mm` which means 2-digit minute in [LDML tokens](https://sugarjs.com/dates/).
Refer to this codepen https://codepen.io/koalyptus/pen/vWGgbg to see a working example.

Cheers

**Comment by TomasZmuda** [comment]
Thank you very much for help!. Tomas.

**Comment by cgpro** [comment]
Otherwise, you'll get some error ;-)
`TypeError: Cannot read properties of undefined (reading 'join')`
