### ISSUE TITLE
rowspan filter table

### ISSUE THREAD

**Issue by XianxianKong** [koalyptus/TableFilter#529]
Hi,
 does it support rowspan filterable? or how can i do it?
like this. Thanks,i really need it..
this image is showing i put a new table into second cell but it doesnt work ,even the first cell
<img width="451" alt="filter" src="https://user-images.githubusercontent.com/26730292/32634122-00ce9b86-c60f-11e7-9460-bebfb433e2c6.png">

this image is using rowspan,but still wrong cause after select campus empty second cell is shown,

<img width="960" alt="filter2" src="https://user-images.githubusercontent.com/26730292/32634365-2e47debe-c610-11e7-9cf6-e3e3977ab1e6.png">

like this.
<img width="501" alt="filter3" src="https://user-images.githubusercontent.com/26730292/32634439-86ffea4c-c610-11e7-80b1-aca8f2597884.png">

**Comment by koalyptus** [comment]
Hi @XianxianKong ,
TableFilter does not support cellspan/rowspan, it simply skips the rows with an uneven number of cells.
The inconsistent behaviour above is not surprising. What we could do, is to add an option that lets the filtering logic parse any number of cells, however not sure about the result.
Cheers

**Comment by koalyptus** [comment]
After investigation, decided to not support colspans/rowspans as it is not a trivial change. I advise to use bullet point or a nested table inside a cell.
Cheers
