### ISSUE TITLE
'No results' message when table with just one row

### ISSUE THREAD

**Issue by enrico28** [koalyptus/TableFilter#531]
Hi there,
when the HTML table contains only 1 row I get the message 'No results'

**TableFilter version:** v0.6.2
**Browser and version:** IE11 and Chrome Version 60.0.3112.78
**OS and version:** Windows 7 Enterprise

* Problem started happening recently, didn't happen in an older version of 
TableFilter: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by enrico28** [comment]
Hi,
some other details:

The Property no_results_message is enabled 
The problem didn't happen in TableFilter version v0.4.32

Thanks
Enrico

**Comment by koalyptus** [comment]
Hi @enrico28,
Currently in a remote location on holidays with occasional internet access. Could you please provide a working example reproducing the issue, cheers

**Comment by koalyptus** [comment]
Hi @enrico28,
Currently in a remote location on holidays with occasional internet access. Could you please provide a working example reproducing the issue, cheers

**Comment by koalyptus** [comment]
Hi @enrico28,
Currently in a remote location on holidays with occasional internet access. Could you please provide a working example reproducing the issue, cheers

**Comment by enrico28** [comment]
A very simple example:
--------------------------------------------------------------------------------------------------------------
<!DOCTYPE html>
<html>
<head>
<title>My title</title>

<link rel="stylesheet" type="text/css" href="path_to/dist/tablefilter/style/tablefilter.css" />
<script type="text/javascript" src="path_to/node_modules/jquery-1.12.4.min.js"></script>
<script type="text/javascript" src="path_to/node_modules/es6-promise.min.js"></script>
<script type="text/javascript" src="path_to/node_modules/tablefilter/dist/tablefilter/tablefilter.js"></script>

</head>
<body>
<br />
<table border="0" id="su-table">
<thead><tr><th>Country</th><th>ISO</th></tr></thead>
<tbody><tr><td>Benin</td><td>BEN</td></tr></tbody>
</table>

<script>
var tfConfig = {
    base_path: 'path/to/my/scripts/tablefilter/',
    grid: true,
    filters_row_index: 0,
    btn_reset: true,
    rows_counter: {
        text: 'Data Rows: '
    },
    status_bar: true,
    col_types: [
        'string', 'string'
    ],
    enable_default_theme: true,
    popup_filters: {
        adjust_to_container: false
    },
    no_results_message: true,
    state: {
       types: ['cookie'],
       filters: true
    },
};
var tf = new TableFilter('su-table', 1, tfConfig);
tf.init();
</script>

</body>
</html>
--------------------------------------------------------------------------------------------------------------

With this example I get the message 'No results'.

If you either change the id su-table to something else or don't set the Property state,
you will not get the message 'No results'.
If you add a second row to the table, you will not get the message 'No results'.

Thank you and have a nice day

**Comment by enrico28** [comment]
[tf2.txt](https://github.com/koalyptus/TableFilter/files/1506028/tf2.txt)

This example has a table with enough columns to allow the reset button to appear.
When you press the reset button you get the message 'No results'. even though the
table has one row

Thank you and have a nice day

**Comment by koalyptus** [comment]
@enrico28 I confirm there is a regression due to refactoring work done recently and also to missing unit tests when there is a unique row. I will publish a fix as soon as I come back from holidays in the next days and have a proper internet connection.
Cheers

**Comment by koalyptus** [comment]
Starting from v.0.6.3, this regression should be fixed. Refer to this zip [issue531-enrico28.zip](https://github.com/koalyptus/TableFilter/files/1516450/issue531-enrico28.zip) containing your examples.
Cheers

**Comment by enrico28** [comment]
Thanks a lot!
Enrico
