### ISSUE TITLE
Consistency problems with the date filter

### ISSUE THREAD

**Issue by CPASimUSante** [koalyptus/TableFilter#532]
A fiddle  : https://jsfiddle.net/xko44uLp/

My set :
```
1 : 05/06/2017
2 : 05/06/2017
3 : 06/05/2017
4 : 06/05/2017
5 : 05/08/2017
```

Several things are weird  for the date column filter :

1. If i enter
0 or 05 or 05/ or 05/0 or 05/06/ 05/06/2 or 05/06/20 or 05/06/201 : i have no result => is there a default number of characters to be entered ? is there a way to have results for a partial match ?

2. But if i enter also the partial match : 
05/06 or 05-06 : i have results for id 1 and 2 ! 

=> why these pattern match and not the previous 
=> is there a way to prevent 05-06 or 05-06-2017 to give result : to blacklist the dash for date and use only the / ? 
I've tried `{ type: 'date', format: '{dd}/{MM}/{yyyy}' } ` but it doesn't change anything, with or without locale set.

I use tablefilter 0.5.28 in prod, but the fiddle is with the latest version

**Comment by koalyptus** [comment]
By default a filter of a date type column expects a string that can be converted to a javascript Date object. If you want to perform a partial string match on a date column, use the `*` operator:
- *0 
- *05 
- *05/ 
- *05/0
- *05/06/ 
- *05/06/2 
- *05/06/20 
- *05/06/201

Cheers

**Comment by CPASimUSante** [comment]
ok for the first part of the question : conversion in js object is done in the background, but 

- why 05/06 or 05-06 (without *)  returns results ?
- and how can i enforce the use of / instead of - ? I've read [the wiki about sort](https://github.com/koalyptus/TableFilter/wiki/3.1-Sort) but addding { type: 'date', format: '{dd}/{MM}/{yyyy}' } for instance doesn't do the trick.

Thank you

**Comment by koalyptus** [comment]
1. Simply because coincidentally sugarjs date library manages to create a date with the 05/06 or 05-06 string (https://sugarjs.com/dates/#/Parsing)
2. what do you mean? are you talking about sorting?

**Comment by CPASimUSante** [comment]
1 - ok, so i will have to check how to prevent/override this behavior
2 - in that page, you have the property types for dates, and i tried to set it to` { type: 'date', locale: 'fr', format: ['{dd}/{MM}/{yyyy}'] }` but i still have result for 05-06-2017 and not only for 05/06/2017

**Comment by koalyptus** [comment]
Before going down that path, I suggest to explore other options from easy to hard:
1. it feels like you want a date type for sorting the date column and string type for filtering, so you could define the date type for sorting and a string type for filtering:  https://jsfiddle.net/koalyptus/cb7dgzp1/
2. leverage the filtering hooks to use the `*` operator by prepending it at the beginning of filtering and removing it at the end: https://jsfiddle.net/koalyptus/747g85ga/  
3. apply a mask to the filter to enforce valid user inputs, something like https://www.npmjs.com/package/inputmask
4. integrate a date picker UI component writing user selection into the input filter generated by TableFilter

**Comment by CPASimUSante** [comment]
Thank you very much for the time you spend on this.
I wasn't even looking for a given solution, i was to search for it, but your first two solutions are what i need, the second one being even more user friendly, even though it prevent for further use of the * operator by the user, since it's already set in the background.

Great solution anyways.
