### ISSUE TITLE
Wiki: toolbar_position Properrty

### ISSUE THREAD

**Issue by enrico28** [koalyptus/TableFilter#537]
The Property toolbar_position is present in the page 1.04 Paging
and in the page 1.09 Submit and reset button, but it refers to the
Property rows_counter. It would be useful to be able to place the
reset button in other positions.

Cheers!

**Comment by koalyptus** [comment]
tx @enrico28, unfortunate copy&paste. I have updated the wiki, so that reset button can be placed in other positions.
Just realised the `btn_reset` wasn't refactored into a structured literal object like the rest:
```javascript
var tfConfig = {
  btn_reset: {
    ...
  }
};
```
I will refactor this in the next release(s).
Cheers

**Comment by enrico28** [comment]
Thank you a lot

**Comment by koalyptus** [comment]
Hey @enrico28 I've just refactored the `btn_reset` options (v0.6.8) and corrected the `paging` wiki.
