### ISSUE TITLE
State restore from 'hash' does not work with checklist filter with regexp as values

### ISSUE THREAD

**Issue by maciex** [koalyptus/TableFilter#539]
State restore from 'hash' does not work with checklist filter with regexp as values

**Reproduction steps:**

1. Create table filtering for checklist column with custom options as below. Enable state saving as 'hash':
```
custom_options: {
    cols:[4],
    texts: [
        [
            'AIX','ALL''LINUX'
        ]
    ],
    values: [
        [
            'rgx:^AIX$','rgx:^ALL$','rgx:^LINUX$'
        ]
    ],
    sorts: [false]
}
```
2. Select 'ALL' in the column filter and try to reuse the URL in a new browser window

**Expected behavior:**
'ALL' item in the checklist is selected

**Observed behavior:**
When one enters the URL with saved state (`http://localhost:8000/patches.html#%7B%22col_4%22%3A%7B%22flt%22%3A%5B%22rgx%3A%5EALL%24%22%5D%7D%7D`) the item 'ALL' is not selected.

**Workaround:**
If one enters the URL `http://localhost:8000/patches.html#{%22col_4%22%3A{%22flt%22%3A[%22ALL%22]}}` it works. So I think that instead of the items value `rgx:^ALL$` the item's text 'ALL' is used to do the checklist selection, but the values are encoded in the URL.

**TableFilter version:** v0.6.2
**Browser and version:** Firefox 57.0
**OS and version:** Fedora 27

**Additional information:**

* Problem started happening recently, didn't happen in an older version of 
TableFilter: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by koalyptus** [comment]
Tx @maciex,
For pointing this out, 👍 for using the template

**Comment by koalyptus** [comment]
@maciex your fix is now merged and deployed, tx again for contributing.

**Comment by maciex** [comment]
@koalyptus I'm not sure why I added "fix for # 539" in that pull request...
These problems are not related.

Edit:
Oh wait, you edited that description. Was it  mistake?

**Comment by koalyptus** [comment]
My bad I thought they were related, ok i'll fix #539 in next releases

**Comment by koalyptus** [comment]
@maciex starting from `v0.6.9` the bug you pointed out should be fixed.
Cheers

**Comment by maciex** [comment]
@koalyptus Works fine. Thank you.
