### ISSUE TITLE
tablefilter interaction with already set pagination

### ISSUE THREAD

**Issue by in-dex** [koalyptus/TableFilter#556]
Hi Sir, first of all thank you for this wonderful code. I would like to ask sir if it's possible to filter an already paged table? say 1 have 20 items on a table i made a pagination which populate the table with 5 items per page, then i applied tablefilter, only in this case it only filters the active page 1 (items 1-5) and not all the other pages values ( 2, 3, 4) 

thank you in advance!

**Comment by koalyptus** [comment]
Tx @in-dex, 
try the `linked_filters` option:
http://koalyptus.github.io/TableFilter/linked-filters.html or
http://koalyptus.github.io/TableFilter/linked-filters-greyed-out-options.html

**Comment by in-dex** [comment]
hi sir , thank you for responding, took me a while to reply. in the end i opted to fully utilize tablefilter's functionality, discarded the pagination i made with another code and use tablefilters instead. and right now its working great!
