### ISSUE TITLE
No filter header when table has no rows

### ISSUE THREAD

**Issue by Nexpola** [koalyptus/TableFilter#562]
I've just upgraded from 0.5.18 to 0.6.16 and now when a table hasn't any row in the <tbody> but only the header row in <thead>, TF doesn't work.

I've tried to simplify my code removing any kind of parameter in the filtersConfig array (var filtersConfig = {}) and using a very simple empty HTML table but I can't find a way to make it working again.
Is it a regression, maybe caused by #533 ?

Thank you!

**Comment by koalyptus** [comment]
Hi @Nexpola, thanks for pointing this out, that behaviour has changed in purpose as a result of a refactoring affecting the way working rows are calculated (#533, #522), much simpler now. Unit tests were updated accordingly to test the new behaviour. 
It is probably debatable if a table with no working rows and only headers should display filters or not (selection filters would be empty btw). Please describe your use case/point of view.

I also jump on the occasion to remind this library hasn't reached a stable version, this would be v1.0 , things are still in flux and some behaviours could still change.

**Comment by Nexpola** [comment]
Hi @koalyptus ,
thanks for your reply. If there is the possibility to choose, my personal opinion is to keep filters even if there are no rows to display, and if possibile, showing the "No results" banner too because I suppose a user expects to see a "static" header with a variable "results pane" in continuity with a regularly populated table.

Otherwise I can write code to show a "No results" banner instead of the empty table :wink:

**Comment by koalyptus** [comment]
Hi @Nexpola,
the 'banner' fix (`no_results_message` option) should be a quick win, optionally generating the filters when no working rows, probably a bit more involved. I will try to sneak in the banner fix in next release(s).
Cheers

**Comment by koalyptus** [comment]
Hi @Nexpola starting from `v0.6.18`, the `No results` banner should be displayed by default in a table with no working rows. 
Cheers

**Comment by Nexpola** [comment]
Great! :+1:  
Thank you very much @koalyptus !

**Comment by koalyptus** [comment]
Probably nothing wrong on your side, I didn't realised you were getting that log message, I see the issue now, should be fixed in next release(s).

**Comment by Nexpola** [comment]
>  I didn't realised you were getting that log message
Directly in the Console of the Dev.Tool of Google Chrome :wink:

**Comment by koalyptus** [comment]
Yeah that's coming from https://github.com/koalyptus/TableFilter/blob/master/src/tablefilter.js#L146-L147

**Comment by koalyptus** [comment]
`v0.6.19` should now fix it, let me know how it goes.

**Comment by Nexpola** [comment]
It works perfectly! 👍

Thank you!
