### ISSUE TITLE
Checklist (popup) filter: Uncaught TypeError: Cannot read property 'nodeName' of undefined

### ISSUE THREAD

**Issue by ScottPurvis** [koalyptus/TableFilter#565]
Error occurs in checklist.js at 422 and 438 (check/uncheck): `if (li.nodeName === itemTag) {
`
Problem seems to start in checklist.js at 378: `let chkIndex = parseInt(o.id.split('_')[2], 10);`
Actual `o.id` is `flt2_PageContent_lg0_0`
`chkindex` ends up NaN.

Checklist filters aren't working at all on the page, text filters are working fine in the same page. Reset/clear fails for all

**Comment by koalyptus** [comment]
@ScottPurvis , provide more context, and a way to reproduce the issue, otherwise we can't help you. Those are working examples:
http://koalyptus.github.io/TableFilter/popup-filters.html
http://koalyptus.github.io/TableFilter/dynamic-external-filters.html

**Comment by ScottPurvis** [comment]
In both the examples that you provided, the input id="flt2_demo_0" (note: 2 underscores) on the "Clear" item that appears first in the checklist. Yes they work.

In my case the actual id is "flt2_PageContent_lg0_0" (note: 3 underscores). Doesn't work.

checklist.js at 378: let chkIndex = parseInt(o.id.split('_')[2], 10); This is not getting the trailing int when there are more than 2 underscores in the id.

Asp.net doesn't let me eliminate the extra underscore in my id.

**Comment by koalyptus** [comment]
Ok now I understand with more context. Yes, that's a 15 years old naughty legacy code to extract an id that survived many refactors... I will try to enhance it to not rely on id format.
I'll give you a sign when fixed.

**Comment by koalyptus** [comment]
Starting from `v0.6.18` it should be fixed. Let me know how it goes.
