### ISSUE TITLE
Initiate tablefilter with the same class.

### ISSUE THREAD

**Issue by MathieuThiry** [koalyptus/TableFilter#579]
I have a lot of tables on the same page and they're all identical. 

Would it be possible to initiate them all with the same class ?

Something like this : 
`<table class="foo"></table>`
`<table class="foo"></table>`
`new TableFilter('foo');`

Thanks again for all your work !

**Comment by koalyptus** [comment]
Thanks @MathieuThiry I appreciate,
to me a `TableFilter` instance represents and extends a single table element, not many of them, the overhead to instantiate multiple TableFilter instances with a css selector is minimal:
```javascript
document.querySelectorAll('.cities')
  .forEach(function(tbl) {
    new TableFilter(tbl).init();
  });
```
https://codepen.io/koalyptus/pen/rdwZZp

**Comment by MathieuThiry** [comment]
Yeah you right, thanks for the tip I don't know why I didn't think about that. 👍
