### ISSUE TITLE
filtering when table is empty

### ISSUE THREAD

**Issue by mmaction** [koalyptus/TableFilter#58]
i'm working on a table that uses filtering and sorting as well as multiselection with the advancedGrid extension.
everything works fine so far but some points seem no to work as expected:
1: If the table does not contain any data i get no on_after_filter event. in the status bar i see the message "Re-setting filters values..."
i've used this event for avoiding ugly, transient page renderings i experienced when table contained lots of data
2. Per default the webserver sends 12 "empty" table rows if table is empty (or 8 empty rows if only 4 entries present), so that the table looks always the same, including the alternating rows. if i use the rows_counter i get wrong a counter since the "empty" rows are counted as well. Whats the best workaround to deal with that?

-> it would be great to have a feature for defining a fixed number of rows showing in the table including alternate rows etc. and not worrying about rows_counter, grid_height, selection events etc.

i attached my htm file (removed irrelevant stuff):

thanks michael

____________________

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<title>WE512696_U04</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="expires" content="0" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="pragma" content="no-cache" />
<link rel="stylesheet" href="../global.css" type="text/css" />
<script language="javascript" src="../global.js" type="text/javascript"></script>
</head>

<body onload="if (typeof onPageLoad == 'function') {onPageLoad();}">
  
  <div id="divHeader">
    
    
    
    
  </div>
  <div id="divAppl">
    <ul>
      </ul>
  </div>

  <div id="divMenu">
    <table>
      <tr>
<td style="width: 4px;">&nbsp;</td>
<td style="width: 4px;">&nbsp;</td>
	  </tr>
    </table>
  </div>
  <div id="divContent">
    
    <table id="tableContent">
      <tr>
        <td style="vertical-align:top;">
          <table id="tableLeftNav">
            <tr><td class="leftNavTitle"></td></tr>
            <tr><td style="vertical-align:top;">

            </td></tr>
          </table>
        </td>
        <td style="vertical-align:top; width:100%;">
          
          <form action="MyFile.cgi" method="post">
          <table id="tableRightContent">
            
            <tr><td class="headline"></td></tr>
            <tr><td>
              
              <table id="tableDialog" >

                <tr>
                  <td class="boldLeft" style="vertical-align:bottom;padding-bottom:10px;">MyEntries</td>
                </tr>
                <tr>
                  <td>
                    
                    <table class="tblData" id="tblRemoteUnits">

                      <thead> 
                      	<tr>
                          <th class="bglightgray">No.</th>
                          <th class="bglightgray">Unit&nbsp;ID</th>
                          <th class="bglightgray">Address</th>
                          <th class="bglightgray">Entry&nbsp;Type</th>
                          <th class="bglightgray">Connection</th>     
                       	  <th style="display:none;"></th>
                      	  <th style="display:none;"></th>   
                      	</tr>
                      </thead>                                          
                      <tbody>
                      </tbody>
					          </table>
                  </td>
                </tr>
               
                <tr style="display:none;">
                  <td class="left" > 
                    <input type="hidden" id="hdnUnitId" name="hdnUnitId" value=""/> 
                    <input type="hidden" id="hdnRndUid" name="hdnRndUid" value=""/> 
                    <input type="hidden" id="hdnOrigin" name="hdnOrigin" value=""/>
                    <input type="hidden" id="remoteUnit" name="remoteUnit" value=""/>
                    <input type="hidden" id="hdnSelectedEntries" name="hdnSelectedEntries" value=""/>
                  </td>
                </tr>                 

                <tr><td style="height:15px;">&nbsp;</td></tr>
                <tr>
                  <td class="center"> 
                    <input name="btnAdd" id="btnAdd" type="submit" accesskey="a" title="Add (Alt + A)" value="Add"
                         /> 
                    &nbsp;&nbsp;&nbsp;&nbsp; 
                    <input name="btnModify" id="btnModify" type="submit" accesskey="m" title="Modify (Alt + M)" value="Modify"
                         /> 
                    &nbsp;&nbsp;&nbsp;&nbsp; 
                    <input name="btnDelete" id="btnDelete" type="submit" accesskey="d" title="Delete (Alt + D)" value="Delete" 
                         /> 
                    &nbsp;&nbsp;&nbsp;&nbsp; 
                    <input name="btnDeleteAll" id="btnDeleteAll" type="submit" accesskey="l" title="Delete All (Alt + L)" value="Delete All" 
                         /> 
                    &nbsp;&nbsp;&nbsp;&nbsp;                        	
                    <input name="btnUpdate" id="btnUpdate" type="submit" accesskey="u" title="Update (Alt + U)" value="Update" 
                         /> 
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <input name="btnDetails" id="btnDetails" type="submit" accesskey="t" title="Details (Alt + T)" value="Details"
                    	 />
                  </td>
                </tr>
               
               <tr><td style="height:25px;">&nbsp;</td></tr>   
                
                <tr >
                  <td class="center"> 
                    <input name="btnStart" id="btnStart" type="submit" style="width:150px" accesskey="r" title="Start (Alt + R)" value="Start Remote Session"
                         /> 
                    &nbsp;&nbsp;&nbsp;&nbsp; 
                    <input name="btnStop" id="btnStop" type="submit" style="width:150px" accesskey="b" title="Modify (Alt + B)" value="Stop Remote Session"
                         /> 
                  </td>
                </tr>
                
              </table> 
              
              
 	  <script language="javascript" src="../tablefilter/tablefilter.js" type="text/javascript"></script>     
 	  <script type="text/javascript">
      //<![CDATA[
      
        var tf = null;                        
      
        // --------------------------------------
        function showTable(o)
        // --------------------------------------      
      	{
      	  document.getElementById("tableDialog").style.visibility = "visible";      
      	}
            
        // --------------------------------------
      	function afterRowSelected(o, row)    
        // --------------------------------------  
      	{                
      	  var selection = tf.extension('advancedGrid')._ezEditTable.Selection;	      	  
          var activeRow = selection.GetActiveRow();
          if (activeRow)
          { 
	      	if (activeRow.cells[0].innerHTML == "")
	      	{
	      	  // empty row -> deselect it
                  selection.DeselectRow(activeRow);
      		  updateButtons();
	      	}
     		  else
      		{
              document.getElementById("hdnSelectedEntries").value = selection.GetSelectedValues();	
      			
              copyCellValue(activeRow, 2, "remoteUnit");
              copyCellValue(activeRow, 1, "hdnUnitId");
              copyCellValue(activeRow, 5, "hdnRndUid");
              copyCellValue(activeRow, 6, "hdnOrigin");  
          	}        
          }                	  	  	     
      	}
	      	      
        /* Setup table filtering */
      	tf = new TableFilter('tblRemoteUnits', 
      	{            		
      		/* filters behaviour */
      		base_path: '../tablefilter/',
      		col_widths: [ "50px", "145px", "340px", "90px", "155px" ],      
      		col_0: "none",
      		col_3: "select",
      		filters_row_index: 1,	
      		auto_filter: true,
      		auto_filter_delay: 0,
      		remember_grid_values: true,
      		alternate_rows: true,
      		mark_active_columns: true,
      		watermark: "search...",
      		on_after_filter: showTable,
      
      		/* drop-down filter */
      		display_all_text: "All",	 
      
      		/* grid layout */
      		grid_layout: true,
      		grid_height: '228px',	
      		grid_width: '770px',
      
      		/* status bar, rows counter, help instructions, reset button */
      		status_bar: true,
      		rows_counter: true,	
      		rows_counter_text: 'Number of Remote Units: ',	
      		btn_reset: true,
      		help_instructions: false,
      
      		/* extensions */     
    		extensions:
      		[
            	{
            	  name: 'sort',
      			    types: ['Number', 'String', 'ipaddress', 'String', 'String' ],	 
        	    },
      			{
      			  name: 'advancedGrid',
       			  vendor_path: '../ezEditTable/',
	      	    selection_model: 'multiple',	
      			  editable: true,	
	      	    editor_model: 'cell',
      			  on_after_selected_row: afterRowSelected,	      			
      			}	
          ],  
      
      	});      
      	tf.init();	    
            	                   		
      //]]>
      </script>
              
            </td></tr>
          </table>
        </form>
      </td>
    </tr>
    </table> 
  </div>
</body>
</html>

**Comment by koalyptus** [comment]
Hi mmaction,
For #1 use the ``on_filters_loaded'' callback fired just after filters instantiation at start-up instead of ``on_after_filter`` which is fired every time the table is filtered.

For #2 the rows counter is just doing its job, counting rows whether they have empty cells or not as it is not a 'records' counter. 
A way to implement your records counter based on described behaviour would be to count the empty rows returned by the server on the on_filters_loaded callback and substract them to the value displayed in rows counter DOM element. The adjustment would occur only once at start-up.
Give it a try.

**Comment by mmaction** [comment]
Thanks for your answers

#1: with an empty table i get the on_filters_loaded event but it still shows the message "Re-setting filters values..." forever in the status bar.

#2: i'll give it a try

**Comment by koalyptus** [comment]
You are using the ``remember_grid_values`` option, that message appears when filters values are retrieved from the cookie. Try to clear your cookie, or comment out ``remember_grid_values`` option.

**Comment by mmaction** [comment]
#1: i want to remember grid values so commenting out the option is no option. the point is that the message keeps staying in the status bar forever if no rows are present in the tbody element regardless if i delete cookies (which is a different behaviour compared to a table with some <tr> rows inside). but i'm going to add anyway a minimum of empty rows so i dont care but i thought it could be a bug...

#2: if i correct the rows counter via DOM (by accessing span element 'totrows_span_...') on the on_filters_loaded event it seems to update the value but just afterwards the value seems to be reset by another event.

**Comment by koalyptus** [comment]
My previous comment was only about validating the idea of what was causing the error, and this is now validated. So, commenting out ``remember_grid_values`` wasn't meant to be a solution. From what I see it smells like a bug occurring when there are no rows.

#2: Ok, forget previous suggestion, try to set the ``nbHiddenRows`` property just after ``TableFilter`` instantiation:
```
var tf = new TableFilter(...);
tf.nbHiddenRows =  yourNbOfEmptyRows;
tf.init();
```
Give it a try
