### ISSUE TITLE
Responsive tables with fixed header

### ISSUE THREAD

**Issue by MathieuThiry** [koalyptus/TableFilter#580]
I've been using TableFilter for a long time now and I thank you for that!

But if there's one feature missing it's clearly this one for me.

I've already seen https://github.com/koalyptus/TableFilter/issues/399 and https://github.com/koalyptus/TableFilter/issues/224 and I wonder if someday we can possibly hope to have this working with TableFilter?

Thank you anyway!

**Comment by koalyptus** [comment]
@MathieuThiry,
A nice to have, I have included this feature request in corresponding project.
Cheers

**Comment by MathieuThiry** [comment]
I look forward to see that, thanks @koalyptus!

**Comment by koalyptus** [comment]
Hi @MathieuThiry starting from v0.6.56 you can use the `sticky_headers: true` option to enable sticky headers. This example shows how to customise the sticky headers CSS definitions: http://www.tablefilter.com/sticky-headers-overrides.html
