### ISSUE TITLE
Create a changelog

### ISSUE THREAD

**Issue by noraj** [koalyptus/TableFilter#584]
Hi,
it would be great to have a changelog for each new versions. it can be a file, or pushing git tags with comments, etc...
It would be great to know what we are up to when updating.

**Comment by koalyptus** [comment]
Tx for your suggestion I'll see what I can do.

**Comment by koalyptus** [comment]
@noraj I currently don't have capacity to maintain a changelog file, however I have automated the creation of git tags from the CI. The associated commits should give more visibility on the changes contained in a new version.
Cheers

**Comment by noraj** [comment]
@koalyptus Seems fair.
