### ISSUE TITLE
filter from left to right

### ISSUE THREAD

**Issue by tbc233** [koalyptus/TableFilter#585]
First of all thank you for this wonderful scripts.
I hava a table with input based filter. Works very well.  I wanted to ask if it is possible to filter the string "from left to right".
So at the moment I can set columns_exact_match or not. But I would like that match the string from the left side. So that "exa" would find "example" but "amp" would not find "example". Or in other words: I would like to have it working as if the user would always add a star * to his search. Like now with columns_exact_match and someone typing "exa*" to find "example".

Is this possible?

**Comment by koalyptus** [comment]
Tx @tbc233,
you can create your own filtering rules by taking advantage of the numerous events or callbacks exposed by `TableFilter`. In your scenario you could use the `before-filtering` and `after-filtering` events to modify the user search terms and programmatically insert the desired modifiers, ie:
```javascript
var tf = new TableFilter(...):

tf.emitter.on(['before-filtering'], function(tf) {
  var originalQuery = tf.getFilterValue(0);
  var modifiedQuery = 'rgx:^' + originalQuery;
  tf.setFilterValue(0, modifiedQuery);
});

tf.emitter.on(['after-filtering'], function(tf) {
  var modifiedQuery = tf.getFilterValue(0);
  var originalQuery = modifiedQuery.replace('rgx:^', '');
  tf.setFilterValue(0, originalQuery);
});

tf.init();
```
in above snippet we take advantage of the regular expression modifier (`rgx:`) to find matches `from left to right`. The modifier is insert before filtering process and removed just after filtering is completed.

There are probably many ways to achieve that, you could also use the `cell_parser` delegate function where you define your own logic to parse the column cells and return the value according to your criterias, just to give an idea: http://www.tablefilter.com/filter-images.html

Cheers

**Comment by tbc233** [comment]
Works well!
Thank you so much!
