### ISSUE TITLE
Wrong Selection if filtering is active

### ISSUE THREAD

**Issue by mmaction** [koalyptus/TableFilter#59]
I have a table and filtering is active, e.g. column 2 input filter limits 1000 entries to 3. When i use Shift for selecting all 3 entries i get too many entries with the method "GetSelectedValues()". All the entries between first and third selected entry are returned as well though filtering is acitve.
I expected that GetSelectedValues() would return only the 3 visible and selected entries. Like this its impossible to process the data on the server side....

Here the used configuration:

 

         tf = new TableFilter('tblRemoteUnits',
         {                       
                 /* filters behaviour */
                 base_path: '../tablefilter/',
                 col_widths: [ "50px", "145px", "340px", "90px", "155px", null, null ],     
                 col_0: "none",
                 col_3: "select",
                 col_5: "none",
                 col_6: "none",     
                 filters_row_index: 1,  
                 auto_filter: true,
                 auto_filter_delay: 0,
                 remember_grid_values: true,
                 alternate_rows: true,
                 mark_active_columns: true,
                 watermark: "search...",
                 on_filters_loaded: onFiltersLoaded,
                 on_after_refresh_counter: adjustCounter,
                 on_after_filter: onAfterFilter,            
 
                 /* drop-down filter */
                 display_all_text: "All",       
 
                 /* grid layout */
                 grid_layout: true,
                 grid_height: '228px',  
                 grid_width: '770px',
 
                 /* status bar, rows counter, help instructions, reset button */
                 status_bar: true,
                 rows_counter: true,    
                 rows_counter_text: 'Number of Entries: ',      
                 btn_reset: true,
                 help_instructions: false,
 
                 /* extensions*/    
                 extensions:
                 [
                     {
                           name: 'sort',
                           types: ['Number', 'String', 'ipaddress', 'String', 'String' ],
                     },
                     {
                           name: 'advancedGrid',
                           vendor_path: '../ezEditTable/',
                           selection_model: 'multiple',       
                           on_after_selected_row: afterRowSelected,
                           nb_rows_per_page: 11,                                          
                     }      
            ], 
 
         });                  
         tf.init();

**Comment by koalyptus** [comment]
Please note the ``GetSelectedValues()`` method belongs to a third party library, [ezEditTable](http://codecanyon.net/item/ezedittable-enhance-html-tables/2425123?ref=koalyptus). For any ezEditTable API related issue, you can submit your comment [here](http://codecanyon.net/item/ezedittable-enhance-html-tables/2425123/comments?ref=koalyptus).

However, from what I see, you can easily achieve that by using the ``GetSelectedRows()`` instead, these would be the steps:
1. get the list of selected rows returned by ``GetSelectedRows()`` (ezEditTable)
2. get a list of the filtered rows by using the ``getValidRows()`` method (TableFilter)
3. create an empty array that will contain the rows values passed to the server-side 
3. iterate over the selected rows list (1) and push an item into the empty list (3) if the ``rowIndex`` of an item exists in the filtered rows
Pseudo code:
```
var selection = tf.extension('advancedGrid')._ezEditTable.Selection;
var selectedRows = selection.GetSelectedRows();
var filteredRows = tf.getValidRows();
var listForServer = [];
selectedRows.forEach(function(item) {
  if(filteredRows.indexOf(item.rowIndex) != -1) {
    listForServer.push(selection.GetRowValues(item));
  }
});
```
Give it a try.
