### ISSUE TITLE
Ajax Data - Load on demand

### ISSUE THREAD

**Issue by shekharsom** [koalyptus/TableFilter#594]
Is there any way I could work with Ajax Data? I mean it works beautifully currently with data table but if I have more than 5000 rows, it's not a good idea to send everything. 

I would prefer if TableFilter could talk to an Data API where it fetches on demand - 10 rows in the beginning and if something is searched, then connect back and get more data. Similarly if next page is clicked, get more data.

The only trouble I see is on sorting. But even in that case, the backend api should be able to help.

**Comment by koalyptus** [comment]
Hi @shekharsom, the basic principle/philosophy behind this library is to work on a pre-existing html table, no matter how that is generated. Loading data/rendering the table is intentionally beyond the scope of this script. This means it is the developer's responsibility to put an appropriate loading/rendering strategy in place especially for large datasets. `TableFilter` has an extensive API with many hooks available, lots of callbacks and events. So you can imagine having custom column filters asynchronously loading and rendering the data before taking advantage of the script's filtering capabilities.

**Comment by koalyptus** [comment]
You might have a look to the [documentation](http://koalyptus.github.io/TableFilter/docs/) and the [WIKI](https://github.com/koalyptus/TableFilter/wiki) for the callbacks and events.
Don't hesitate to ask.
