### ISSUE TITLE
Flat Directory Structure

### ISSUE THREAD

**Issue by robcpq** [koalyptus/TableFilter#600]
Due to the limitations of a web app, I am able to put the tablefilter files (JS, CSS, and other resources) in a single directory. I was able to achieve it my manually modifying references, but I'd love to see a build that is flat by default so I can easily upgrade. 

Great product BTW! I love that it is pure JS!

**Comment by koalyptus** [comment]
tx @robcpq, `TableFilter` assumes a certain folder structure relative to main stylesheet for static resources like images, those are in the `themes` folder. However, you can achieve a 'flat' structure at runtime by using following configuration options:
- `base_path`
- `stylesheet`

and then use a custom css option for each element featuring an image, I know that is not a quick but depending on the features you enable there not that many images :).

If you are wiling to dive into the library code, then follow the steps in [Development](https://github.com/koalyptus/TableFilter#development) section of the README and and eventually fork the repo.

There is no plan to have a flat directory version at this stage.

Cheers
