### ISSUE TITLE
Tables using `alternate_rows` starts with 'even' row after filtering

### ISSUE THREAD

**Issue by kapep** [koalyptus/TableFilter#603]
For tables which have `alternate_rows` set, the alternating background color is reversed after applying any filters. For example, if the background color of every odd row is gray and the color of every even row is white when loading the table, applying any filter makes the background color of odd rows white and of even rows gray.

**Reproduction steps:**

1. Go to https://koalyptus.github.io/TableFilter/alternating-rows.html
2. Note the gray color of the first row
3. Apply any filter (e.g. type "Sydney" in the "from" filter)
4. Note the white color of the first row

**Expected behavior:**

The background color should stay consistent

**Observed behavior:**

The background color should is inconsistent and changes

**TableFilter version:** 0.6.38
**Browser and version:** Firefox 
**OS and version:** Win10

**Additional information:**

The even/odd classes seems to be applied wrongly. After filtering, the first `tr` has the class `even`. Playing around with the table header I also noticed that it even/odd classes are also applied to `tr` elements in `<thead>` (but only if there are more than two `tr` elements). So it seems header rows are included when calculating odd/even rows, that could be part of the issue.

**Comment by koalyptus** [comment]
Tx for pointing this out @kapep, it is a known issue that was never captured in a ticket. I will try to fix it in a next release.

**Comment by koalyptus** [comment]
@kapep, issue should be fixed starting from v0.6.39. Really appreciated you used the template for submitting bugs 😄
