### ISSUE TITLE
sort extension does not use cell_parser function

### ISSUE THREAD

**Issue by vojtechovsky** [koalyptus/TableFilter#607]
Sort extension does not understand `cell_parser` function(if defined).

**Reproduction steps:**
1. http://koalyptus.github.io/TableFilter/custom-filtering.html - here is a special parser for filtering
2. It knows how to handle `select` and `checkbox` values => filtering works fine
3. change `col_types` for first and last column to `string`

**Expected behavior:**
 Sort extension should use the same function like filters in order to get values table cells.

**Observed behavior:**

Sort extension tries to use different logic to get values from cells.

**TableFilter version:**  tablefilter@0.6.39
**Browser and version:** chrome 66.0.3359.181 (Official Build) (64-bit)
**OS and version:** windows 10

**Comment by koalyptus** [comment]
Tx for pointing this out @vojtechovsky, the inconsistency you described above should be fixed starting from `v0.6.41`. You can see the fix in action in same demo: http://koalyptus.github.io/TableFilter/custom-filtering.html
