### ISSUE TITLE
alternating rows background color persistence

### ISSUE THREAD

**Issue by enrico28** [koalyptus/TableFilter#610]
Hi there,
alternating rows background color is not maintained after sorting

Expected behavior:
alternating rows background color should be maintained after sorting

Thanks
Enrico

TableFilter version: v0.6.39 or greater
Browser and version: IE11 and Chrome Version 64.0.3282.119 (Official Build) (32-bit)
OS and version: Windows 7 Enterprise

Problem started happening recently, didn't happen in an older version of
TableFilter: Yes
Problem can be reliably reproduced, doesn't happen randomly: Yes

A working example reproducing the issue

`<!DOCTYPE html>
<html>
<head>

<link rel="stylesheet" type="text/css" href="my_dir/tablefilter/style/tablefilter.css" />
<script type="text/javascript" src="my_dir/JQ/es6-promise.min.js"></script>
<script type="text/javascript" src="my_dir/tablefilter/tablefilter.js"></script>

</head>
<body>

<table border="0" cellspacing="1" cellpadding="10">
<tr><th colspan=6>Defectivity Request: TBR   </table></center>

<table border="0" id="req-table" cellspacing="1" cellpadding="10">

<thead><tr id="persist-header"><th>Id<th>Lot name<th>Operation<th>Author<th nowrap>Creation Date<th>Defectivity Reference</th></tr>
</thead>

<tbody>

<tr><td>4963<td>1811G<td>883<td>Stefania<td>08 Jun 2018 14:22<td>Michele<tr><td>4301<td>05494<td>720<td>Nunzio<td>03 Apr 2018 16:31<td>Michele<tr><td>401<td>44898<td>819<td>Paola<td>07 Mar 2018 17:42<td>Giovanna<tr><td>1620<td>49761<td>556<td>Marina<td>22 May 2017 13:54<td>Silvia<tr><td>1253<td>16700<td>952<td>Gabriella<td>06 Apr 2017 17:39<td>Noemi<tr><td>1095<td>16700<td>295<td>Giulia<td>23 Mar 2017 08:31<td>Lucia

</tbody>

</table>

<script data-config>

var tfConfig = {
    base_path: '../my_dir/tablefilter/',
    responsive: false,

    grid: true,

    col_0: '',
    col_1: '',
    col_2: '',

    col_3: '',
    col_4: '',
    col_5: '',

    filters_row_index: 0,
    exact_match: false,
    alternate_rows: true,

    clear_filter_text: '< Clear >',

    rows_counter: {
        text: 'Data Rows: '
    },

    btn_reset: {
       toolbar_position: 'left'
    },

    status_bar: true,

    col_types: [
        'number', null, 'number',

        null,
        { type: 'date', locale: 'en-US', format: ['{dd} {months} {yyyy} {hh}:{mm}'] },
        null
    ],

    enable_default_theme: true,

    popup_filters: {
        adjust_to_container: false
    },

    no_results_message: {
        content: 'Data not found'
    },

    highlight_keywords: true,

    extensions: [{
        name: 'sort'
    }]

};

var tf = new TableFilter('req-table', 1, tfConfig);

tf.init();

</script>

</body>
</html>

`

**Comment by koalyptus** [comment]
Hi @enrico28, tx for pointing this out, this is fixed starting from v0.6.41.
Have a look at online demos, eg: http://www.tablefilter.com/sort.html to see the fix.
Cheers

**Comment by koalyptus** [comment]
Btw, I confirm it was introduced by v0.6.39... unfortunate regression

**Comment by enrico28** [comment]
Hi,

I am deeply sorry, but even with version v0.6.41 
I have the same behavior in my context 

After a series of sorting, the background of all the rows is white


Thanks
Enrico

**Comment by enrico28** [comment]
It depends on the browser.
Everything works correctly with Chrome, but not with IE11

Cheers

**Comment by koalyptus** [comment]
Ok @enrico28 I just posted a codepen with your HTML table and associated config that works with IE11:
https://codepen.io/koalyptus/pen/XYeMVW

IE now needs an additional polyfill to support the `name` property of a function, eg:
https://unpkg.com/function.name-polyfill@latest/Function.name.js
from https://github.com/JamesMGreene/Function.name
It was the first one I found on github/npm, no particular reason to use this one.

Cheers

**Comment by enrico28** [comment]
Hi,

I knew I had to use es6-promise.min.js with IE11

Now I have also added Function.name.js and it works as expected.

Thanks a lot
Enrico
