### ISSUE TITLE
how to achieve filtering with ROWSPAN more than 1

### ISSUE THREAD

**Issue by antseba** [koalyptus/TableFilter#62]
Hello;
Is it possible to filter table while some line in some column may have more than 1 rowspan?

 See the attached example.

![filtering](https://cloud.githubusercontent.com/assets/14903217/11437548/8e92e71a-9529-11e5-8016-862e1d518919.PNG)

I tried, but then the format is completely wrong

**Comment by koalyptus** [comment]
Hi @antseba, 
``TableFilter`` does not fully support ``rowspan`` and ``colspan`` at the moment. If this is an acceptable solution for your project, I suggest to disable the row highlighting if this is the only issue. Perhaps you could implement a different behaviour like row highlighting on mouseover, it can be done easily with some CSS styling.

**Comment by koalyptus** [comment]
Closing as no news since
