### ISSUE TITLE
Good day, I have a dynamic table on Bootstrap

### ISSUE THREAD

**Issue by grad23** [koalyptus/TableFilter#623]
Good day, I have a dynamic table on Bootstrap, is it possible to use TableFilter for such tables? Now it simply reports that at least 1 row is needed for the work, although the data is loaded into the table. Data is loaded via AJAX. Thanks and waiting for reply. grad23@yandex.by

**Comment by koalyptus** [comment]
@grad23 make sure you instantiate `TableFilter` when the async request to populate has completed and the table rows are effectively rendered. From what you describe it seems to be a timing issue related to AJAX.

**Comment by grad23** [comment]
Ok, more or less managed to make friends filter and table, but when pagination from bootstrap-table data selection is not for all values of the table, but only for those displayed on the page. For example, in the table of 100 values from 0 to 99, the pagination bootstrap-table = 10 values on the page, respectively, the "5" filter finds and shows, and 11 (which on the next page) does not see. 
And the second, after setting the value of col_2: 'select', (col_2 = field_id as the simplest without using the formatter) instead of the list of values gives an error.
Uncaught TypeError: Cannot read property 'cells' of undefined
    at dropdown.js:218
    at tablefilter.js:2828
    at Dropdown.build (dropdown.js:188)
    at Dropdown.onSlcFocus (dropdown.js:60)
    at HTMLSelectElement.<anonymous> (dropdown.js:127)

![image](https://user-images.githubusercontent.com/14808520/42781925-207fbf82-8950-11e8-9b76-5dde8c3fb953.png)

**Comment by grad23** [comment]
I put script for table-filter in to .on('load-success.bs.table', function (e, data, row, value) { , so all data are loaded by AJAX before...

**Comment by koalyptus** [comment]
If you publish an example reproducing the issue on codepen or equivalent, I will be able to understand a little bit more.

**Comment by koalyptus** [comment]
can be re-opened if needed
