### ISSUE TITLE
Row counting is wrong when using cache

### ISSUE THREAD

**Issue by rimace** [koalyptus/TableFilter#624]
There are some cases in which the row counting feature counts one row to much. 

**Reproduction steps:**

You need a Table with <thead> and <tbody>. In the <thead> section I have the header of the rows but also a second row for counting the sums like this:
```
<thead>
<tr>
	<th>Article number</th>
	<th>Production amount</th>
	<th>amount articles on stock</th>
</tr>
<tr>
	<th></th>
	<th id="sumPlannedProductionAmount"></th>
	<th id="sumArticleOnStock"></th>
</tr>
</thead>
```
Also to reproduce this bug you need TableFilter to use a cache like this:
```
state: {
	types: ['local_storage'],
	filters: true,
	sort: false
},
```

Now let's say there is one header row for the column titles, one header row for the sums and 10 rows with content. When visiting the page for the first time, the counted rows are 10 (which is correct). After filter something the counted rows are still correct. But after remove evrey filter the counted rows are 11 and not 10 anymore. You can even close the browser and open it again, it will still be wrongly counted.

**Expected behavior:**

The counted rows should be 10 again.

**Observed behavior:**

The counted rows are now 11. So when there is a cache, the row counting behavior is different.

**TableFilter version:** 0.6.47
**Browser and version:** Firefox 52 ESR and Firefox 61
**OS and version:** Fedora 28 and Windows 7

**Additional information:**

* Problem started happening recently, didn't happen in an older version of 
TableFilter: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

Any idea on what is different when counting without a cache and with cache.

**Comment by koalyptus** [comment]
Hi @rimace, have a look at this demo which is is similar with multi-line headers, localstorage enabled  and rows counter: http://www.tablefilter.com/grouped-headers.html
Can you reproduce the issue?
Make sure you instruct TableFilter to start the filtering from the expected row, as explained in that demo.

**Comment by koalyptus** [comment]
can be re-opened if required.

**Comment by rimace** [comment]
Sorry for bothering again, I'll tried to dig into it and created a simple test case.
[issue-624.zip](https://github.com/koalyptus/TableFilter/files/2468992/issue-624.zip)

When opening the html file it will show the Amount "3" is shown for the rows. After filtering and deleting the filter the Amount "4" is shown, even though there are only 3 rows.

**Comment by rimace** [comment]
@koalyptus Sorry for bothering again, I'll tried to dig into it and created a simple test case. [issue-624.zip](https://github.com/koalyptus/TableFilter/files/2478820/issue-624.zip)

When opening the html file it will show the Amount "3" is shown for the rows. After filtering and deleting the filter (just delete it and press enter) the Amount "4" is shown, even though there are only 3 rows.

So the count method delivers different results on the initialization and after filtering the table.

**Comment by koalyptus** [comment]
@rimace I'll have a look, tx for providing an example reproducing the issue

**Comment by koalyptus** [comment]
Ok you simply need to instruct TableFilter from which row should start the filtering process:
```
let tf = new TableFilter("commissionsList", {
	base_path: 'assets/',
	rows_counter: {
		text: 'Amount : '
	},
	extensions: [
    {
        name: 'colOps',
        id: [
        	'sumPlannedProductionAmount'
        ],
        col: [3],
        operation: ['sum'],
        exclude_row: [2],
        decimal_precision: [0],
    	tot_row_index: [2]
    }]
}, 2);

tf.init();
```
The numeric parameter `2` tells TableFilter to start filtering from row index 2 (count is done excluding the added filters row):
https://github.com/koalyptus/TableFilter/wiki/2.0-TableFilter-class
http://www.tablefilter.com/grouped-headers.html
