### ISSUE TITLE
'[empty]' Filter operator treats HTML image and iframe tags as empty cells

### ISSUE THREAD

**Issue by cbaket** [koalyptus/TableFilter#625]
The '[empty]' Filter operator treats HTML elements that do not contain text as an empty cell.
For example, a cell that only contains an image: **<img alt="" src="http://telo.org/wp-content/uploads/2015/11/vehiclehire1.jpg" style="width: 400px; height: 501px;">** will be treated as an empty cell.

**Reproduction steps:**

1. create a cell with an iframe or an image
2. use the 'custom_options' property as follows:
    custom_options: {
        cols: [4],
            texts: [
                [
                    '*',
                    'Empty'
                ]
            ],
            values: [
                [
                    '[nonempty]',
                    '[empty]'
                ]
            ],
            sorts: [false]
        },
3. apply the filter 'Empty' in the column filter

**Expected behavior:**
Cells with HTML tags that don't contain text but there is actually the HTML tag in there should not be treated as empty cells.

**Observed behavior:**
Cells with HTML tags like images and iframes are treated as empty cells

**TableFilter version:** 0.6.42 (latest github version from dist)
**Browser and version:** Version 67.0.3396.99 (Official Build) (64-bit)
**OS and version:** macOS High Sierra 10.13.4

**Comment by koalyptus** [comment]
Tx for pointing  this out @cbaket, I'll try to fix this in the next release(s).

**Comment by koalyptus** [comment]
@cbaket should be fixed starting from `v0.6.50`, let me know how it goes.
