### ISSUE TITLE
Method for reloading table data

### ISSUE THREAD

**Issue by dset0x** [koalyptus/TableFilter#627]
Hello. First of all, thank you for this great piece of software.

I'd like to know if there is a recommended way for updating the table data. What I have been doing is replacing the `<tbody>` element which serves my purposes fine.

With TableFilter however, that essentially negates filtering and sorting. I have tried two methods so far, each with its problems:

1.
``` javascript
if (table_filter.isInitialized()) {
    table_filter.emitter.emit('initialized', table_filter);
}
```
This restores all functionality, except extensions (I use `sort`, which stops working after).

2.
``` javascript
if (table_filter.isInitialized()) {
    table_filter.destroy();
    table_filter.init();
}
```
This also restores all functionality, but has side-effects. For example, the user will lose the focus from the filter field they were searching in.

Thanks in advance.

**Comment by koalyptus** [comment]
nice @dset0x !
