### ISSUE TITLE
is there any way to link external select for operators?

### ISSUE THREAD

**Issue by newpaulinhu** [koalyptus/TableFilter#631]
I have a input filter where at his left side i have a select with the operators (< , > , <= )

But i can't apply to my search without have to "put" the value inside the filter input using the "before-filtering"

![image](https://user-images.githubusercontent.com/1041608/43734038-df285cf4-998c-11e8-831b-e80301126012.png)

is there any way or function on emmiter where i can apply the operator before filtering without  have to concat the operator to the input

**Comment by koalyptus** [comment]
Hi @newpaulinhu,
this comment should help you https://github.com/koalyptus/TableFilter/issues/585#issuecomment-380980821

In that code example the `modifiedQuery` in your case would be something like:
`var modifiedQuery = yourDropDownValue + originalQuery;`

Tell me how it goes

**Comment by newpaulinhu** [comment]
Thanks! the comment really help me, but in my case i solved a little different, because i have a few filters like that, and i can't use the getFilterValue or getFilterId that need to pass the index, like that:
tf.getFilterValue(0);

in my case i solve it by finding the active filter by the method getActiveFilterId so my Before Filter is like that:

tf.emitter.on(['before-filtering'], handleFilterSelect);
tf.emitter.on(['after-filtering'], cleanFilterSelect);

function handleFilterSelect(tf){
	var filterField = $('#' + tf.getActiveFilterId());
	var selectedOperator = filterField.parent().parent().find('.operators').text();
	filterField.val(selectedOperator + filterField.val())
}

And my after-filtering:

function cleanFilterSelect(tf){
	var filterField = $('#' + tf.getActiveFilterId());
	filterFieldval(filterField.val().replace(/[`~!@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/gi, ''))
}

Thanks

**Comment by koalyptus** [comment]
Awesome @newpaulinhu, I am glad to see that example inspired you.
Cheers
