### ISSUE TITLE
Dynamically hide filters that no longer apply?

### ISSUE THREAD

**Issue by M0RGaming** [koalyptus/TableFilter#644]
Is it possible to have an option to hide filters that no longer apply to what is being shown?

For example,
```
+---------+-------+------+
| Yes     | False | True |
+---------+-------+------+
| Finally | No    | Da   |
+---------+-------+------+
```
If we filter the third column to the word [True] then is there a way to make the first column drop-down filter no longer display the inapplicable options (Finally), as the second row is no longer displayed?

Sorry if this is confusing, Thanks -M0R

**Comment by cjohnsonuk** [comment]
Have you tried linked_filters?
"if set true this property modifies the filtering behaviour: drop-down filters become linked and the linked filter will displays only the filtered data (default - false)."

http://koalyptus.github.io/TableFilter/linked-filters.html

**Comment by M0RGaming** [comment]
I have tried this, and it works, thank you.

**Comment by M0RGaming** [comment]
Btw, do you know how to close an issue
