### ISSUE TITLE
Checklist: Enable Select All

### ISSUE THREAD

**Issue by allanbrito90** [koalyptus/TableFilter#649]
Hi,

Does have a way to enable a "Select All" checkbox item in the same way as "Clear" checkbox item?

I'm doing through selectOptions but I don't know if there is a better way.

Thanks in advance.

**Comment by koalyptus** [comment]
Hi @allanbrito90,
There is no such an option available for the checklist filter type. I confirm `selectOptions` method is the way to go.

Cheers
