### ISSUE TITLE
Purpose of "headers_row_index"

### ISSUE THREAD

**Issue by MathieuThiry** [koalyptus/TableFilter#654]
Hi,

Could you explain me what's the purpose of this please ?

    grid_layout: {
      headers_row_index: 1
    } 

Documentation says that : "defines which row contains the column headers (default - 0)"

But I tried with several different numbers (0 / 1 / 2) and I didn't see any change. 

Thanks !

**Comment by koalyptus** [comment]
Hi @MathieuThiry,
`headers_row_index` is a legacy configuration option that should no longer be public, my bad. For practical reasons, when `grid_layout` is on headers should always be above the filters row.
I have just updated the [wiki page](https://github.com/koalyptus/TableFilter/wiki/1.03-Grid-layout), above option is no longer available.

Cheers

**Comment by MathieuThiry** [comment]
And what about this : 

    grid_layout: {
        default_col_width: '100px'
    },

Is it still working ?

**Comment by koalyptus** [comment]
Yes still there<https://github.com/koalyptus/TableFilter/blob/master/src/modules/gridLayout.js#L317>, conditionally applied if:

  1.  there is no `col_widths`  setting defined
  2.  there are no `width` html attributes on the headers' cells
  3.  there are no `style.width` applied to headers' cell

If none of the above conditions is satisfied then the default value is applied.

Cheers
________________________________
De : Mathieu Thiry <notifications@github.com>
Envoyé : vendredi 21 septembre 2018 14:11
À : koalyptus/TableFilter
Cc : koalyptus; Comment
Objet : Re: [koalyptus/TableFilter] Purpose of "headers_row_index" (#654)


And what about this :

grid_layout: {
    default_col_width: '100px'
},


Is it still working ?
