### ISSUE TITLE
add plotting capabilities 

### ISSUE THREAD

**Issue by roykingtree** [koalyptus/TableFilter#678]
Not an issue, but an enhancement proposal. Add simple 2d plotting based on data from 2 columns. Bar, scatter, and line-plots would be ideal.

**Comment by koalyptus** [comment]
Seems to be out of the scope of this library to me. You can always use TableFilter's API to get the table data and use any charting library to plot that data.

**Comment by cjohnsonuk** [comment]
I've got mine working using one of the many free charting tools out there.  I use the API to create a second table with stats based on the first data table to allow the viewer to carry out analysis then create charts from that data (using the API again).  Works really well as we were able to choose and later swap which charting tool we use to get one that best meets our requirements
