### ISSUE TITLE
Potential problem with multiple tables on one page

### ISSUE THREAD

**Issue by qzminski** [koalyptus/TableFilter#679]
If you have a lot multiple table elements on the page, it may happen that script crashes on one of them due to duplicate ID. JS error log:

```
tablefilter.js:1 Uncaught TypeError: Cannot read property 'style' of undefined
    at TableFilter.getRowDisplay (tablefilter.js:1)
    at eval (tablefilter.js:1)
    at eval (tablefilter.js:1)
    at TableFilter.getValidRows (tablefilter.js:1)
    at AlternateRows.processAll (tablefilter.js:1)
    at AlternateRows.init (tablefilter.js:1)
    at eval (tablefilter.js:1)
    at Array.forEach (<anonymous>)
    at TableFilter.initFeatures (tablefilter.js:1)
    at TableFilter.init (tablefilter.js:1)
```

One workaround is to create the elements with some delay:

```js
$('[data-my-table]').each((i, el) => {
    setTimeout(() => {
        (new TableFilter(el, { alternate_rows: true })).init();
    }, (i + 1) * 10);
});
```

**Reproduction steps:**

1. Create multiple `<table>` elements on one page.
2. Create TableFilter instances for all elements with option `alternate_rows: true`.
3. Reload the browser a few times.

**Expected behavior:**

All TableFilters should be initialized correctly.

**Observed behavior:**

Some of the tables get the same ID caused by this line of code:

https://github.com/koalyptus/TableFilter/blob/master/src/tablefilter.js#L125

It does not happen always and on the same table element, as it depends on how quick the JS engine does the job. So one time it will work without a problem, the other time it will crash on random table element.

**TableFilter version:** 0.6.65 but probably affects the latest as well
**Browser and version:** Chrome or any other
**OS and version:** macOS or any other

**Additional information:**

* Problem started happening recently, didn't happen in an older version of 
TableFilter: No idea ¯\_(ツ)_/¯
* Problem can be reliably reproduced, doesn't happen randomly: No

**Comment by koalyptus** [comment]
Tx @qzminski for pointing that out, no doubt the way the id is generated is at best very "weak" :). I advise for the time being to define a unique id for every table until a proper fix is implemented.
Cheers

**Comment by koalyptus** [comment]
@qzminski starting from `v0.6.79` this should be fixed.
Let me know how it goes.

**Comment by qzminski** [comment]
Works great, thanks a lot!
