### ISSUE TITLE
Grouping rows

### ISSUE THREAD

**Issue by jamesRUS52** [koalyptus/TableFilter#680]
Hello
How can I configure TableFilter for grouping rows and subTotal by group?
![screenshot](https://user-images.githubusercontent.com/39707635/52465610-3d957200-2b90-11e9-876a-dde2f0d96b21.png)

**Comment by koalyptus** [comment]
Hi @jamesRUS52,

Grouping sub-total is not spported, but you might be able to achieve that by leveraging TableFilter's API.

Cheers

**Comment by jamesRUS52** [comment]
Hi, @koalyptus 
Could you give me an example? What function of API should I use?

**Comment by cjohnsonuk** [comment]
Inline group totals is a bad idea.  You'd be better creating a separate table with the group totals in.  That way adding group totals won't be adding data the table from where you are getting your group totals source data from.

Here are some to start with: 
(source http://koalyptus.github.io/TableFilter/docs/class/src/tablefilter.js~TableFilter.html)

getFilteredColumnData(colIndex: any, includeHeaders: boolean, exclude: any): ArrayReturn the filtered data for a given column index 

getFilteredColumnValues(colIndex: any, includeHeaders: boolean, exclude: any): ArrayReturn the filtered values for a given column index 

getFilteredData(includeHeaders: Boolean, excludeHiddenCols: Boolean): ArrayReturn the filtered table data based on its columns data type definitions with following structure: [ [rowIndex, [data0, data1...]], [rowIndex, [data0, data1...]] ]

getFilteredValues(includeHeaders: Boolean, excludeHiddenCols: Boolean): ArrayReturn the filtered table values with following structure: [ [rowIndex, [value0, value1...]], [rowIndex, [value0, value1...]] ]

These allow you to pull the data from the table (filtered data in this case so only whats visible).  You can then manipulate this with JS and push the results into a group totals data table.

**Comment by koalyptus** [comment]
FYI, up-to-date auto-generated docs are now available here: http://www.tablefilter.com/docs/class/src/tablefilter.js~TableFilter.html
