### ISSUE TITLE
Div inside table

### ISSUE THREAD

**Issue by badalraut** [koalyptus/TableFilter#699]
When a div accordian is added to a td in the table then the paging stops working unless grid_layout is set to true.

**Comment by koalyptus** [comment]
provide more details or follow [this](https://github.com/koalyptus/TableFilter/blob/master/CONTRIBUTING.md#template-for-submitting-bug-reports) or provide an online example to increase your chances to get help.
My 2cents, the accordian ui component is interfering somehow with the toolbar items, e.g. accordian placeholder is covering the pagination buttons.

Cheers
