### ISSUE TITLE
in bootstrap 4 if used the row counter and paging bar goes to bottom of grid.

### ISSUE THREAD

**Issue by badalraut** [koalyptus/TableFilter#701]
in bootstrap 4 if used the row counter and paging bar goes to bottom of grid.

**Comment by koalyptus** [comment]
@badalraut, TableFilter's toolbar is displayed by default in a `caption` element and apparently bootstrap 4 prefers displaying caption elements at the bottom of a table. This codepen shows how to workaround this inconvenience: https://codepen.io/koalyptus/pen/NmamJL , have a look to the CSS override.

TableFilter also gives you the ability to render most of the features in desired container elements, refer to this example for the toolbar: https://www.tablefilter.com/external-toolbar.html . This could also be an alternative solution for integrating with bootstrap 4.

**Comment by badalraut** [comment]
Tried external toolbar but in vain.

**Comment by koalyptus** [comment]
Not sure what made your external toolbar attempt unsuccessful, but the same [codepen](https://codepen.io/koalyptus/pen/NmamJL) now features an additional table with an external toolbar integrating with bootstrap 4.

**Comment by badalraut** [comment]
I am using adminlte.io 3 in the project with it but also tried with only
bootstrap r not working. Moment I use bootstrap 3.3.7 all is well.
