### ISSUE TITLE
custom_options.sorts = [false] has no effect

### ISSUE THREAD

**Issue by ebw44** [koalyptus/TableFilter#703]
In the example https://www.tablefilter.com/custom-filter-options.html the custom_option sorts = [false] seems to have no effect.

**Comment by koalyptus** [comment]
Hi @ebw44 ,
in above example open the browser console and type following js instructions:
```javascript
tf.customOptions.sorts = [true];
tf.destroy();
tf.init();
```
Inspect the `POP` column filter and note the options sorted in alphanumeric manner and not in order of appearance, it seems to have an effect :).

Cheers

**Comment by ebw44** [comment]
Thanks @koalyptus,
I misunderstood the "customOptions.sorts". I though I could use it to disable sorting for a specific column when it concern only the drop-down (as clearly stated in the [documentation](https://github.com/koalyptus/TableFilter/wiki/1.02-Main-features
)
Is there anyway to disable sorting for a specific column? One of my column is a checkbox, and the interaction between sorting and checking is not great.

Thanks

**Comment by jmcarson** [comment]
I had this same question. It looks like setting the sort: types (or col_types) for the column to 'none' will disable sorting for that specific column. For example either of the following disables sorting for the first column. 
extensions:[
            { 
                name: 'sort',
                types: ['none', 'string'] 
            },
        ],
or:
col_types: ['none','string']

I found the none type here.
https://github.com/koalyptus/TableFilter/wiki/3.1-Sort
