### ISSUE TITLE
Error in IE11

### ISSUE THREAD

**Issue by krzcho** [koalyptus/TableFilter#705]
Just going to the examples page (http://www.tablefilter.com/examples.html) with IE11:

SCRIPT5007: Unable to get property 'container' of undefined or null reference

![image](https://user-images.githubusercontent.com/18173/56803061-f4b19900-6821-11e9-9a7c-f2325c5c7bb3.png)

**Comment by koalyptus** [comment]
Hi @krzcho, do other non-codepen examples in http://www.tablefilter.com work, e.g. https://www.tablefilter.com/grouped-headers.html, work with IE11?

**Comment by krzcho** [comment]
http://www.tablefilter.com/grouped-headers.html work fine, there is just single "undefined" error there

![image](https://user-images.githubusercontent.com/18173/56805613-ebc4c580-6829-11e9-93cb-59d364723ea6.png)

**Comment by koalyptus** [comment]
ok this seems to indicate the codepen embedded in examples page is missing the polyfills described in 
https://codepen.io/koalyptus/pen/XYeMVW

tx for pointing this out

**Comment by krzcho** [comment]
Yes, that solves the issue; thanks

**Comment by peternewman** [comment]
Hi @koalyptus ,

Firstly thanks for the project, I'm looking at migrating from something older I was using and this seems loads better!

The sample in the dist doesn't seem to have them either:
https://unpkg.com/tablefilter@0.7.2/dist/starter.html
