### ISSUE TITLE
Doesnt work with html files created in windows

### ISSUE THREAD

**Issue by Guyver1wales** [koalyptus/TableFilter#707]
So I found this script while google searching for a way to make a html table searchable and filterable.
I'm a windows server admin and use PowerShell to automate various domain wide tasks.
One task I'm currently working on is to pull all certificates from all our domain servers and create a searchable/filterable table so we can search our entire domain for a specific certificate and see how many servers its installed on.
All this is fine and I can get the code I want and get it into a complete html document no issues.

My issue is when adding the scripts code to my html output as outlined in the guide.
This is what I'm using:
`    <script src="tablefilter/tablefilter.js"></script>
    <script data-config>
        var filtersConfig = {
            base_path: 'tablefilter/',
            alternate_rows: true,
            rows_counter: true,
            btn_reset: true,
            loader: true,
            status_bar: true,
            mark_active_columns: true,
            highlight_keywords: true,
            extensions: [{ name: 'sort' }]
        };
        var tf = new TableFilter('demo', filtersConfig);
        tf.init();
    </script>`

I have been tearing my hair out with this all evening and have finally found the issue as I ended up creating two identical files that show as identical in WinMerge.

the working file (which is a copy of the Starter.html file with my table copied into it) is showing in winmerge as a file type of:
1252(windows-1252) Unix.

My non-working file which wont load the javascipt correctly and allow me to filter my table shows in WinMerge as:
1200(iso-10646-ucs-2 BOM) Win

This is the only difference I can find between the two files as they have 100% identical code content. (confirmed with WinMerge)

I am creating the html file by running the following in PowerShell and then adding the js script code as outlined in the projects guidance.
Get-Service | ConvertTo-Html | Out-File -FilePath 'C:\temp\Services.html'

**Comment by Guyver1wales** [comment]
I have found a workaround after looking at the documentation for Out-File.
I can now get it working if I use Out-File -Encoding ASCII

Get-Service | ConvertTo-Html | Out-File -FilePath 'C:\temp\Services2.html' -Encoding ascii

It would still be interesting to know why this dependant on the encoding?

**Comment by koalyptus** [comment]
@Guyver1wales,  glad you worked it out.
Html markup uses characters `<` and `>` to delimit an element, those characters were probably encoded therefore file content wasn't proper html. Just a theory, don't know enough about the techs you are using. TableFilter js lib does not seem to be part of the problem.
Cheers

**Comment by Guyver1wales** [comment]
nothing wrong with the html, that was working perfectly. as I said, WinMerge is showing the code in the html file as being identical. the javascript simply wasn't loading into the page.

For testing I'm just using windows 10 64bit. PowerShell 5.1 and your current latest version.

Steps to replicate:
1. Download tablefilter and unzip the /tablefilter folder to C:\temp so that the javascript filepath is:
"C:\temp\tablefilter\tablefilter.js"
2. double click on starter.html supplied with tablefilter and check it works as expected (it should)
3. run powershell as admin and run the following command:
Get-Service | ConvertTo-Html | Out-File -FilePath 'C:\temp\Services.html' 
4. copy the <script> sections from starter.html to services.html under the </table> element as outlined in your docs.
5. open Services.html and the html table loads as expected but the javascript is not and so the filtering elements are not loaded.

optional:
6. open services.html and copy the table structure.
7. open starter.html and replace the table with the one from services.html
8. open starter.html and it will load the javascript correctly and show the filtering elements correctly.

So the issue is either:
a. your script only works with 1252(windows-1252) Unix encoded text files and doesnt work with windowspowershell default 1200(iso-10646-ucs-2 BOM) encoding?
or
b. javascript as a language only wotks with 1252 encoding?

Unfortunately I know nothing about javascript as I only code with PowerShell being a Windows Server admin.
Hopefully the steps above will allow you to replicate the issue as t only requires windows and powershell and nothing else.
