### ISSUE TITLE
How do you filter a column for * when its NOT a wildcard?

### ISSUE THREAD

**Issue by Guyver1wales** [koalyptus/TableFilter#709]
I'm currently using tablefilter to filter a html report which is esentially a 20,000+ certificate database of every certificate installed on all our domain servers.

we have a lot of wildcard certificates that are named *.mydomain.co.uk

with a regular expression I can escape a * by doing `\*` and it will treat the * as a valid character to search rather than treating it as a wildcard.

How do I escape * when filtering my tables so I can actually search for the * character and not have it treated as a wildcard??

**Comment by koalyptus** [comment]
Have you tried to use a regex by inserting `rgx:\*` in the filter?

**Comment by koalyptus** [comment]
Alternatively you could define the `like_operator` option to another value than `*`, eg:
```javascript
var tf = new TableFilter('my-table-id-here', {
  like_operator: '[*]'
});
tf.init();
```

**Comment by Guyver1wales** [comment]
> Have you tried to use a regex by inserting `rgx:\*.mydomain.co.uk` in the filter?

thats what I was looking for, cheers!

**Comment by koalyptus** [comment]
Alternatively you could define the `like_operator` option to another value than `*`, eg:
```javascript
var tf = new TableFilter('my-table-id-here', {
  like_operator: '[*]'
});
tf.init();
```
