### ISSUE TITLE
bug: refresh_filters

### ISSUE THREAD

**Issue by michel-lepage** [koalyptus/TableFilter#71]
Hello Max,

congratulation for this nice tool!

it seems that refresh_filters does not work.
when a selection is made on one column, the oher drop down filters are not actualized.

cheers
michel

**Comment by koalyptus** [comment]
Hi Michel,
refresh_filters is now called linked_filters. You can check it out in this demo:
koalyptus.github.io/TableFilter/linked-filters.html

Cheers

**Comment by michel-lepage** [comment]
Great !!!

Thanx a lot
