### ISSUE TITLE
clear_filter_text is not applied

### ISSUE THREAD

**Issue by dset0x** [koalyptus/TableFilter#714]
**Describe the bug**
Setting `clear_filter_text` has no effect on the Clear text.

**Reproduction steps:**
1. Set `clear_filter_text` to an array in your configuration. [Example](https://gist.github.com/dset0x/147de9fb1fa1c68fa67768abc92c8816)
2. `var table_filter = new TableFilter(document.querySelector('.units-index-table'), tf_config);`

**Expected behavior**
`table_filter.clearFilterText` is "Clear"

**Observed behavior:**
`table_filter.clearFilterText` is not "Clear"

**TableFilter version:** 0.6.89
**Browser and version:** Firefox 66
**OS and version:** Linux
**Device:** My laptop. Also your laptop. Well, I hope you can reproduce it.

**Additional information/context:**
Issue also seems to occur here: https://www.tablefilter.com/external-filters.html

* Problem started happening recently, didn't happen in an older version of TableFilter: No, also fails with version 0.6.55
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by koalyptus** [comment]
Tx @dset0x for pointing this out, it will be fixed in the next version(s).

**Comment by koalyptus** [comment]
@dset0x it should be fixed starting from `v0.6.92`. Let me know how it goes.
Reminder: this option only applies to `select`, `multiple` and `checklist` filters.
Cheers

**Comment by dset0x** [comment]
Fantastic! Thanks so much, @koalyptus.
