### ISSUE TITLE
dataSortDesc

### ISSUE THREAD

**Issue by dengf** [koalyptus/TableFilter#716]
Hi-

What is the key name in the configration to sepcify dateSortDesc? I went through the wiki and docs, but failed to find the instruction on so.

Thanks

**Comment by dengf** [comment]
Hi--
To clarify on my ask, I was trying to overload the sorted select options in filter.  The data type for the value and I would  like to be able to sort them in descending order. Thanks

**Comment by koalyptus** [comment]
@dengf, apologies for late reply due to parental leave.
Please consider `filter_options_sorter` setting in https://github.com/koalyptus/TableFilter/wiki/1.05-Drop-down-filter, it allows you to implement your own sorter for the filter options.
Cheers

**Comment by koalyptus** [comment]
@dengf, FYI `v.0.6.94` enhances filter options sorting logic and now supports date data type. Use the `sort_filter_options_desc` option to do so as shown in this example: https://codepen.io/koalyptus/pen/pmXqob

**Comment by dengf** [comment]
@koalyptus, Thanks a ton.
