### ISSUE TITLE
Display count in select filter

### ISSUE THREAD

**Issue by CPASimUSante** [koalyptus/TableFilter#717]
**Enhancement/feature description**
I would like to have the count of rows displayed in the select filter for each option.

Thank you

**Screenshots and GIFs**
![select](https://user-images.githubusercontent.com/14015697/57848103-6a34d780-77d8-11e9-8571-4d6ad1b8639f.png)

**Comment by koalyptus** [comment]
Hi @CPASim,
Probably a nice to have, but to achieve your particular use case I advise to take advantage of TableFilter's API, something like [getColumnData](http://www.tablefilter.com/docs/class/src/tablefilter.js~TableFilter.html#instance-method-getColumnData) is probably a candidate to get the data you need to implement your grouping logic.
Cheers
