### ISSUE TITLE
Sticky headers does not work in the IE 11

### ISSUE THREAD

**Issue by anilak28** [koalyptus/TableFilter#718]
**Describe the bug**
Hi

The Sticky headers does not work in the IE , Chrome works perfectly.
Could it be fixed?
or may be you have work around?

BR

**Comment by koalyptus** [comment]
Hi @anilak28, I have no workaround available for that one, I advise to find the right CSS rules to make it work under IE. FYI, [sticky](https://github.com/koalyptus/TableFilter/blob/master/src/tablefilter.js#L880) the CSS class used by TableFilter to make headers sticky.

Cheers
