### ISSUE TITLE
Sort Extension not working...

### ISSUE THREAD

**Issue by alingham** [koalyptus/TableFilter#736]
Hi there,

I've tried getting sort working for my set of columns. They have multiple headers so I made my TableFilter from your Grouped headers example.
However, the sort function did not work.
So I've been hunting around, changing the code and everything.

In the end, I even set up a test page and direct copied your code from the Grouped headers example across.

[See my Test Page Here](http://arakura.school.nz/pvs/test-table.php)

Am I missing something?

What else do I have to include on the server?
At this stage on my server is literally the dist folder which I put in includes/tablefilter...

**Comment by koalyptus** [comment]
Hi @alingham,
From what I see in your example, TF is not able to load the extensions js script needed for the sorting functionality, `tf-0-8dba489b6aa8af63974b.js` file is missing from `includes/tablefilter` folder:
![image](https://user-images.githubusercontent.com/8214629/64084903-ec8adc80-cd72-11e9-95d1-82358f1dbb86.png)

**Comment by alingham** [comment]
Oh awesome. Working now. Thanks
So that wasn't entirely clear in the instructions for manual install... It just said to copy the tablefilter.js file across.... The other looked like a temporary file so I didn't bother with it...

Cheers for the help!
