### ISSUE TITLE
Weird result for filtering

### ISSUE THREAD

**Issue by l2** [koalyptus/TableFilter#74]
Considering the following code:

    <head> <meta charset="UTF-8"> 
    <script src="TableFilter/dist/tablefilter/tablefilter.js"></script>
    </head>
    <html>
    <body>
    <table id="table1">
    <tr>
    <td>
    aa
    </td>
    <td>
    bb
    </td>
    <tr>
    <td>
    21.1.16
    </td>
    <td>
    21.1.05
    </td>
    </tr>
    <tr>
    <td>
    34.234
    </td>
    <td> rr</td>
    </tr>
    </table>
    <script language="javascript" type="text/javascript">
    	var myTF = new TableFilter("table1");
    	myTF.init()
    </script>
    </body>
    </html>

By typing "2" in the first box, the results should be the both rows of the table but in fact, I only obtain the second one. I think something is wrong in this case.

**Comment by koalyptus** [comment]
With no configuration supplied, the component assumes the first row is the headers row therefore it is simply skipped. Add a headers row and it will be fine.

**Comment by l2** [comment]
I try this

    <head> <meta charset="UTF-8"> 
    <script src="TableFilter/dist/tablefilter/tablefilter.js"></script>
    </head>
    <html>
    <body>
    <table id="table1">
    <tr>
    <th>aa</th>
    <th>bb</th>
    </tr>
    <td>21.1.18</td>
    <td>21.1.04
    </td>
    </tr>
    <tr>
    <td>21.1.16</td>
    <td>21.1.05</td>
    </tr>
    <tr>
    <td>34.234</td>
    <td> rr</td>
    </tr>
    </table>
    <script language="javascript" type="text/javascript">
        var myTF = new TableFilter("table1",1,
        {base_path:'TableFilter/dist/tablefilter/'}
        );
        myTF.init()
    </script>
    </body>
    </html>

But it's still not working (filtering by 1 or 2 in the first box)

**Comment by koalyptus** [comment]
Hmmm, try to add an opening ``<tr>`` before ``<td>21.1.18</td>``

**Comment by l2** [comment]
.... sorry for the mistake but same result

    <head> <meta charset="UTF-8"> 
    <script src="TableFilter/dist/tablefilter/tablefilter.js"></script>
    </head>
    <html>
    <body>
    <table id="table1">
    <tr>
    	<th>aa</th>
    	<th>bb</th>
    </tr>
    <tr>
    	<td>21.1.18</td>
    	<td>21.1.04</td>
    </tr>
    <tr>
    	<td>21.1.16</td>
    	<td>21.1.05</td>
    </tr>
    <tr>
    	<td>34.234</td>
    	<td> rr</td>
    </tr>
    </table>
    <script language="javascript" type="text/javascript">
        var myTF = new TableFilter("table1",1,
        {base_path:'TableFilter/dist/tablefilter/'}
        );
        myTF.init()
    </script>
    </body>
    </html>

**Comment by l2** [comment]
If i write "21.1.16" in the first row, I can obtain the good result.

**Comment by koalyptus** [comment]
Indeed something weird, using the ``*`` operator seems to filter as expected: ``*2``.
Lebelled this as a bug, I will investigate it, nice one :) !

**Comment by koalyptus** [comment]
So, it turns out those values were resolved as dates (with . separator) and therefore string searches as ``2`` were not matched by the filtering logic. I just pushed v0.0.18 allowing those types to be searchable by strings.
Tell me how it goes.

Cheers,
Max

**Comment by l2** [comment]
It works fine.

Thank for your very quick answer.

**Comment by koalyptus** [comment]
Cool, thanks for pointing this out.
Closing this issue.
