### ISSUE TITLE
empty values

### ISSUE THREAD

**Issue by joseqq** [koalyptus/TableFilter#740]
how I can filter and have only the rows with empty values in a field?
and second I would know if it is possible to filter results in a field that values is *. When I filter with the select option it do not filter the results. 

Thanks.

**Comment by koalyptus** [comment]
Hi @joseqq,
>how I can filter and have only the rows with empty values in a field?

You can filter by `[empty]` operator as listed in [here](https://github.com/koalyptus/TableFilter/wiki/4.-Filter-operators). This demo features it drop-down filters using that operator: http://www.tablefilter.com/grouped-headers.html

>I would know if it is possible to filter results in a field that values is *. When I filter with the select option it do not filter the results

By default `*` is an operator as per https://github.com/koalyptus/TableFilter/wiki/4.-Filter-operators. Please have a look to this [thread](https://github.com/koalyptus/TableFilter/issues/709).

Cheers

**Comment by joseqq** [comment]
I really apreciate. thank you
