### ISSUE TITLE
Sort not working - similar to #736

### ISSUE THREAD

**Issue by tbeertje21** [koalyptus/TableFilter#747]
I downloaded the current version (zip from github) and try to run http://localhost:5000/starter.html
Sorting does not work.

1. unzip current version
2. start webserver in .../dist/ so that localhost:5000/starter.html is the test page
3. open start.html in browser. Everything appears and filters do work. Sorting does not work.

Errors similar to #736 appear:

1) in the console:
...
GEThttp://localhost:5000/tablefilter/style/tablefilter.css
[HTTP/1.0 200 OK 9ms]
GEThttp://localhost:5000/tablefilter/tf-0-9d0f2f7840b2a1cccbd0.js
[HTTP/1.0 404 NOT FOUND 25ms]
ChunkLoadError: "Loading chunk 0 failed.
(error: http://localhost:5000/tablefilter/tf-0-9d0f2f7840b2a1cccbd0.js)"
	requireEnsure http://localhost:5000/tablefilter/tablefilter.js:116:26
	loadExtension http://localhost:5000/tablefilter/tablefilter.js:16301:44496
	initExtensions http://localhost:5000/tablefilter/tablefilter.js:16301:43176
	initExtensions http://localhost:5000/tablefilter/tablefilter.js:16301:43070
	init http://localhost:5000/tablefilter/tablefilter.js:16301:29846
	<anonymous> http://localhost:5000/starter.html:489:5
bootstrap:187:42
GEThttp://localhost:5000/favicon.ico
[HTTP/1.0 404 NOT FOUND 0ms]
Loading failed for the <script> with source “http://localhost:5000/tablefilter/tf-0-9d0f2f7840b2a1cccbd0.js”. starter.html:1:1
GEThttp://localhost:5000/tablefilter/style/themes/btn_clear_filters.png

2) at network level:
Request URL: http://localhost:5000/tablefilter/tf-0-9d0f2f7840b2a1cccbd0.js
Status code: 404

**Expected behavior**
Sorting must work.
When testing on http://localhost:5000/test/test-sort-key.html the behaviour is the same: no hand appears and sorting does not work.
No onAfterSort or on_sort_loaded is triggered: a console.log() in there at the first line of the function never outputs something.

**Observed behavior:**
I never get a "hand" on the headers like I do get it on https://www.tablefilter.com/sort-custom-type.html

**Screenshots**
Not applicable (see error from the browser network and console above.

**TableFilter version:** "version": "0.6.99" (current master, Latest commit
71103cd 9 days ago), from package.json (The '?' in some examples returns "TableFilter v{VERSION}", as well on '?' on https://www.tablefilter.com/sort-custom-type.html )
**Browser and version:** Any.
**OS and version:** W8.1
**Device:** Laptop Asus K95

**Additional information/context:**
None

* Problem started happening recently, didn't happen in an older version of TableFilter: No. Version 0.6.99 is my first download. I tried 0.6.94 and tests do not work either. In 0.the 6.94 test/test-sort-key.html, the hand does appear (no network errors: 200 for GET http://localhost:5000/dist/tablefilter/tf-0-753b2cd0ac94345cc829.js) but the sorting does not work.

* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by tbeertje21** [comment]
As a by-pass, just tried v0.6.88 too, in firefox and chrome: the starter does work but not test/test-sort-key.html of either version: the hand appears but no sorting happens.

**Comment by koalyptus** [comment]
Tx for pointing this out @tbeertje21, unfortunately dist package was missing a file, the 404 you are listing above. Starting from v0.6.100 the issue should be fixed. 
Cheers

**Comment by tbeertje21** [comment]
Indeed, I got v0.6.100 and so far, everything works great! This distribution is "fixed"... Thanks a lot, and enjoy your responsiveness!
