### ISSUE TITLE
FIXED: Thanks....lower case not sorting as case insensitive

### ISSUE THREAD

**Issue by Pajservices** [koalyptus/TableFilter#765]
Just trying to sort a table of data and the lower case items appear to be sorted first - even though I have the case_sensitive: false, set.

**Reproduction steps:**

1. Create Data Table that includes the following text in column 0

"Crane Tracks, MANUAL OVERHEAD TRAVELLING CRANE TRACK (GAS PLANT)"
"Fall Arrest Equipment, FALL ARREST LANYARD"
"Trestle / Stand, LOAD SHAFT SUPPORT STAND"
"Winch, Manual, FALL ARRESTER/WINCH (FITTED TO RESCUE SHEERLEGS)"
"forklift Attachment 6Mts, FORK LIFT TRUCK FORK EXTENSIONS"

2. Set the Configuration parameters as follows;
    case_sensitive: false,

**Expected behavior:**

I expected the lower case "forklift...."to be sorted within the rest of the table - after 'Fall..." case insensitive wise

**Observed behavior:**

lower case sorts first

**TableFilter version:** Latest as at 8th Feb 2020
**Browser and version:** Chrome 80.0.3987.87
**OS and version:** Windows Server 2019 with IIS10 

**Additional information:**

* Problem started happening recently, didn't happen in an older version of 
TableFilter: Not Sure - only just started to use
* Problem can be reliably reproduced, doesn't happen randomly: YES

**Comment by cjohnsonuk** [comment]
I had an issue previously where the case of my config didn't match the case of the config in the documentation , eg for example :  `Case_Sensitive: false`, instead of `case_sensitive: false`,  

I was looking for something much more complicated than it really was

It was an easy one to overlook and a quick and easy check to carry out.  HTH

**Comment by koalyptus** [comment]
Hi @Pajservices,

the `case_sensitive` option is used to define the filter [matching behaviour](https://github.com/koalyptus/TableFilter/wiki/1.02-Main-features), it does not apply to column sorting.

Based on this [example](https://www.tablefilter.com/sort.html) configuration in `col_types` define the column you want to make case insensitive by using the `caseinsensitivestring` value.

Alternatively, you could also define it at the sort configuration level, ie:
```javascript
...
extensions: [{ 
  name: 'sort',
  types: ['caseinsensitivestring']
}]
...
```

Be aware you can also create custom sorters if you need to, this example gives an idea how to achieve that:
https://www.tablefilter.com/sort-custom-type.html

Cheers

**Comment by Pajservices** [comment]
Thank you so much that works a treat.

 

Regards

 

Phil Jones

**Comment by Pajservices** [comment]
Not sure if anyone can help me with this, a bit cheeky I know but struggling.

 

I am using the tablefilter and it works really well. I have a table, and on each row is a check box – used to select items to be passed to another process. 

 

On Click of a check box I have a function in JS that counts how many have been checked so far and displays the number. Also works by allowing me to Click – hold SHIFT – and Click further down to check a list of rows.

 

Unfortunately, when the table is filtered and I Click-SHIFT-Click ...it also includes the hidden rows that have been filtered out. (When clearing the filter you can see they are checked).

 

I am trying to figure out the code to put in my function to check if the row is hidden/filtered out or not – and if it is – uncheck it. Have tried getting the element, looking at style etc...but not working...

 

Any help would be much appreciated.

 

 

 

 

Regards

 

Phil Jones

**Comment by Pajservices** [comment]
Quick Question re Tablefilter

 

When using a ‘Select’ Filter the drop down list is quite long, but when using ‘multiple’ it seems to be limited to 3 or 4 lines 

 

 

Is it possible to change the length of the drop down box – maybe in CSS or a config option?

 

 

Thanks in Advance

 

 

Regards

 

Phil Jones

PAJ Services
