### ISSUE TITLE
Identify when in 'Filter Mode'

### ISSUE THREAD

**Issue by Pajservices** [koalyptus/TableFilter#771]
I have a long table that contains a Check box on each line for selection, and some code that allows consecutive check boxes to be selected by 'Click First - Hold Shift - Click Last'. 

When the table is filtered though, the 'hidden' lines  between the start and end are also selected (which I can understand) - so I have tried to enhance my code to determine if a line is 'filtered out /hidden'. I also have code that runs through the table and counts the Checks, and tried to determine which are filtered so as to ignore them but can't seem to find which attribute to check for.

Is there any way of knowing when in 'filtered mode' or identifying which are hidden.

I have attached the code which 'ticks' all in between, which I need to amend to ignore the 'hidden' ones

// Code used to allow SHIFT Click on boxes and tick them all between (chkbox is id of the chkbox field )
	var lastChecked = null;
    $(document).ready(function() {
          var $chkboxes = $('.chkbox');
          $chkboxes.click(function(e) {
              if(!lastChecked) {
                lastChecked = this;
                return;
              }
  
              if(e.shiftKey) {
                 var start = $chkboxes.index(this);
                 var end = $chkboxes.index(lastChecked);
                 $chkboxes.slice(Math.min(start,end), Math.max(start,end)+ 1).prop('checked', lastChecked.checked);
              countCheckboxes ();
              }
   
              lastChecked = this;
           });
    });`

**Comment by koalyptus** [comment]
Hi @Pajservices,

TableFilter exposes an API to know which rows are filtered, `tf.isRowDisplayed(rowIndex)` or which rows are valid `tf.isRowValid(rowIndex)`, `tf` being the `TableFilter` instance:
- http://www.tablefilter.com/docs/class/src/tablefilter.js~TableFilter.html#instance-method-isRowDisplayed
- http://www.tablefilter.com/docs/class/src/tablefilter.js~TableFilter.html#instance-method-isRowValid

Those helper methods should help you in the checkboxes behaviour logic.

Cheers

**Comment by Pajservices** [comment]
Thanks so much

 

Regards

 

Phil Jones
