### ISSUE TITLE
Error loading "tf-1-aa77ded8a1c16cdd0238.js"

### ISSUE THREAD

**Issue by matteo-savino** [koalyptus/TableFilter#781]
When my page loads, the file "tf-1-aa77ded8a1c16cdd0238.js" is not found.

**Reproduction steps:**

1. I include the TableFilter like this: "<script src="https://unpkg.com/tablefilter@0.6.105/dist/tablefilter/tablefilter.js"></script>"
2. My page displays the tables
3. The table works but I have many errors in the console

**Expected behavior:**

View my data in the tables without errors in the console

**Observed behavior:**

The data is displayed in the tables, but the console is filled with errors, all a consequence of this:
"tablefilter.js:1 GET https://unpkg.com/tablefilter@0.7.0/dist/tablefilter/tf-1-aa77ded8a1c16cdd0238.js net::ERR_ABORTED 404"

**Screenshots and GIFs**

https://drive.google.com/open?id=1BxeXRnTfqIWSuTZqv19Ws9-B1_PEwXtv

or

<img width="354" alt="TableFilterError" src="https://user-images.githubusercontent.com/65533755/82190748-cd78ae80-98f1-11ea-830b-abd75cfeb38f.png">

**TableFilter version:** 0.6.105
**Browser and version:** Google Chrome 81.0.4044.122 (Official build) (64-bit)
**OS and version:** Windows 10 Pro

**Additional information:**
I tried to analyze the problem and I realized that the path where "tablefilter.js" goes to look for the file "tf-1-aa77ded8a1c16cdd0238.js" is wrong. 
The path through which I reach the file from my browser is the following:
"https://unpkg.com/browse/tablefilter@0.6.105/dist/tablefilter/tf-1-aa77ded8a1c16cdd0238.js"

* Problem started happening recently, didn't happen in an older version of 
TableFilter: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by koalyptus** [comment]
Hi @matteo-savino, in the screenshot I see a couple of exceptions happening before the the 404 you are highlighting, and at top the CORB message which refers to the `tf-1-aa77ded8a1c16cdd0238.js` file in question. It gets lazily loaded by `tablefilter.js`.

Is this happening in other browsers?
Have you tried to import `https://unpkg.com/tablefilter@latest/dist/tablefilter/tablefilter.js` instead?

**Comment by matteo-savino** [comment]
Thank you for your answer,
I imported the tables through a link with a static version. Using the link you sent me, it started working without problem again.

Thanks so much!
