### ISSUE TITLE
Allow to remove copy right notice by setting help_instructions value

### ISSUE THREAD

**Issue by lijieyin** [koalyptus/TableFilter#788]
**Enhancement/feature description**
Allow to remove copy right notice by setting help_instructions value

**Steps which explain the enhancement/feature**
1. When click on "?/Help" to pop up help information, at the bottom of the pop up window, a URL and a copy right information are shown as in the image below, currently you allows us to set help_instructions to provide customized help information, however the copyright and URL cannot be overridden unless directly modify the tablefilter.js file, is it possible to allow us to remove this URL and copy right information by setting  help_instructions  value?

**Current and suggested behavior**
[Describe current and suggested behavior here]

**Why would the enhancement be useful to most users**

**Screenshots and GIFs**
![image](https://user-images.githubusercontent.com/18475920/91241026-05ac4a80-e787-11ea-8e39-cca88d6860ec.png)

**Additional context**

**Describe alternatives you've considered**

**TableFilter Version:** [Enter TableFilter version here]

**Comment by koalyptus** [comment]
Please note you can use the `defaultHtml` property on the `Help` instance to modify the instructions footer, ie:
```javascript
var tf = new TableFilter('my-table-id', myTfConfig);
var help = tf.feature('help');
help.defaultHtml = '';
tf.init();
```

Refer to http://www.tablefilter.com/docs/class/src/modules/help.js~Help.html#instance-member-defaultHtml

**Comment by lijieyin** [comment]
Thank you very Koalyptus, it works perfectly.

Regards
Lijie YIN
________________________________
