### ISSUE TITLE
ColOps: Format of the calculated number doesn't respect locale

### ISSUE THREAD

**Issue by rimace** [koalyptus/TableFilter#789]
**Describe the bug**
The ColOps extension ignores the options of the TableFilter options. All operations result in a US American format, even if the locale was to `de` for example. I also set the `thousands_separator` and `decimal_separator`, those those seemed to be ignored by ColOps

**Reproduction steps:**
1. Create a table using and additionally use these options:
```
locale: 'de',
thousands_separator: '.',
decimal_separator: ',',
```
2. Use ColOps to calculate some sums/means

**Expected behavior**
The number format of the sums should match the locale's format that was defined in the options.

**Observed behavior:**
The number format of the sums are always US American format, using comma as thousand separator and point as a decimal separator.

**Screenshots**
![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

**TableFilter version:** 0.7.3
**Browser and version:** Firefox 78 ESR and 80
**OS and version:** Fedora 32
**Device:** HP EliteBook G2

**Additional information/context:**
Currently this is the workaround I use:
```
[...]
on_after_operation: function() {
    column.innerHTML = Number.parseFloat(column.innerHTML.replace(",", "")).toLocaleString("de-DE");
}
```

* Problem started happening recently, didn't happen in an older version of TableFilter: No, It has been like htat for years.
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by koalyptus** [comment]
Hi @rimace,
Please have a look to this demo: http://www.tablefilter.com/data-types.html for formatting numbers.

Cheers

**Comment by rimace** [comment]
Hello @koalyptus ,
thanks for your help, this works!
While surfing the code, I found that the `thousandsSeperator` in [tablefilter.js:818](https://github.com/koalyptus/TableFilter/blob/3e763efac990e9e09827249d6dd9c27daf4ffac6/src/tablefilter.js#L818) is never used anywhere in the code.

Still I close this issue as I now have the answer thanks to you :)

**Comment by koalyptus** [comment]
Tx for spotting that confusing left-over reference to `thousandsSeperator`, I will remove it in next version(s).
Cheers
