### ISSUE TITLE
Callback after Paging is done

### ISSUE THREAD

**Issue by ak111in** [koalyptus/TableFilter#796]
**Enhancement/feature description**
Just like there is callback after filtering is done, is there any callback when paging is done as paging is completed after filtering.

**Comment by koalyptus** [comment]
The `grouped-by-page` event is probably what you are looking for. Below an example of usage:
https://codepen.io/koalyptus/pen/ZEboajz

Resources:
- https://github.com/koalyptus/TableFilter/wiki/1.04-Paging#events

Cheers

**Comment by ak111in** [comment]
thanks
