### ISSUE TITLE
Filters only considering the primary unique values, Not the respective filtered unique values

### ISSUE THREAD

**Issue by SaiPrabhu611** [koalyptus/TableFilter#813]
Firstly, Thank you Table Filter, it helped me a lot

Using this package, I found that the filters on columns are only taking primary unique values into account, but not the respective filtered values, 
Let's consider Column1 has 5 values, if I select a value from dropdown and get the result, in the column 2 filter, it still shows the values which are primarily taken, not the filtered or present result values.

Anyone if solved or can solve and share your views would be appreciated.

Thank you

**Comment by cjohnsonuk** [comment]
Try looking at the linked_filters setting . 
this may be what you are looking for

There's an example here
https://www.tablefilter.com/linked-filters.html
