### ISSUE TITLE
Date column sort with blanks entries

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#95]
I've got a table with two columns of dates in the format yyyy-mm-dd
When I have blank dates (or replace blank dates with a "-" symbol) sorting on that column produces seemingly random  results.  In a post on your website (http://tablefilter.free.fr/comments.php?l=en&a=1) is suggests using v2.5
I've got the table filter from github:
 tablefilter v0.0.14 by Max Guglielmi
 build date: 2015-12-06T11:22:34.280Z 

Am I doing something wrong?
C

**Comment by koalyptus** [comment]
Have you configured the data type for those columns ?
There are many ways to configure them, if those are the only format for dates in your table:
```
var yourConfig = {
...
  default_date_type: 'YMD',
...
};
```

Check this demo out: http://koalyptus.github.io/TableFilter/data-types.html
