### ISSUE TITLE
Pop-up filters + getHeadersText() don't work properly

### ISSUE THREAD

**Issue by Insorior** [koalyptus/TableFilter#99]
I tried to export my headers texts with getHeadersText(), and a popup_filters option enabled. For filters such as 'checklist' or 'select' all the data contained in the filter form is pasted on the export rather than just the titles.

I see 2 solutions for this problem :

* Programmaticaly selecting only the titles (not the filters form options)

* (better to me as it solves another problem that I'm about to post on this forum) putting popup filters on a separate line below the header line

thanks for your support !

**Comment by koalyptus** [comment]
Hi @Insorior, thanks for pointing this out, I appreciate.
- I will fix the ``getHeadersText`` helper method as it is definitely a bug.
- As you noticed, the popup filters UX needs to be improved, better support for touch screens with bigger icons etc. This is part of the roadmap but will happen a bit later, as still focusing in architectural changes at the moment (``pub-sub-refactoring`` branch).

Cheers

**Comment by koalyptus** [comment]
@Insorior,
I just published v0.0.23 with ``getHeadersText`` helper method fix.
Cheers

**Comment by Insorior** [comment]
Awesome ! 

Thank you for quick fix !
